### ISSUE TITLE
error while running rails generate ahoy:stores:fluentd

### ISSUE THREAD

**Issue by fatroller** [ankane/ahoy#101]
Hi,

I get an error when I try to run the below command. I'm on Windows 7 64 bit. and rails 4.0.9

E:\ap01\dev\rmmi>rails generate ahoy:stores:fluentd
Could not find generator ahoy:stores:fluentd.

I've also included gem 'fluent-logger' in my gem file and then ran bundle install. I'm trying to run the ahoy_matey gem.

Thanks in Adavnce!

**Comment by ankane** [comment]
The Fluentd store is only available if you point to the master branch (unreleased).
