### ISSUE TITLE
visits not getting tracked from chrome 

### ISSUE THREAD

**Issue by fatroller** [ankane/ahoy#102]
Hi,

The visits table is not getting populated if I access from chrome browser. The records get generated using IE Or Firefox. There is no error generated. Would any one by any chance know why this is case ?
TIA

**Comment by anandvc** [comment]
@fatroller  Are your cookies enabled in Chrome?

**Comment by fatroller** [comment]
Yes, the cookies were enabled. But then I tried ahoy.reset(); in the browser console and it started updating db records for next visit. Thanks for getting back in any case.
