### ISSUE TITLE
Events & Visits not storing in the db

### ISSUE THREAD

**Issue by Jasonbit** [ankane/ahoy#103]
I'm using Postgres 9.4, ahoy 1.1.1, Rails 4.2.1, ruby 2.1.1p76

I've looked through all the issues and have seen some similar Visit problems. However, none of them seem to solve my issue.

First off, events work when I go through a web based controller. However, I have a subclassed api controller that events never work for. My app controller looks something like:

```ruby
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  before_action :require_login
  after_filter  :track_action

  protected

  def track_action
    ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
  end
```

My api controller looks like:

```ruby
class Api::ApiController < ApplicationController

  protect_from_forgery with: :null_session
    
  skip_before_filter  :verify_authenticity_token, :require_login
  before_filter       :provide_api_user
  after_filter        :track_action  
  
  private

  def provide_api_user

    ...

    # For tracking
    ahoy.authenticate(current_user)
    
  end
```

When I drill down thru the code and log out the current_user, it's all set correctly - in Ahoy, I can see that @user is set correctly. The visit_id in the events table is there for my non-api controller events, but no visit entry.

I have also added the logging to the initializer like so and no extra logging info:

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
  Ahoy.quiet = false
end
```

So, I'm not sure what the issue is - why part of it works in a non-api controller and none of it works in my api controller.

**Comment by ankane** [comment]
Visits are recorded through a Javascript callback by default.  If you want to track visits for an API endpoint, [check this out](https://github.com/ankane/ahoy#track-visits-immediately).

**Comment by Jasonbit** [comment]
Hey @ankane,

Right, makes sense - I've been going over all the docs and code. I did change my ahoy store to the following

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
  Ahoy.quiet = false
  Ahoy.track_visits_immediately = true
  Ahoy.geocode = :async
end
```

and still no change. I don't get an ahoy event at all when I hit any of my api endpoints.

And for some reason, the ahoy.js is not being added at all even though I specified the require in my application.js. Might have something to do with the latest Rails?

I'll keep digging and post anything else I find. Thanks again.

**Comment by Jasonbit** [comment]
Ok, I found out why visits wasn't working - I'm using a bootswatch theme and the asset pipeline is not including my application.js but the js for that theme (facepalm). So I'm now able to get a visit in the db.

For the api controller not tracking, it's because the user agent (curl in this case for my testing) was being flagged as a bot. I 'fixed' this by overriding the `exclude?` method in the store:

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
  Ahoy.quiet = false
  Ahoy.track_visits_immediately = true
  Ahoy.geocode = :async

  def exclude?
    user ? false : bot?
  end
  
end
```

This gets me through to logging events. However, for this case, I have no visit even though there is a visit_id present in the event. I get that a visit is tied to a cookie on the js side of things, so now I'm trying to figure out a simple way so create the visit for the api side.

If I can't do that (because the visit tracks user agent and those sorts of client side things) then it looks like I'll have to accept api requests only being events and not neatly wrapped up into a starting visit like the browser side does. The fact that my events all have user_id might be ok, but the event also has a dangling visit id that goes to nowhere.

Any thoughts from your point of view? Do you guys worry about this at Instacart or even consider this an issue?

I'm sure you're busy with other stuff so no worries if this is just how it works. Thanks.

**Comment by ankane** [comment]
The `track_visits_immediately` option should create a visit server-side without the need for js.
