### ISSUE TITLE
Ahoy :async not working

### ISSUE THREAD

**Issue by tggo** [ankane/ahoy#104]
When pushing new job for geocode need pass only id, not object.
Because redis stores only strings.
In GeocodeJob need do
visit = Visit.find(id_string)

Or I mistake?

Sample of wrong attributes pass

```
{"job_class"=>"Ahoy::GeocodeJob",
 "job_id"=>"ecc07c39-67fa-4e51-a386-4e43f019ecb0", 
 "queue_name"=>"ahoy", 
 "arguments"=>["#"]}
```

**Comment by selivandex** [comment]
i have the same issue, have you solved this? @tg0

**Comment by tg0** [comment]
look two last commits in my fork
https://github.com/tg0/ahoy/commits/master

**Comment by ankane** [comment]
Not sure I understand the issue @tggo. Can you explain more?

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if its still an issue and you want to explain more.
