### ISSUE TITLE
Logging duplicate events and thread safety

### ISSUE THREAD

**Issue by mchristen** [ankane/ahoy#105]
Using Rails 4.2 and Ahoy 1.1.1 I am noticing lines in the log output like

    PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "ahoy_events_pkey" 
    DETAIL:  Key (id)=(6f699dd1-d2e7-4972-aac5-3f182a593f5b) already exists. 
    INSERT INTO "ahoy_events" ("id", "visit_id", "user_id", "name", "properties", "time", "request_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id" 

It is my understanding that the nature of these errors is a by-product of the way Ahoy is designed with the asynchronous nature of the JS library. 

That said, there is code in the ActiveRecordStore designed to rescue this exception so I am at a loss as to why they are showing up in the logs anywhere in the first place.

What brought my attention to this line in the logs was an attempt to debug an apparent deadlock in the Rails.logging system in production. Essentially after some indeterminate amount of time the Logging system in Rails stops outputting content. In the case of my app, for every instance I have traced in our log files every time the logging system locks up it was in the middle of logging those lines above. 

I noticed in the Ahoy::Engine class there is mucking around with the Rails.logger.level depending on the status of Ahoy.quiet. I am not a ruby/rails thread safety expert, but I definitely think the way log levels are being changed is not a thread safe operation. 

For example, imagine the follow scenario

    Request A arrives, stores the current log level as info, sets Rails.logger.level to error and starts a short running request
    Request B arrives, stores the current log level as error(set from previous request), sets Rails.logger.level to error, and starts a long running request.
    Request A completes, the Rails.logger.level is set to info as that was the log level stored in the env hash at the start of Request A.
    Request B completes, the Rails.logger.level is set to error as that was the log level stored in the env hash at the start of Request B.

**Comment by ankane** [comment]
Hi Matt, thanks for reporting.  You're right - the log silencer is not thread-safe :(  You can disable this feature with:

```ruby
Ahoy.quiet = false # or Rails.env.development?
```

Obviously, this is bad for anyone running `puma` or another threaded server, so this will need to be changed before the next release.  Maybe only silencing in development is the best option.

As for the unique violation, I'm not sure why it wouldn't be rescued.

**Comment by ankane** [comment]
It looks like activerecord-sessionstore has a thread-safe way to do it.

https://github.com/rails/activerecord-session_store/blob/master/lib/active_record/session_store/extension/logger_silencer.rb

**Comment by mchristen** [comment]
Ah interesting, looks like they are adding some thread safety to the logger itself to provide the silencing interface. Makes sense.

**Comment by ankane** [comment]
Hopefully Rails will do this by default in the future https://github.com/rails/rails/pull/16885
