### ISSUE TITLE
Run before filter in Events and Visits controllers

### ISSUE THREAD

**Issue by bilby91** [ankane/ahoy#108]
Hello,

I'm trying to run a before_filter in both of this controllers but didn't have luck :( . I saw the skip_filter that removes all the filters.

Using class_eval on BaseController can do the work here ? Having trouble with a circular dependency issue.

Thanks, awesome project! Keep up the good work!

**Comment by ankane** [comment]
Hey @bilby91, reopening `BaseController` should do the trick.  What error are you seeing?
