### ISSUE TITLE
Custom store to Mixpanel / Intercom / Google Analytics

### ISSUE THREAD

**Issue by jnettome** [ankane/ahoy#110]
First of all, thank you @ankane for this excellent project. I'm constantly using your tools made for instacart here at [Encontre um Nerd](https://encontreumnerd.com.br).

Today, I'm using https://github.com/railslove/rack-tracker as an alternative for Segment.io, and I'm wondering If I can use just ahoy to do this job.

Have you or someone else experienced something like this?

**Comment by ankane** [comment]
Hey @jnettome, you'd have to create your own custom store for this. We recently started using Segment.io in addition to Ahoy at Instacart fwiw.

**Comment by oboxodo** [comment]
@ankane that's interesting. I'm currently using segment.io and I'm pretty happy with them. But I'm now needing to add some per user and per group of users stats dashboard with some graphs, etc, and I'm feeling like having all that data "locally" might be more appropriate. So I'm considering Ahoy, but I feel like I still need to have Segment around.

You mention you are using both ahoy and segment at Instacart. Did you wrap Segment reporting in a custom ahoy store for this? And in that case, can ahoy handle reporting to multiple stores with a single call to track a visit or event?

**Comment by ankane** [comment]
We use Segment client-side, so didn't touch the store.

**Comment by hadees** [comment]
@ankane do you have any code for segment and ahoy integration? I'm looking at doing this myself.
