### ISSUE TITLE
Multiple users on the same device

### ISSUE THREAD

**Issue by blackpond** [ankane/ahoy#112]
Hi - I've noticed that Ahoy does not record visits consistently when logging in as a different user on the same device.

I found the following line:

`DEBUG -- : [ahoy] Visit excluded`

Is there a way to prevent this behaviour?

Thanks!

**edit**

sorry - looks like the visit excluded is from new relic pining my machine, there doesn't seem to be any other ahoy logs.

`I, [2015-06-24T15:08:47.641246 #14149]  INFO -- : Started HEAD "/" for 54.248.250.232 at 2015-06-24 15:08:47 -0600
I, [2015-06-24T15:08:47.691168 #14149]  INFO -- : Processing by PagesController#index as */*
D, [2015-06-24T15:08:47.695346 #14149] DEBUG -- : [ahoy] Visit excluded

**Comment by ankane** [comment]
Thanks for the update.  Ahoy excludes bots by default, so this is expected.  See the readme if you want to change this.
