### ISSUE TITLE
Ahoy not tracking visits or events after install

### ISSUE THREAD

**Issue by rubyguy** [ankane/ahoy#114]
I installed Ahoy exactly as mentioned in the Readme on gihub for Rails 4, mysql. I restarted my server, logged out and logged back in, but visits and ahoy_actions table are empty. Nothing is being recorded. Documentation is not very clear on this. It does not mention if there is anything else needs to be done to start recording visits. Please help.

**Comment by ankane** [comment]
Hi @rubyguy, see if the [development instructions](https://github.com/ankane/ahoy#development) help in debugging.

**Comment by rubyguy** [comment]
@ankane, I tried everything. No luck!
It is loaded along with all its modules and classes:
[:Tracker, :VisitProperties, :Engine, :GeocodeJob, :Store, :BaseController]
I restarted my rails server. Nothing happens.
How does it track visits? Is there a setting that has to be turned on for it to start? I really need this thing to work or I will have to look for another gem.

**Comment by rubyguy** [comment]
I added the following to my application_controller.rb
```
  after_filter :ahoy_track

  protected

  def ahoy_track
    ahoy.track_visit
  end
```

and I am getting this error:

```

ActiveRecord::StatementInvalid in Devise::SessionsController#new
Mysql::Error: Data too long for column 'id' at row 1: INSERT INTO `visits` (`id`, `visitor_id`, `started_at`, `ip`, `user_agent`, `referrer`, `landing_page`, `referring_domain`, `browser`, `os`, `device_type`, `country`, `latitude`, `longitude`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```
and the server log shows:

```
SQL (1.6ms)  INSERT INTO `visits` (`id`, `visitor_id`, `started_at`, `ip`, `user_agent`, `referrer`, `landing_page`, `referring_domain`, `browser`, `os`, `device_type`, `country`, `latitude`, `longitude`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["id", "<36 bytes of binary data>"], ["visitor_id", "<36 bytes of binary data>"], ["started_at", "2015-07-16 18:54:44"], ["ip", "127.0.0.1"], ["user_agent", "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0"], ["referrer", "http://127.0.0.1:3000/"], ["landing_page", "http://127.0.0.1:3000/users/sign_in"], ["referring_domain", "127.0.0.1"], ["browser", "Firefox"], ["os", "Linux"], ["device_type", "Desktop"], ["country", "Reserved"], ["latitude", 0], ["longitude", 0]]
Mysql::Error: Data too long for column 'id' at row 1: INSERT INTO `visits` (`id`, `visitor_id`, `started_at`, `ip`, `user_agent`, `referrer`, `landing_page`, `referring_domain`, `browser`, `os`, `device_type`, `country`, `latitude`, `longitude`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 769ms
```
I checked the definition of the table and id and visitor_id columns are binary(16) but the data is longer than that... 

How to fix this?

**Comment by rubyguy** [comment]
After spending two full days and going through every piece of the code I figured the error is due to UUID being sent as a String instead of UUID. The problem code is in active_record_store.rb track_visit lines 7,8 and track_event lines 28,29. which are :
```
            v.id = ahoy.visit_id
            v.visitor_id = ahoy.visitor_id
```
So I overrode this code in config/initializers/ahoy.rb as below and error was corrected.

```
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
      def track_visit(options, &block)
        visit =
          visit_model.new do |v|
            v.id = UUIDTools::UUID.parse_raw(ahoy.visit_id)
            v.visitor_id = UUIDTools::UUID.parse_raw(ahoy.visitor_id)
            v.user = user if v.respond_to?(:user=)
            v.started_at = options[:started_at]
          end

        set_visit_properties(visit)

        yield(visit) if block_given?

        begin
          visit.save!
          geocode(visit)
        rescue *unique_exception_classes
          # do nothing
        end
      end

      def track_event(name, properties, options, &block)
        event =
          event_model.new do |e|
            **e.id = UUIDTools::UUID.parse_raw(options[:id])
            e.visit_id = UUIDTools::UUID.parse_raw(ahoy.visit_id)**
            e.user = user if e.respond_to?(:user=)
            e.name = name
            e.properties = properties
            e.time = options[:time]
          end

        yield(event) if block_given?

        begin
          event.save!
        rescue *unique_exception_classes
          # do nothing
        end
      end
end
Ahoy.track_visits_immediately = true
```

Another major issue I had to grapple with was poor documentation. This gem is nicely written but the documentation is hardly does justice to it. You may want to add more documentation to show clearly how to actually switch it on, and what major pitfalls a new user can face. This will definitely improve its popularity.

**Comment by SimonWalsh1000** [comment]
I agree about the documentation. Its incredible sparse especially for newbies. The gem is nice but the documentation is dreadful.

**Comment by ankane** [comment]
Feel free to make / suggest improvements where needed.

**Comment by abrambailey** [comment]
Thank you @rubyguy !  I was struggling with the same problem, but thankfully I found your fix after only 2 hours and not two days.

**Comment by jamesprior** [comment]
@rubyguy Can you walk me through a bit on why it is `parse_raw` instead of `parse` ?  Looking through UUIDTools it looks like `parse_raw` expects a string representing bits to be converted into a UUID.  

Do you know how any of those things are getting returned as raw bytes?

**Comment by monfresh** [comment]
@abrambailey @jamesprior If you use the latest version of Ahoy, it's recommended to use `ActiveRecordTokenStore`, not `ActiveRecordStore`. The former fixes the UUID issue.

**Comment by monfresh** [comment]
@ankane Is there a particular scenario where one would use `ActiveRecordStore` and not `ActiveRecordTokenStore`? If not, would it make sense to remove `ActiveRecordStore` since it has this UUID issue that still hasn't been fixed?

**Comment by jamesprior** [comment]
Hey thanks for the pointer - do you know if there is already anything written on how to migrate from one to the other?  Eg, what reports need updating, will sessions get lost, etc.  I see a very comprehensive readme on the project homepage but I don't see a wiki link.

**Comment by monfresh** [comment]
Not that I know of. I'm new to Ahoy, so I'm lucky to not be in a position to migrate between stores.

**Comment by ankane** [comment]
Both stores exist for backward compatibility. Ahoy before 1.0 used the token store, Ahoy 1.0 switched to UUIDs, and Ahoy 1.4 brought back the token store as the default. I haven't been able to reproduce the issues with UUIDs, so I suspect most users haven't had issues.

@jamesprior migrating will be difficult. I'm not sure there's a strong reason to migrate, but the general approach would be:

1. Create a new table
2. Update code to use new table
3. Backfill from old table

Visits during the transition could get a bit funky, but this is a fairly straight forward approach.

**Comment by blackpond** [comment]
After upgrading to Rails 5 I started getting this error as well:

`ActiveRecord::ValueTooLong (Mysql2::Error: Data too long for column 'id' at row 1: INSERT INTO `visits` (`id`, `visitor_id`, `ip`, `user_agent`, `landing_page`, `user_id`, `browser`, `os`, `device_type`, `screen_height`, `screen_width`, `started_at`) VALUES (x'65663538363231342d396464392d346330312d396133372d363033353037633633313166', x'62393866373932352d323836632d346165622d613365372d623761656635353337633665', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'http://localhost:3000/', 201, 'Chrome', 'Mac OS X', 'Desktop', 1050, 1680, '2017-03-07 08:32:28')):`
