### ISSUE TITLE
Ahoy is not tracking visits what to do?

### ISSUE THREAD

**Issue by shilpi230** [ankane/ahoy#115]
I am able to track events but its populating visit database :( 
but this ```ahoy.track_visit``` is telling me true only please reply asap :)

**Comment by rubyguy** [comment]
You need to explain your question clearly. I had lot of issues with this gem too. Remember, a unique visit is created only after 4 hours. You can put ahoy.track_visit in your application controller or any specific controller to track a visit. Same for the event. visits are recorded in visits table. Events are recorded in ahoy_events table.
