### ISSUE TITLE
Visit does not get updated if user signs in

### ISSUE THREAD

**Issue by chrise86** [ankane/ahoy#12]
According to the docs:

```
With Devise, it will attach the user even if he / she signs in
after the visit starts.
```

However this does not seem to be the case. I had to manually add in the custom option:

```
if current_visit and !current_visit.user
  current_visit.user = current_user
  current_visit.save!
end
```

Rails 4.1
Devise 3.2.4
Ruby 2.1.1
Ahoy 0.1.3

Also, if tracking conversion / sign in rates, what would be the best route? Use the new ahoy_events gem and attached to the current_visit?

**Comment by supercodepoet** [comment]
I am seeing this behavior right now. Visiting a page freshly will create a new visit and then signing in does not set the user_id on the visits table for the visit.

Rails 4.2
Devise 3.4.1
Ruby 2.1.5
Ahoy 1.1.1

**Comment by supercodepoet** [comment]
Ok, found the issue. Devise needs to be ahead of Ahoy in the Gemfile.

**Comment by pdoggi** [comment]
Just FYI, I experienced the same behavior, so I did a similar thing as **chrise86**.

Rails 4.0.2
Authlogic 3.3.0
Ruby 1.9.3
Ahoy_Matey 1.1.1

**Comment by ankane** [comment]
@pdoggi You'll have to do it manually with Authlogic.

**Comment by pdoggi** [comment]
Yup, that's what I did. Thanks, @ankane!
