### ISSUE TITLE
Querying Events by properties hash key/value pair

### ISSUE THREAD

**Issue by campgurus** [ankane/ahoy#120]
I have been looking but haven't found an answer to this seemingly simple question.  I am trying to search events to return number of article views for @article.  so I am guessing it should be something like:

Ahoy::Event.where("properties @> (:key => :value)", :key => 'article_id', :value => @article.id).count

I have also looked at the possibility of using hstore, but I am not sure if that is necessary.  Any guidance would be great.  Thanks.

**Comment by ankane** [comment]
jsonb, hstore, and json column types should all be queryable. If you're on Postgres 9.4, jsonb would be my choice; otherwise, hstore.

**Comment by campgurus** [comment]
Helpful. Thanks.  Just out of curiousity, why do you prefer jsonb?

**Comment by campgurus** [comment]
Same as #84.

**Comment by ankane** [comment]
Is `properties` a text column on ahoy_events?

**Comment by campgurus** [comment]
It was initially, but I changed it to jsonb. from schema.rb

create_table "ahoy_events", id: :uuid, default: nil, force: :cascade do |t|
    t.uuid     "visit_id"
    t.integer  "user_id"
    t.string   "name"
    t.jsonb    "properties"
    t.datetime "time"
  end

  add_index "ahoy_events", ["time"], name: "index_ahoy_events_on_time", using: :btree
  add_index "ahoy_events", ["user_id"], name: "index_ahoy_events_on_user_id", using: :btree
  add_index "ahoy_events", ["visit_id"], name: "index_ahoy_events_on_visit_id", using: :btree

**Comment by constantm** [comment]
I'm running into the same issue, and we're running Postgres 9.3. Changing column type to JSON results in `no implicit conversion of Hash into String` when trying to do anything with `Ahoy::Event`. Is there no other way to query events from properties without using Postgres 9.4/jsonb?

**Comment by mbajur** [comment]
+1

**Comment by hothero** [comment]
+1, Anyone have any solution for this??

I got the same error after upgrading properties filed from json to jsonb type. I ensure my postgresql version is 9.4.4.

**Comment by Fudoshiki** [comment]
+1

**Comment by abrambailey** [comment]
+1

**Comment by hothero** [comment]
This problem could be solved by [issue#86](https://github.com/ankane/ahoy/issues/86) or you can follow my article: http://blog.hothero.org/posts/2016/04/10/707302

**Comment by genlighten** [comment]
I'm trying to query events by profile_id (from my properties hash). I'm using MySQL rather than PostgresQL. My Ahoy::Events look like this:

#<Ahoy::Event id: 4, visit_id: 2, user_id: 2, name: "Viewed profile", properties: {"profile_id"=>2, "referral_url"=>"/genealogists/chicago-il"}, time: "2016-06-16 03:41:49"> 

When I try to query for events that have profile_id 2, using this syntax:

Ahoy::Event.where("properties LIKE '%\"profile_id\"=>2%'").count

in the console, the returned value is zero, even though there are four entries in my development database with profile_id=>2.

I'm guessing I'm just using the wrong syntax for the MySQL query. Any suggestions on what I need to change?

Thanks!

**Comment by ankane** [comment]
Hi Dean, see the [Querying Properties](https://github.com/ankane/ahoy#querying-properties) section.  For those who are getting the `no implicit conversion of Hash into String` error, see #86 for the solution.

**Comment by genlighten** [comment]
Hi again, sorry to be a bother. I *did* follow the "text" syntax in the Querying Properties section, and it didn't work for my app that uses MySQL as the DB, as I explained in my post. It returned zero results, despite there being several in the database.

I tried setting the "name" field for my events to "Viewed profile #{profile_id}", then setting up an AR query like this:

first_event = Ahoy::Event.where(:name => "Viewed profile #{profile_id}").last and that worked fine, but I'd really rather query the profile_id from within the properties hash as you've designed it.

I'm guessing that it's a simple MySQL syntax error, but I've checked my use of %, escaping the quote marks, etc. and they seem right.

Thanks!

--Dean

**Comment by ankane** [comment]
It looks like you're using Ruby syntax (i.e. `=>`) instead of JSON syntax. Try the following to see what works.

```ruby
Ahoy::Event.where("properties LIKE '%\"profile_id\": \"2\"%'").count
Ahoy::Event.where("properties LIKE '%\"profile_id\": 2%'").count
Ahoy::Event.where("properties LIKE '%\"profile_id\":\"2\"%'").count
Ahoy::Event.where("properties LIKE '%\"profile_id\":2%'").count
```

**Comment by genlighten** [comment]
The last one worked perfectly. Thanks!

--Dean

**Comment by ankane** [comment]
Great 👍
