### ISSUE TITLE
Separate datastore

### ISSUE THREAD

**Issue by arrowcircle** [ankane/ahoy#123]
Hi!
Is it possible to use ahoy with separate datastore?
Like my rails app uses one DB, and ahoy uses another DB for tracking.
If you have a lot of events it will be cool to have separate storage.

**Comment by saturnflyer** [comment]
@arrowcircle you should be able to change your Visit model and Ahoy::Event model to whatever datastore you like

**Comment by ismailmechbal** [comment]
Guys i'm quite new to Rails and intend to use Ahoy, same as @arrowcircle i'd like to use a separate datastore, mysql, anyone can point me to the right direction.

**Comment by rbgraham** [comment]
@ismailmechbal @arrowcircle fwiw I used http://www.ostinelli.net/setting-multiple-databases-rails-definitive-guide/ as a starting point.

**Comment by jabbett** [comment]
Thanks @rbgraham - that was super helpful!

The ahoy-specific details I'd share are:

* after following that guide, when you run `rails generate ahoy:stores:active_record`, move the newly generated files in `db/migrate` to `db_stats/migrate` 
* update the Ahoy models to extend an AhoyBase model that sets the custom database connection, [as shown in this gist](https://gist.github.com/jabbett/07522fd44859e614de32f3863a1b6b8d)

**Comment by ismailmechbal** [comment]
Thanks @rbgraham works great!
