### ISSUE TITLE
current_visit doesn't work on Heroku

### ISSUE THREAD

**Issue by guydu** [ankane/ahoy#124]
I'm using Ahoy gem to track visits.

The installation went well and it seems to work fine on my local machine but when running on Heroku the current_visit is null

I log in the following way:

logger.info "Hello World"
logger.info current_visit.to_json
on my machine I get:

Hello World
{"id":"4ab59270-adac-4780-98df-348543cb1ac8","visitor_id":"2de0a1b0-feb4-49b3-bf96-ced98be9f690","ip":"::1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36","referrer":null,"landing_page":"http://localhost:3000/","user_id":9,"referring_domain":null,"search_keyword":null,"browser":"Chrome","os":"Mac OS X","device_type":"Desktop","screen_height":1024,"screen_width":1280,"country":"Reserved","region":null,"city":null,"postal_code":null,"latitude":"0.0","longitude":"0.0","utm_source":null,"utm_medium":null,"utm_term":null,"utm_content":null,"utm_campaign":null,"started_at":"2015-09-02T11:16:14.340Z"}
while running on Heroku I get:

2015-09-02T12:56:05.708156+00:00 app[web.1]: Hello World
2015-09-02T12:56:05.723945+00:00 app[web.1]: null
and yes, it was bundles and the db was migrated. any ideas what went wrong?

I'm running on Rails 4.2

Thanks!

http://stackoverflow.com/questions/32354083/ahoy-gem-doesnt-work-on-heroku?noredirect=1#comment52594318_32354083

**Comment by andreasarnold02** [comment]
Have you tried production mode on your local?

**Comment by Streek** [comment]
Same, does not function on heroku or locally using a heroku database remotely.

**Comment by ACPK** [comment]
Is this still an issue?

**Comment by ankane** [comment]
Ahoy should have no problems running on Heroku.  Here are [a few things to try](https://github.com/ankane/ahoy#development) if you're having issues.
