### ISSUE TITLE
Mount before other routes

### ISSUE THREAD

**Issue by richardvenneman** [ankane/ahoy#126]
Thanks for the great library.

I'm using ahoy in an app which has "GitHub-style" nested URLs.

```ruby
resources :countries, path: '', only: [:show] do
  resources :cities, path: '', only: [:index]
  resources :cities, path: '', only: [:show] do
    ...
  end
end
```

Ahoy gets automatically mounted after these routes, so in some cases the CitiesController tries to process `/ahoy/visits` requests. Is there any way I can mount Ahoy before above routes?

I tried several approaches as described in #29 but to no avail (I also do not wish to mount Ahoy twice). It seems pull request #31 would exactly fit my needs. Would you accept a pull request for that functionality, or are there any other solutions?

Thanks.

**Comment by ankane** [comment]
What's the reasoning behind not wanting to mount it twice?

**Comment by richardvenneman** [comment]
Did not feel clean, but if you're suggesting that there's nothing wrong with that, then I guess there is none!
