### ISSUE TITLE
Uninitialized constant Ahoy::Stores (NameError)

### ISSUE THREAD

**Issue by jeremyjeremies** [ankane/ahoy#128]
I've set up Ahoy and everything is working properly in my rails app on my development machine. Visits are being recorded and events are working as well.

However, when I deploy the app to production using capistrano, the app is delivering a 500 error because unicorn cannot restart. The following error is from my Unicorn logs:

    E, [2015-10-07T15:16:52.778745 #6599] ERROR -- : reaped #<Process::Status: pid 18874 exit 1> worker=0
    I, [2015-10-07T15:16:52.778745 #6599]  INFO -- : worker=0 spawning...
    I, [2015-10-07T15:16:52.782735 #18967]  INFO -- : worker=0 spawned pid=18967
    I, [2015-10-07T15:16:52.783063 #18967]  INFO -- : Refreshing Gem list
    I, [2015-10-07T15:16:54.252618 #6599]  INFO -- : reloading config_file=/opt/www/myapp/current/config/unicorn.rb
    I, [2015-10-07T15:16:54.269868 #6599]  INFO -- : done reloading config_file=/opt/www/myapp/current/config/unicorn.rb
    E, [2015-10-07T15:16:54.418586 #18967] ERROR -- : uninitialized constant Ahoy::Stores (NameError)
    /opt/www/myapp/releases/20151007200140/config/initializers/ahoy.rb:1:in `<top (required)>'

The app production log doesn't say much, it just hangs on this line (not sure if it has anything to do with the error):

    DEBUG [00630f76] 	D, [2015-10-07T11:24:12.705626 #7083] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"

When I comment out the entire initializers/ahoy.rb file and re-deploy, unicorn reloads properly and the app works fine but obviously none of the events or visits are being recorded. Any thoughts?

    ruby 2.2.2
    rails 4.2.0
    gem 'ahoy_matey'

**Comment by jeremyjeremies** [comment]
Turns out this was a unicorn issue and not specific to ahoy - for anyone else that experiences this:

http://stackoverflow.com/a/20908747

**Comment by ankane** [comment]
Thanks for following up!

**Comment by gitgdeng** [comment]
Hi I got the same error even after restart server as mentioned by @jeremyjeremies 
cc @ankane 
btw, I am using ruby v1.9.3 and ahoy gem v1.2.1

**Comment by Dhrumilp17** [comment]
@jeremyjeremies  Can I know how I can resolve the same issue if I deployed my rail app using PUMA webserver?
@imgdeng  Did you resolved the issue? Can you share your solution?

**Comment by smapira** [comment]
@dpanch378 The same thing happens to me in ahoy_matey (4.0.1).
I have re-tried to executed `bundle exec rails generate ahoy:install`, then resolved it.

**Comment by MRoc** [comment]
Happend to me when I installed `ahoy_matey` in `group :development`. Fixed by moving to normal dependencies.
