### ISSUE TITLE
Can I use this to track url params?

### ISSUE THREAD

**Issue by simkessy** [ankane/ahoy#131]
I'm trying to find a solution to track how users are using my search. I have 1 model called `Availabilities` and my search is just scopes and to filter through the records, so it's nothing fancy like searchkick or elasticsearch. 

The search params are start_date, end_date, activitiy (associated model), location (assoctiation), and time_range (morning, afternoon, night). 

I'm trying to track these params and figure out what my users search for most often and need to figure out if ahoy can accomplish this?

**Comment by ankane** [comment]
Yes, you can use Ahoy for this, but I recommend creating a separate model specifically for searches.
