### ISSUE TITLE
Crawler not detected

### ISSUE THREAD

**Issue by chr1s1** [ankane/ahoy#134]
Hi, 

I could not find the logic in the code otherwise I would have fixed it myself. We found a crawler in the visits table which was tracked like a regular user: 

```
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36 HubSpot Webcrawler
```

Is there a way to make sure that also this crawler is not stored as a regular visitors?

**Comment by mchristen** [comment]
Ahoy uses the [browser](https://github.com/fnando/browser) gem to do browser/bot detection. I would start there in terms of figuring out why it didn't classify that UA as a bot.

The call into browser from Ahoy occurs here

https://github.com/ankane/ahoy/blob/master/lib/ahoy/deckhands/technology_deckhand.rb#L19

**Comment by chr1s1** [comment]
Thanks a lot!
