### ISSUE TITLE
Event Counts for specific Record

### ISSUE THREAD

**Issue by kashifnaseer** [ankane/ahoy#138]
I'm planning to move from Impression gem to Ahoy. I've 2 questions, can you help me to understand, how i can get the following working in Ahoy.

1) We are using session_hash of Impression gem which tracks one event per User Session for one record. if user visits multiple times same page, it tracks only 1 event for that session. How i can get something similar in Ahoy.

2) I want to store the Object details like its ID and Class Name sothat i can later track how many events are attached to one specific Record. How i can do this ? like how many times company 'XYZ' is viewed.

I'm thinking to add following 2 fields in the 'ahoy_events' but how i can populate these fields

       eventable_type [ Company, User, Building etc]
        eventable_id [1d of the type]

**Comment by JeffreyCheng92** [comment]
You can just do `ahoy.track("Visit user page",  {id: 123, class_name: "Dog"})` in the controller that loads the page.

**Comment by campgurus** [comment]
@JeffreyCheng92 how do I query the Event.properties hash that the ahoy generates, e.g. to return all events that are e.g. views of a particular user? https://stackoverflow.com/questions/35753631/querying-ahoy-gem-events

**Comment by ankane** [comment]
@kashifnaseer 

1. You can do something like:

```ruby
unless session[:session_event_recorded]
  ahoy.track(name, properties)
  session[:session_event_recorded] = true
end
```

2. You can update the `ahoy_events` table and `track_event` method to record whatever values you'd like.

@campgurus See the [Querying Properties](https://github.com/ankane/ahoy#querying-properties) docs

**Comment by RathanakSreang** [comment]
@ankane 
what if I want to record event on first visit page, or after `30 minute`?
And I want to do that on many action.
How can I achieve that?

**Comment by silva96** [comment]
> @ankane what if I want to record event on first visit page, or after `30 minute`? And I want to do that on many action. How can I achieve that?

```ruby
# frozen_string_literal: true

class TrackVisitService
  SESSION_DURATION = 30.minutes # same as ahoy.rb initializer

  # This service dynamically tracks visits as Ahoy events
  # Example: ahoy.track('Product View', product_id: 1) or ahoy.track('User View', user_id: 1)
  def self.call(ahoy:, trackable:, event: 'View', one_per_session: true)
    new(ahoy:, trackable:, event:, one_per_session:).perform
  end

  def initialize(ahoy:, trackable:, event:, one_per_session:)
    @ahoy = ahoy
    @trackable = trackable
    @event = event
    @one_per_session = one_per_session
  end

  def perform
    return if one_per_session && already_tracked?

    ahoy.track(event_name, event_data)
    register_event_in_session if one_per_session
  end

  private

  attr_reader :ahoy, :trackable, :event, :one_per_session

  def register_event_in_session
    Cache.redis.set(event_id, '1', ex: SESSION_DURATION)
  end

  def event_id
    [ahoy.visit_token, event, trackable.class, trackable.id].join('-')
  end

  def event_name
    "#{trackable.class} #{event}"
  end

  def event_data
    { "#{trackable.class.to_s.downcase}_id" => trackable.id }
  end

  def already_tracked?
    Cache.redis.get(event_id).present?
  end
end
```

And in your controller you call it like this:

```ruby
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    TrackVisitService.call(ahoy:, trackable: @product)
  end
  ```
