### ISSUE TITLE
Logger silencer causes 502 errors (no block given (yield))

### ISSUE THREAD

**Issue by thomassnielsen** [ankane/ahoy#142]
Relevant stack trace:

```
App 783 stderr: [ 2016-02-03 16:46:57.5937 813/0x007ff4bae50158(Worker 1) utils.rb:86 ]: *** Exception LocalJumpError in Rack application object (no block given (yield)) (process 813, thread 0x007ff4bae50158(Worker 1)):
App 783 stderr:     from /usr/local/bundle/gems/ahoy_matey-1.2.1/lib/ahoy/logger_silencer.rb:44:in `silence_logger'
App 783 stderr:     from /usr/local/bundle/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:72:in `method_missing'
App 783 stderr:     from /usr/local/bundle/gems/ahoy_matey-1.2.1/lib/ahoy/engine.rb:14:in `call_with_quiet_ahoy'
```

This surprised us in a production deployment. Current workaround is to set `Ahoy.quiet = false`, as that skips the logger silencer entirely. I haven't been able to pinpoint _why_ the method gets no block.

We're on `ahoy_matey (1.2.1)`

**Comment by ankane** [comment]
Interesting, haven't seen that before.

Since Rails 4.1+ will have a thread-safe logger soon, I'd like to remove the log silencer from Ahoy in a future release. https://github.com/rails/rails/issues/20490

**Comment by thomassnielsen** [comment]
Right, missing info: We're at Rails 3.2.21.

**Comment by ankane** [comment]
Hey @thomassnielsen, try the latest version - 1.4.0.

**Comment by jfeust** [comment]
@ankane We're also getting this on heroku. Rails 3.2.22 with the latest ahoy 1.4.0  Any thoughts?

**Comment by ened** [comment]
How could one remove this middleware while keeping Ahoy itself around?

**Comment by ankane** [comment]
You can set `Ahoy.quiet = false`. https://github.com/ankane/ahoy/blob/07fb3866e38885e4a34092db22b88d5719cc9833/lib/ahoy/engine.rb#L9
