### ISSUE TITLE
How to explicitly set routes and using a different user model

### ISSUE THREAD

**Issue by DaKaZ** [ankane/ahoy#145]
Hello,

Thank you for your efforts on this amazing gem - I am excited to start using it but I have a few problems I need to resolve first.

For starters, we have custom error controller to make sure we catch and process errors correctly and return well formatted messages to the user - this is primarily dealing with JSON parameter parse errors on our API but we use it for all errors.  Why this matters: when we have this route in our `routes.rb` file, the Ahoy routes are never loaded.  For the life of me, I can't find where the routes are declared in the ahoy engine, I need to declare them explicitly before we have this which is the last line of our routes.rb:

`match "*path", to: "errors#catch_404", via: :all`

Secondly, we have a models called "User" and "Contact" - we don't want to track on the User model because those are already converted Contacts.  In our case, Contact is also polymorphic and Contact belongs to User, so we get that association for free.  Contact is where we want to associate and track visits.  So, I added the polymorphic changes to the migration and the proper `has_many :visits, as: :user` to the Contact model.  I then added `ahoy.authenticate(@contact)` to the controllers where we learn the contact's information (like newsletter sign up).  I don't get an error, but I don't see associated visits being stored with the contact.   I do have `Ahoy.track_visits_immediately = true` set in the ahoy initializer as well.  I'd love any tips for trouble shooting and/or setting it up appropriately.

Thanks

**Comment by DaKaZ** [comment]
Okay, I solved the first issue my explicitly mounting the engine with a name other than "ahoy" like this:
`mount Ahoy::Engine => "/ahoy", as: :my_ahoy`

I still need to figure out how to track visits to the Contact model....

**Comment by zyzioziom** [comment]
Hi @DaKaZ , did you manage to track visits on different model? 
I renamed database fields, but Ahoy still looks for User model:
`ActiveRecord::AssociationTypeMismatch (User(#70276061228040) expected, got Lead(#70276033025640)):`

**Comment by DaKaZ** [comment]
Nope - I gave up... sorry

**Comment by ankane** [comment]
@zyzioziom you'll need to update the `belongs_to` association on the `Visit` model.

```ruby
class Visit < ActiveRecord::Base
  belongs_to :user, class_name: "Lead"
end
```

**Comment by ankane** [comment]
Cleaning up issues

**Comment by dignoe** [comment]
> Okay, I solved the first issue my explicitly mounting the engine with a name other than "ahoy" like this:
> `mount Ahoy::Engine => "/ahoy", as: :my_ahoy`
> 
> I still need to figure out how to track visits to the Contact model....

FYI - The new module name is `AhoyEmail`, so I ended up adding this to my routes to make it work:

    mount AhoyEmail::Engine => '/ahoy', as: :my_ahoy
