### ISSUE TITLE
Gem `browser` updated to ver 2.0.0. 

### ISSUE THREAD

**Issue by kntmrkm** [ankane/ahoy#146]
https://github.com/fnando/browser/issues/210

with browser gem ver 2.0.0.

An error occurs.

`undefined method downcase`

should use version 1.1.0. until solve it.

**Comment by abevoelker** [comment]
I just got the same error (seems the browser gem just cut 2.0.0 in the last few hours). As @kntmrkm said this is a quick fix until the gemspec version constraint is tightened or syntax fixed:

```ruby
gem "browser", "~> 1.1"
```

**Comment by ankane** [comment]
Thank you both.  This is addressed in the latest release.
