### ISSUE TITLE
Exception reported: Error while trying to deserialize arguments

### ISSUE THREAD

**Issue by existent-ltd** [ankane/ahoy#148]
We are seeing a large number of exceptions of the following form.

``` sh
Ahoy: Error while trying to deserialize arguments: Couldn't find Visit with 'id'=0
```

It appears that this may be originating in the `Ahoy::GeocodeJob` class; indeed, we have the following in our Ahoy initializer:

``` ruby
Ahoy.geocode = :async
```

We are using the `ActiveRecordStore` for our visit data. I'm wondering whether the following lines in `ActiveRecordStore` might be the culprit:

``` ruby
begin
  visit.save!
  geocode(visit)
rescue *unique_exception_classes
  # do nothing                                                          
end
```

Would it instead be safer to call `geocode(visit)` as an `after_commit` callback?

**Comment by ankane** [comment]
Was going to ask if this is still an issue, but user was deleted.
