### ISSUE TITLE
Possible security/spam issues on "ahoy/events"

### ISSUE THREAD

**Issue by dmnelson** [ankane/ahoy#150]
Hi all,

We've been using this gem on one of our projects for a while and it has been extremely helpful. Our application is often target for all kinds of attacks and that makes us scam and wonder of all possible breaches we might have.

I was reviewing the Ahoys tracking method and I noticed that the "properties" attribute on the EventsController simply dumps whatever comes from the request body into the database. That can allow people to overflow the database with useless data.

And example with generated JSON data: 
```bash
curl -A "Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3" -X POST -H "Content-Type: application/json" --data '[{"name":"$view","properties":{"url":"http://localhost:3000/products?keywords=*","title":"Search for blablablala","spam":[{"_id":"56d5e63b7d1468581e2880c4","index":0,"guid":"263d1b8a-5b9f-4451-bb96-10e4742b5e45","isActive":false,"balance":"$2,282.55","picture":"http://placehold.it/32x32","age":38,"eyeColor":"green","name":"Sheree Acevedo","gender":"female","company":"VURBO","email":"shereeacevedo@vurbo.com","phone":"+1 (820) 552-2427","address":"564 Fiske Place, Bend, Oregon, 1896","about":"Nisi reprehenderit veniam minim enim amet officia commodo ea qui ut. Velit exercitation fugiat velit amet excepteur est amet ipsum velit esse cupidatat minim. Proident non id aliquip labore mollit velit. Dolor proident ad aliqua non officia cillum anim et sint nisi ex non.\r\n","registered":"2015-05-19T01:34:35 +03:00","latitude":-62.603757,"longitude":145.162191,"tags":["duis","culpa","irure","magna","consequat","elit","officia"],"friends":[{"id":0,"name":"Avis Sandoval"},{"id":1,"name":"Milagros Powell"},{"id":2,"name":"Lourdes Mcleod"}],"greeting":"Hello, Sheree Acevedo! You have 4 unread messages.","favoriteFruit":"banana"},{"_id":"56d5e63b97f0881d372025ff","index":1,"guid":"cb5bfe14-9116-40fd-bfa5-8d222139a4dc","isActive":true,"balance":"$1,900.07","picture":"http://placehold.it/32x32","age":34,"eyeColor":"blue","name":"Marian Shaw","gender":"female","company":"ROCKABYE","email":"marianshaw@rockabye.com","phone":"+1 (877) 545-3836","address":"322 Engert Avenue, Chamberino, Massachusetts, 9927","about":"Labore non fugiat laboris ad dolore excepteur eiusmod incididunt. Sit ex commodo esse consectetur et consectetur eiusmod. Nostrud veniam minim ad aute ut proident exercitation cillum nulla in ut voluptate. Consectetur ad esse sint voluptate culpa laboris labore culpa. Commodo amet est dolor adipisicing irure veniam irure amet nisi. Excepteur laboris ad sit incididunt amet nisi anim est dolore.\r\n","registered":"2015-06-11T08:30:00 +03:00","latitude":85.867006,"longitude":161.773622,"tags":["ipsum","aliqua","consectetur","laborum","ad","irure","anim"],"friends":[{"id":0,"name":"Dale Olsen"},{"id":1,"name":"Laura Franks"},{"id":2,"name":"Webster Puckett"}],"greeting":"Hello, Marian Shaw! You have 1 unread messages.","favoriteFruit":"banana"},{"_id":"56d5e63bf8304394586ce309","index":2,"guid":"13807a3b-b243-492c-ba09-6dd2ad3ad05f","isActive":false,"balance":"$3,854.49","picture":"http://placehold.it/32x32","age":28,"eyeColor":"brown","name":"Schwartz Rojas","gender":"male","company":"PATHWAYS","email":"schwartzrojas@pathways.com","phone":"+1 (880) 596-3175","address":"602 Seba Avenue, Fredericktown, South Carolina, 4737","about":"Nulla amet cillum id cupidatat cupidatat consectetur aliqua consectetur amet occaecat. Ullamco consectetur esse adipisicing sunt non eu proident amet amet consectetur non sit officia. Voluptate nisi non dolor dolore elit ad.\r\n","registered":"2015-03-03T01:48:13 +03:00","latitude":42.867241,"longitude":9.293174,"tags":["adipisicing","culpa","ullamco","dolore","ea","qui","eu"],"friends":[{"id":0,"name":"Mcbride Parks"},{"id":1,"name":"Mayra Bean"},{"id":2,"name":"Lindsay Velez"}],"greeting":"Hello, Schwartz Rojas! You have 2 unread messages.","favoriteFruit":"banana"},{"_id":"56d5e63b42c3a26877450430","index":3,"guid":"44a82021-37ac-4bdf-a320-8852ea117707","isActive":true,"balance":"$3,267.31","picture":"http://placehold.it/32x32","age":27,"eyeColor":"brown","name":"Cabrera Bradshaw","gender":"male","company":"UBERLUX","email":"cabrerabradshaw@uberlux.com","phone":"+1 (970) 489-2341","address":"176 Woodside Avenue, Klondike, Virginia, 9119","about":"Reprehenderit eu consectetur in do duis voluptate do. Anim elit Lorem deserunt fugiat nulla amet qui id qui aute. Et pariatur pariatur eu irure eiusmod anim consectetur esse. Incididunt id consequat mollit laborum reprehenderit sint exercitation magna sit exercitation. Deserunt non cillum mollit est. Amet occaecat mollit elit duis ea amet ullamco id.\r\n","registered":"2015-10-20T12:05:16 +02:00","latitude":-0.228536,"longitude":111.207243,"tags":["nulla","sit","eiusmod","culpa","occaecat","ut","aute"],"friends":[{"id":0,"name":"Salazar King"},{"id":1,"name":"Mcmahon Noble"},{"id":2,"name":"Krista Barnes"}],"greeting":"Hello, Cabrera Bradshaw! You have 9 unread messages.","favoriteFruit":"apple"},{"_id":"56d5e63b798805caff2b3933","index":4,"guid":"930f2e3c-70af-47fc-9373-35001f2af461","isActive":false,"balance":"$1,439.92","picture":"http://placehold.it/32x32","age":28,"eyeColor":"green","name":"Julianne Gray","gender":"female","company":"COMVOY","email":"juliannegray@comvoy.com","phone":"+1 (884) 426-3299","address":"803 Borinquen Pl, Faywood, Northern Mariana Islands, 8120","about":"Cillum non ullamco aliqua sit elit fugiat esse duis ex labore deserunt adipisicing. Duis cupidatat esse adipisicing amet tempor ad. Dolor et excepteur velit nostrud adipisicing.\r\n","registered":"2014-12-27T10:27:36 +02:00","latitude":24.919436,"longitude":-8.063959,"tags":["officia","magna","officia","nulla","laboris","ut","elit"],"friends":[{"id":0,"name":"Fisher Santiago"},{"id":1,"name":"Imogene Crawford"},{"id":2,"name":"Yesenia Bray"}],"greeting":"Hello, Julianne Gray! You have 7 unread messages.","favoriteFruit":"strawberry"}],"page":"/products"}}]' http://localhost:3000/ahoy/events
```

Another thing is that this makes this controller a good candidate to DDoS and other types of attacks since it doesn't validate any sort of token to make sure the request is originated from the site (Maybe it could use the CSRF token?)

**Comment by drhenner** [comment]
In the future contact the developers of a project directly about security issues. 1st the world shouldn't find out until there is a fix. 2nd if it isn't a real issue they get negative press for a non-issue. 

That said all contributions are great. I don't maintain this project but I appreciate the awesome work and even the users contribute.

**Comment by caleuanhopkins** [comment]
I think the security level should be placed before firing the ahoy tracking code, therefore your security should exists in the app, not the gem. If you are allow direct access from a HTTP request to manipulate the database without doing any form of "pre-scanning" then unfortunately you are opening yourself up to exposures such as the type you've described. Not blaming or pointing fingers, if the issue you described is as critical as you've outlined then my suggestion would be to do your own validation before allow the app to execute the ahoy commands.

**Comment by dmnelson** [comment]
Hi @caleuanhopkins! I'm not sure if I follow what you tried to say here. Maybe I'm missing something, but the issue I'm describing here is introduced by the controller bundled in the gem (https://github.com/ankane/ahoy/blob/master/app/controllers/ahoy/events_controller.rb#L27), that would create the endpoint that would allow someone to spam the database without any app code in between. 

For example, if you create a vanilla Rails app and install the gem* - then you have that issue in your app, even if you use your own code to fire the tracking code, as long you don't disable the default controller, the issue is present.

Of course this can be solved on the app side or even on the infrastructure side, and it's not that hard.

What I think though, is that it would be better if them gem didn't introduce this - or that at least would point it out on the README. I'm thinking on the number of people that have the gem installed and don't know that this is potentially going on their apps.

[*] I've just done that test, created a new Rails app, installed the gem, started the server and executed the cURL command on the original post and all of that got into the DB.

**Comment by ankane** [comment]
Thanks for raising this concern David.  As @drhenner pointed out, please email me directly about potential security issues in the future.  My email address is on my Github profile.  **This cannot be overstated.**

This type of attack is possible with any user submitted value you decide to store without a length constraint, but I agree Ahoy makes this somewhat easier to do.  To help mitigate this, I’ve add throttling, a limit on content length of requests, and a limit on the max number of events per request.  It may also makes sense to notify users about this in the readme.

Please email me directly if you have any feedback, concerns, or more ideas.  Thanks.
