### ISSUE TITLE
Document wrong with geocoding Active Job 

### ISSUE THREAD

**Issue by TangMonk** [ankane/ahoy#151]
This line `Add Active Job and set:` should be deleted, because of gem `activejob_backport` actually not used in master source code

![image](https://cloud.githubusercontent.com/assets/3498786/13516369/7e0cd6cc-e1f4-11e5-9e8d-e4970cc21c35.png)

And configure the worker queue to `ahoy`

**Comment by TangMonk** [comment]
sorry for my miss understand of active_job, close

**Comment by ankane** [comment]
ActiveJob backport is needed for Rails 4.0 and 4.1.  I'll update the readme to make this clearer.
