### ISSUE TITLE
Dependency ( Browser ) Incompatibility in recent versions

### ISSUE THREAD

**Issue by notsoluckycharm** [ankane/ahoy#154]
Hello, 

In the gemspec, we have the following dependency:  spec.add_dependency "browser", ">= 0.4.0"

However, the recent versions of Browser ( > 2.0 ) have changed a core integration point that Ahoy uses to do .bot? detection. I contacted Browser first at the following fnando/browser#217 to figure out what the necessary change may be.

To others who come across this issue, adding "browser", "1.1.0" to your gemfile should resolve the issue until a PR is merged here.

I won't reproduce the bug report, as it is available in the referenced issue.

**Comment by ckahle33** [comment]
+1 - @notsoluckycharm Thanks for the fix!

**Comment by ankane** [comment]
Thanks for reporting. Fixed in the latest release.
