### ISSUE TITLE
1.2.2 does not work in combination with quiet_assets gem

### ISSUE THREAD

**Issue by gurix** [ankane/ahoy#157]
After updating from v1.2.1 to v1.2.2 I got the following error
```
Failure/Error: ::Kernel::raise
      
      SystemStackError:
        stack level too deep
      # /Users/markus/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/forwardable.rb:174
      # 
      #   Showing full backtrace because every line was filtered out.
      #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
      #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

``` 
I could not conclude the exact reason but I figured out that it seems somehow not to be compatible with the gem quit_assets. 

At the moment my solution to just remove quiet_assets gem seems fine for me, but I guess somebody else will be run in it. 

There is a comment on https://github.com/ankane/ahoy/blob/master/lib/ahoy.rb#L106 that looks like a similar effect concerning activerecord. I guess I run into it because I don't use activerecord but just mongoid as orm.

**Comment by harigopal** [comment]
+1

I'm seeing an infinite loop, after upgrading from ahoy_matey v1.2.1:

```
.rvm/gems/ruby-2.3.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
.rvm/gems/ruby-2.3.0/gems/ahoy_matey-1.3.0/lib/ahoy/log_silencer.rb:12:in `call'
```

Couldn't figure it out, though - ended up removing quiet_assets.

**Comment by ankane** [comment]
See if 1.3.1 fixes it.
