### ISSUE TITLE
localhost "can't receive data"

### ISSUE THREAD

**Issue by jgrosso-dynamynd** [ankane/ahoy#160]
When I upgrade from 1.2.1 to 1.3.0, I start getting "**localhost** can't receive data" in Chrome (and there's nothing in the server logs).

**Comment by rodolfoasantos** [comment]
I have the same issue!

**Comment by jgrosso-dynamynd** [comment]
For me,
    gem 'ahoy', '1.2.1'
    gem 'browser', '1.1.0'
fixed it.

**Comment by rodolfoasantos** [comment]
@jgrosso-dynamynd I need the version 1.3.0 whose has some security updates using throttling. My case I was facing issues during the log handler process when the patch ``Ahoy:: log_silencer`` is calling ``super``

**Comment by ankane** [comment]
Just pushed a new version - 1.3.1. See if that fixes it.

**Comment by ankane** [comment]
My bad, confused this with something else. Try master.

**Comment by rodolfoasantos** [comment]
It works now! Thank's @ankane 
Waiting for the new version bump to remove the local fixes.

**Comment by ankane** [comment]
Great!
