### ISSUE TITLE
Ahoy installation with Rails 3.2.22.2 failing

### ISSUE THREAD

**Issue by kavita-chitnis** [ankane/ahoy#163]
Hi,
I have installed the Gem Ahoy as per the instruction in the link -> https://github.com/ankane/ahoy

rake db:migrate
The last command produces following error

rake db:migrate
==  CreateVisits: migrating ===================================================
-- create_table(:visits, {:id=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  type "binary" does not exist
LINE 1: CREATE TABLE "visits" ("id" binary(16) PRIMARY KEY, "visitor...

I tried both PostgreSQL (with uuid gem) and MySQL installations and both gave me the same error.

**Comment by ankane** [comment]
Try deleting the migrations, upgrading to Ahoy 1.4.0, and installing again.
