### ISSUE TITLE
Events created with visit_id, but visit is not in db

### ISSUE THREAD

**Issue by bastiRe** [ankane/ahoy#167]
Hi,
we're using Ahoy in a Rails 4.2 app with Postgres 9.4.. Unfortunately we just discovered that we have one major problem. Every day a few hundred events are created which have a visit_id but the corresponding visit is not in the database. This also means that we don't have access to a visitor_id or similar and makes those events unusable for us.
Any ideas why this could be happening? Our ahoy configuration is: 
```
  Ahoy.visit_duration = 30.minutes
  Ahoy.quiet = false
  Ahoy.geocode = false
```

**Comment by joefreeman** [comment]
Unless you enable [`track_visits_immediately`](https://github.com/ankane/ahoy#track-visits-immediately), visits will only be created when the request is made to do so by the JavaScript library. If this is only happening for some of your events, maybe there's something preventing those clients running the JavaScript. Alternatively, you might consider adding the visitor ID to the event model.

**Comment by bastiRe** [comment]
Solved my issue. After some digging we realised that Ahoy is giving each event a new `visit_id` without a corresponding visit if cookies don't work and the visit is therefore not saved to the db. However, this could probably be made a little clearer in the docs.
