### ISSUE TITLE
How to test Visit counting via Spinach

### ISSUE THREAD

**Issue by gltarsa** [ankane/ahoy#168]
Is it possible to test an Ahoy usage with Spinach?  I have the following `.feature` file:

```
Feature: Visit Counter
  @javascript
  Scenario: A new user visiting the page increases the visit count
    Given I am not signed in
    When a new visitor visits the page
    Then the visit counter increases by 1
```

I have implemented these steps:

```
class Spinach::Features::VisitCounter < Spinach::FeatureSteps
  step 'I am not signed in' do
    Ahoy.track_visits_immediately = true
    visit root_path
    @initial_count = Visit.count
  end

  step 'a new visitor visits the page' do
    visit destroy_user_session_path
    visit root_path
  end

  step 'the visit counter increases by 1' do
    puts "Visit count ] #{Visit.count}"
    expect(Visit.count).to eql(@initial_count + 1)
  end
end
```

But the expectation fails; the counter remains at 0.   Ahoy is not updating the  database as part of this test.

Suggestions as to what I may be doing wrong?

Thanks,
Greg

**Comment by ankane** [comment]
Hey @gltarsa, I'm not familiar with Spinach, but maybe someone else will weigh in.

**Comment by Startouf** [comment]
Hey, did you manage to make it work ? I'm using Cucumber and I also rely on Ahoy visits to populate a view_counter

**Comment by gltarsa** [comment]
Alas, no.  I have been wanting to walk through the Ahoy code to see what it is that triggers the persisting of the `Ahoy::Event` data, but this is my fun side project and I've given higher priority to getting other features going.  I was hoping to see a test in the repo that exercised this, but there is none that I can find.  

Happily, it appears to work in production.  I just hate not having a test for the feature.

**Comment by Startouf** [comment]
@gltarsa yes I am indeed using JS on almost all my tests including those where I wanted the feature.
However, I am testing with Poltergeist mainly, I haven't tried with Safari/Selenium Driver, which may help in that case.

So yes I believe we'd need to dig that persistence code from the library... I'll probably end up doing that some time.

**Comment by Startouf** [comment]
Darn, after debugging the code, it would seem the code goes all the way to `/lib/ahoy/stores/base_store.rb` which reads 

```
def bot?
  @bot ||= request ? Browser.new(request.user_agent).bot? : false
end
```
So yeah of course it recognises our virtual browsers as bots...

The related part of the doc is there https://github.com/ankane/ahoy#exclude-bots-and-more

Since we do not expect any bots in Cucumber I believe it's okay to monkeypatch with a support file (@ankane ?)

```
features/support/ahoy.rb
class Ahoy::Store < Ahoy::Stores::YourORMStore
  def exclude?
    false
  end
end
```
Be sure to replace YourORMStore with your actual store

The cleaner way would be to define a configuration variable for test environment that would set the exclude? to false

**Comment by ankane** [comment]
@Startouf That should be fine. You could also do:

```ruby
class Ahoy::Store
  def exclude?
    super && !Rails.env.test?
  end
end
```
