### ISSUE TITLE
Use UUID for visitor, visit, and event ids

### ISSUE THREAD

**Issue by ankane** [ankane/ahoy#17]
Might as well use a standard method https://github.com/sporkmonger/uuidtools

UUIDs should be stored as binary 16, not strings.

Use version 1 or 4 for visits and events (version 1 includes timestamp)
http://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_versions

Use version 5 (deterministic UUIDs) for visitor id for native apps (implemented on client, not server)

**Comment by bnussey** [comment]
Hey @ankane on this one, do we need to ensure the uuid extension is installed to postgresql for this to function correctly? I am getting the following error when accessing the Event model 

    LoadError: Unable to autoload constant Event, expected /home/action/workspace/app/models/ahoy/event.rb to define it

**Comment by ankane** [comment]
No need to have the uuid extension.

```sh
rails generate ahoy:stores:active_record
```

Should add the event model to your project.
