### ISSUE TITLE
Record separate visits for platform accounts under request paths?

### ISSUE THREAD

**Issue by mrjamesriley** [ankane/ahoy#170]
Hello,

I'm working on a new Rails application with Ahoy, a platform where each page for a user sits directly under the domain, as in:

`example.com/bob`
`example.com/alice`

I'm wanting the visits from a user to the page of `/bob` or `/alice` to be recorded as two separate visits - so that both bob and alice can independently view their traffic data. This URL setup matches Twitter, Instagram and the like.

I've tried going with an `account_id` field on the `visits` table - but given that the actual tracking takes place in a POST request to `/ahoy/events` - I don't have access to the usual data within a controller to obtain this value. A controller global variable such as `current_account` won't work as the Ahoy controllers does not inherit from ApplicationController.

Is there a way to set data in the page, which is then read by the Ahoy tracker and submitted with the request? Or perhaps another solution that'll allow this setup, which appears to be a pretty common use case.

cheers,
James

**Comment by mrjamesriley** [comment]
As an update, I've had a quick play and have made commits to a fork which can be found here: https://github.com/mrjamesriley/ahoy (with details at the top of the README). To achieve the above, I've added:

* The ability to set custom data to send along with the POST request from JS tracking a visit
* The ability to set the cookie path with the request, to essentially scope a visit to a users profile

I'd be interesting if knowing if there is a built in way to achieve my scenario described above - though the source does not seem to suggest so.

**Comment by ankane** [comment]
Hey @mrjamesriley, the Ahoy controllers do inherit from `ApplicationController`. https://github.com/ankane/ahoy/blob/master/app/controllers/ahoy/base_controller.rb#L2

You might be able to accomplish separate visit tracking by setting the cookie path.  There's not currently a way to do this, but PRs welcome.
