### ISSUE TITLE
Visit is associated with the user not the visitor

### ISSUE THREAD

**Issue by danielmyasnikov** [ankane/ahoy#171]
hi @ankane ,

Just wondering why is only the last visit is associated with the user on users signin/signup process?

https://github.com/ankane/ahoy/blob/master/lib/ahoy/stores/base_store.rb#L21

Would it be better to have a visitor associated with the user:

As a quick solution for myself I'm overriding this method in `base_store`

**Comment by ankane** [comment]
Ahoy doesn't try to link past visits to users, but you're encouraged to add an `authenticate` method in your store to customize as needed.
