### ISSUE TITLE
Transitioning over from ActiveRecord

### ISSUE THREAD

**Issue by ezuk** [ankane/ahoy#173]
Hi there,

Just starting to use Ahoy, quite excited. We're small so we're going to start with ActiveRecord, but soon enough we'll need to transition to a more serious store.

Are there any guides/examples for:

1) Migrating over from AR to something like Firehose?
2) Querying data in Firehose? (i.e, once we get the data in there, how do we get it back out again?) I know this one isn't strictly related to Ahoy -- just wondering if there are any tips/resources people can share.

I'd be happy to submit a PR to the documentation with anything new I learn here. :)

**Comment by ankane** [comment]
Hi Erez, with Firehose, you can send the events to Redshift, which is queryable.  You can also send them to S3 and import them into another queryable data store.  To migrate, update your `Ahoy::Store` to send new events to your new data store, and then import exisiting events from your database into the new data store.

**Comment by ezuk** [comment]
Nice! Very cool, thank you :)
