### ISSUE TITLE
No visit recreation on cookie timeout

### ISSUE THREAD

**Issue by ex0rcist** [ankane/ahoy#174]
Found a bug: 

1) Open page, visit is created 
2) Delete ahoy_visit cookie (simulating situation when user afk or looking other tabs, cookie times out)
3) Make ahoy.track (javascript)
4) event is recorded, but new visit is not created until page refresh, visit_id is null

solution: 
on each .track look for cookies, and re-run https://github.com/ankane/ahoy/blob/master/vendor/assets/javascripts/ahoy.js#L185 if they are not set

Going to make a PR if I'm correct. Thanks

**Comment by ankane** [comment]
Hey Eugene, you're right. A PR would be great.

**Comment by ankane** [comment]
Fixed with #189
