### ISSUE TITLE
Scope `safely` method only to objects that actually need it

### ISSUE THREAD

**Issue by zspencer** [ankane/ahoy#175]
We really like ahoy where we work; but with the inclusion of `safely_block` it began monkey patching two methods globally onto `Object`; resulting in some amount of consternation among our security team. 

It would be great if ahoy required `safely/core` and then only used `include Safely::Methods` in the Tracker class which uses it.

This way all objects in all downstream users of Ahoy do not have `yolo` and `safely` methods appended to them.

**Comment by ankane** [comment]
Merged.
