### ISSUE TITLE
Exclude certain controller from being tracked

### ISSUE THREAD

**Issue by cyzanfar** [ankane/ahoy#181]
Is there a way to exclude certain controller from being tracked. For example `Home#index`persists this Ahoy::Event object:
```
#<Ahoy::Event:0x007f8edd049de0> {
            :id => 64,
      :visit_id => 0,
       :user_id => nil,
          :name => "Processed home#index",
    :properties => {
        "controller" => "home",
            "action" => "index"
    },
          :time => Sat, 04 Jun 2016 18:21:32 EDT -04:00
}
```
i'd like to skip those since it's not really relevant to what i'm trying to track

**Comment by ankane** [comment]
Hi Cyrus, you can skip the `before_action` if you want to exclude certain controllers.
