### ISSUE TITLE
Track_visit throwing error

### ISSUE THREAD

**Issue by cyzanfar** [ankane/ahoy#183]
I'm getting a `NoMethodError (undefined method visitor_id=' for #<Visit:0x007fb1e3a3b5c8>)` when tracking visits.

```
    def track_visit(options, &block)
      binding.pry
      visit =
        visit_model.new do |v|
          v.id = ahoy.visit_id
          v.visitor_id = ahoy.visitor_id # here is the issue
          v.user = user if v.respond_to?(:user=)
          v.started_at = options[:started_at]
        end

      set_visit_properties(visit)

      yield(visit) if block_given?

      begin
        visit.save!
        geocode(visit)
      rescue *unique_exception_classes
        # do nothing
      end
    end
```

I followed the readme. Event tracking works but visit doesn't. would you have any clue on what happening?

**Comment by ankane** [comment]
Hi Cyrus, does your `Visit` model have a `visitor_id` column?

**Comment by monfresh** [comment]
@cyzanfar It seems like you are using the `ActiveRecordStore`, but your DB is expecting you to use `ActiveRecordTokenStore`. If you ran these commands from the README:
```sh
rails generate ahoy:stores:active_record
rake db:migrate
```
then, it should have created a `visits` table with `visit_token` and `visitor_token` fields, not `visitor_id`. You can check by looking at your `schema.rb`. It should look something like this:
```ruby
create_table "visits", force: :cascade do |t|
    t.string   "visit_token"
    t.string   "visitor_token"
    t.string   "ip"
    t.text     "user_agent"
    t.text     "referrer"
    t.text     "landing_page"
    t.integer  "user_id"
    t.string   "referring_domain"
    t.string   "search_keyword"
    t.string   "browser"
    t.string   "os"
    t.string   "device_type"
    t.integer  "screen_height"
    t.integer  "screen_width"
    t.string   "country"
    t.string   "region"
    t.string   "city"
    t.string   "postal_code"
    t.decimal  "latitude"
    t.decimal  "longitude"
    t.string   "utm_source"
    t.string   "utm_medium"
    t.string   "utm_term"
    t.string   "utm_content"
    t.string   "utm_campaign"
    t.datetime "started_at"
  end
```

It should have also created a file called `config/initializers/ahoy.rb` with the following content:
```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore
  # customize here
end
```
It sounds like perhaps you are using `Ahoy::Stores::ActiveRecordStore` instead.

**Comment by monfresh** [comment]
@ankane This is yet another point of confusion with the two types of ActiveRecord stores. The README still refers to ActiveRecordStore (on line 142) even though the default is now the token store, which adds to the confusion.

**Comment by ankane** [comment]
Cleaning up issues
