### ISSUE TITLE
Upper bound on price slider should end with '+' if it's the default

### ISSUE THREAD

**Issue by toldani** [ankane/ahoy#185]
ie, it's the default, it should say $1,000,000+, since that's how the backend interprets it.  If someone clicks on it to change it, obviously the '+' would go away like the dollar signs and commas.  The plus should only be there if the upper bound for the price slider is set to the default.  This behavior should probably carry though to carat weight too, and parameters like length and ratio, if it's possible but rare for a value to fall outside of the slider range.

**Comment by ankane** [comment]
Hey @toldani, this seems to be for another project.
