### ISSUE TITLE
Storing session id in visits?  

### ISSUE THREAD

**Issue by toldani** [ankane/ahoy#186]
Considering how useful this would be for cross-referencing session data with ahoy data (if you're storing session data server-side), I'm surprised it's not being done already.  I can probably write the necessary code to do it in a half hour or so, and if you like, I can post my code.  Depending on how I do it, it may, however, be Redis-specific.

**Comment by toldani** [comment]
It was pretty easy to put in.  I forked it at: https://github.com/toldani/ahoy

Now I can pull in user session data stored in Redis by linking through visits.  Very convenient. :)

**Comment by ankane** [comment]
Hey @toldani, you can also accomplish this by adding a custom `track_visit` method (if you don't want to use a fork)
