### ISSUE TITLE
Potential Error in Readme

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy#187]
In the readme, one of the chart examples is:

    User.joins(:visit).group("device_type").count

Shouldn't it be:

    User.joins(:visits).group("device_type").count

**Comment by ankane** [comment]
Hi Andrew, I don't see that in the readme. Did you mean `Order.joins(:visit).group("device_type").count`?

**Comment by ACPK** [comment]
@ankane - Yes sorry!

**Comment by ankane** [comment]
That'd be correct for the `User` model, since it's a has many relationship, but `Order` belongs to visit.
