### ISSUE TITLE
ahoy.authenticate(@user) not working for first visit

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy#191]
When an invited user visits our site, we create an account with them using param info. Our site is correctly creating an account for them automatically, but "ahoy.authenticate(@user)" isn't associating the account to the user unless they visit for a second time.

```
# BeforeAction in Controller:

def create_guest_user
  Client.create(email: params[:email].to_s)
end

# IndexController action:

 def index
    ahoy.authenticate(@user)
    ...
 end 
```

**Comment by ACPK** [comment]
Any word on this or more info needed?

**Comment by ankane** [comment]
Hey Andrew, hope you had a nice 4th as well.  I'd try following the code path for when an account is created to see where to add `ahoy.authenticate`.  If you're calling `ahoy.authenticate` but it's not working, try adding a custom `authenticate` method in to `Ahoy::Store` to debug.

**Comment by ACPK** [comment]
@ankane - FYI: If I replace ahoy.authenticate(@user) with pry and then call ahoy.authenticate(@user) in the console, it works.
