### ISSUE TITLE
Using Ahoy to track visits via events in ruby

### ISSUE THREAD

**Issue by tbrammar** [ankane/ahoy#193]
I'm creating events in my controller like so:

`ahoy.track(action, {title: 'blah'})`

However, this only creates the event. It does not create the view as well.

I don't want to track views all across my site, so how do I create a view when I also create an event?

**Comment by tbrammar** [comment]
This is what I've gone with:

    ahoy.track_visit if ahoy_tracker.new_visit?
    ahoy.track(action, {title: 'blah'})

Please let me know whether there's amore effective way of doing this.

**Comment by ankane** [comment]
That approach looks good. You can also use the `Ahoy.track_visits_immediately` setting.
