### ISSUE TITLE
anonymize IP addresses. Is this possible?

### ISSUE THREAD

**Issue by klaustopher** [ankane/ahoy#195]
I was looking through the source code for a way to anonymize the IP address of a user before storing it in the database.

Due to some regulatory reasons it is not possible to store the IP address fully in the database but we still want to get some insights on what's happening with our users.

Am I overlooking something here? Or is this not possible with ahoy?

We have now implemented a solution where we anonymize the IP addresses with a cron job after 30 days, but I would really like not to store the full address in the first place

**Comment by ankane** [comment]
Hey Klaus, IP anonymization is not built in, but you can override the `track_visit` method to do anything.

https://github.com/ankane/ahoy#track-additional-values

**Comment by klaustopher** [comment]
Ah, that makes sense ... Thanks ;)
