### ISSUE TITLE
ideas to isolate the tracking endpoint?

### ISSUE THREAD

**Issue by jhuangtw-dev** [ankane/ahoy#196]
are there any best practices/guidance on how to best isolate the tracking endpoint from the rest of the app?
we are running on Heroku, and we'd like create some isolation between the business critical main app versus the analytics endpoint, so that if the analytics pings becomes extremely spammy, our main app would not be affected. (we've already played with the rack attack parameters as part of the ahoy config).

high level we're thinking along the lines of:
- is it possible to bind the ahoy endpoint to specific dynos? (not obvious from docs if this was doable at all)
- run another app instance off the same production db, but only use it to receive and process ahoy pings (look up user metadata etc).

we may be completely off-track here so any advice greatly appreciated!

**Comment by ankane** [comment]
Hey @jhuangtw-dev, we haven't had any performance issues with Ahoy endpoints to date.  My suggestion would be to use a service like AppSignal or New Relic to monitor performance and hold off on optimizing until needed.

**Comment by jhuangtw-dev** [comment]
@ankane thank you for the input.
any idea/experience around the highest request-per-second folks have had with ahoy?

tracking view, click and submits, our newrelic dashboard shows that our transaction (request) count doubles - which is not surprising as there are likely many-js-events-to-one-controller growth.
any advice around resource provisioning? we plan to do loadtest on a forked environment before enabling in production.

**Comment by ankane** [comment]
I'm unsure about req/s stats. Nothing special for resource provisioning - I'd handle this just as you would with other potentially write-heavy features.
