### ISSUE TITLE
Ahoy store is set as MongoDB and user is on Mysql having problems in association

### ISSUE THREAD

**Issue by hassaniftikhar** [ankane/ahoy#197]
My application is using two datasotres mongodb and mysql, Ahoy is using mongodb while my user model is ActiveRecord using mysql as backend store.

Given that when I a visit is created the user visitor id is not set properly and it results in improper association, also an exception is generated when ahoy hits current_user (using devise)

ELECT  `users`.\* FROM `users` WHERE `users`.`is_deleted` = 0 AND `users`.`_id` = 39738  ORDER BY `users`.`id` ASC LIMIT 1
Mysql2::Error: Unknown column 'users._id' in 'where clause': SELECT  `users`.\* FROM `users` WHERE `users`.`is_deleted` = 0 AND `users`.`_id` = 39738  ORDER BY `users`.`id` ASC LIMIT 1
Mysql2::Error: Unknown column 'users._id' in 'where clause': SELECT  `users`.\* FROM `users` WHERE `users`.`is_deleted` = 0 AND `users`.`_id` = 39738  ORDER BY `users`.`id` ASC LIMIT 1

So is there any way I can resolve that where my user is on mysql and ahoy is using mongodb.

Any help would be appreciated, Thanks.

**Comment by ThanhKhoaIT** [comment]
Hi! Me too...

And fixed!
In `app/models/ahoy/event.rb` my file
```ruby
class Ahoy::Event
  include Mongoid::Document

  # associations
  belongs_to :visit

  # fields
  field :name, type: String
  field :properties, type: Hash
  field :time, type: Time
  field :user_id, type: Integer
  index({user_id: 1}, {name: :user_id_index})

  def user
    User.find_by_id(self.user_id)
  end

  def user=(user)
    self.user_id = user.id
  end
end
```

Now, working for me!

**Comment by ankane** [comment]
Cleaning up issues. I haven't tried to use separate data stores for users and visits - thanks for taking this one @ThanhKhoaIT
