### ISSUE TITLE
Grouping and counting Ahoy::Events by properties

### ISSUE THREAD

**Issue by genlighten** [ankane/ahoy#198]
I'm trying out the new capability to query Ahoy::Events using the where_properties method. I can reproduce the provided example no problem:

`Ahoy::Event.where(name: "Viewed profile").where_properties(profile_id: 2).count`

yields 2, since profile 2 has received 2 views, each tracked by its own event.

I also record the property "referral_url" for each event, in hopes of tracking what internal pages on our site send clients to view providers' profiles. I'd like to provide a list of referral_urls with a count for how many events (profile_views) had a specific referral_url and visited a specific profile.

Something like this:

`Ahoy::Event.where(name: "Viewed profile").where_properties(profile_id: 2).group("properties(referral_url)").count`

but this yields a mysql error:

`ActiveRecord::StatementInvalid: Mysql2::Error: FUNCTION genlighten3_development.properties does not exist:`

What would be the proper way to query events using group for an event property?

Thanks!

--Dean

**Comment by ankane** [comment]
You should be able to take the SQL generated from `where_properties` (without the equals part) and use it in `group`.

**Comment by genlighten** [comment]
So for instance if I define:

`profile_2_events = Ahoy::Event.where(name: "Viewed profile").where_properties(profile_id: 2)
`
and I then try to calculate:

`profile_2_events.group("properties REGEXP '[{,]\"referral_url\"...).count`

or something like that, I'll get back a hash of referral_urls with counts of how many times they show up in profile_2_events?

--Dean

**Comment by ankane** [comment]
This approach won't work with `text` fields unfortunately. I'd highly recommend using `jsonb` with Postgres or `json` with MySQL.  Otherwise, you'll be limited by the queries you can run.
