### ISSUE TITLE
duplicate click events

### ISSUE THREAD

**Issue by jhuangtw-dev** [ankane/ahoy#199]
Hi all,
I'm in the middle of setting up ahoy with our Rails app and observing some strangeness in browser console; not sure if it's related to turbolink or the way we're calling ahoy.trackClicks().

our setup:
- rails 4.2.6 with turbolink
- Ahoy.track_visits_immediately = true
- ahoy.js included as README described
- in our page body, we call ahoy.trackClicks() and ahoy.trackView() where we call other trackers like GA.

symptom:
views seem to track fine, but clicks seem to to get repeated with each incremental action.
eg:
first click would log 1 click.
second click would log 2 clicks.
third click would log 3 clicks ... and so on.
the duplicated click events would all be on the previous clicked-on DOM element, as if the onclick callback is being called multiple times.

any help appreciated!

**Comment by jhuangtw-dev** [comment]
answering my own question here: most likely turbolink. since the partial i had that was calling trackClicks() was being called more than once while the other document hasn't changed, looks like the onClick() events were getting added and causing duplicate tracking calls firing.

**Comment by meerageorge** [comment]
@jhuangtw-dev What's the solution here?

**Comment by mmgeo** [comment]
Figured out that including the ahoy.trackclicks() script inside the head tag solves the issue.
