### ISSUE TITLE
log goes quiet after visit is recorded

### ISSUE THREAD

**Issue by a5sk4s** [ankane/ahoy#202]
when Ahoy.quiet is set to true (default), all logs go quiet subsequently to a recorded visit. no further requests are being logged.

by setting Ahoy.quiet to false, we are able to circumvent this behavior. not sure yet what implication this would have on production.

i can see some monkey patching in the ahoy code, but can't find how this would be reverted, so that subsequent requests are properly logged.

any help is appreciated

**Comment by ankane** [comment]
It sounds like the log silencer is not being reset properly (possibly a library conflict, but not sure). Setting `Ahoy.quiet = false` should be fine for production - you'll just see the ahoy endpoints in your logs.

**Comment by a5sk4s** [comment]
thanks for your response

if you could direct me to the part that is supposed to reset the logger state, i might be able to look into it a little further

we are also using `Ahoy.geocode = :async` and that is showing up as the last entry in the log when `Ahoy.quiet` is set to `true`

**Comment by ankane** [comment]
Hey @a5sk4s, thanks for wanting to look into it.  I'd clone the repo and do a search for `quiet` to find the appropriate code.

**Comment by ankane** [comment]
Cleaning up issues
