### ISSUE TITLE
Feature: Not tracking admin users

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy#205]
For our admin backend, we're using `skip_before_action :track_ahoy_visit` to not track admin users but what would be the best strategy for:
1. Stop tracking of users where `.is_admin?` is true.
2. Delete visits which were immediately or later connected to admin user.

**Comment by ankane** [comment]
If you're not planning to store them, Ahoy's [exclude method](https://github.com/ankane/ahoy#exclude-bots-and-more) is probably best.

**Comment by ACPK** [comment]
@ankane - Will this delete the visit that gets later associated to them when they log in?

**Comment by ankane** [comment]
No, it won't. It'll only ignore events after the user is logged in.

**Comment by pcraston** [comment]
Sorry to re-open this issue (and if this is a dumb question!) but how can I access the `current_user` in Ahoy's [`exclude_method`](https://github.com/ankane/ahoy#exclude-bots-and-more) to check if `current_user.admin?` is true (I'm using Devise)? 

Been searching the documentation and source code but as far as I can tell the `controller` and `request` objects both don't have access to the `current_user`?

Thanks for your help!

**Comment by fadyZohdy** [comment]
@pcraston did you find a way for doing that ?

**Comment by pcraston** [comment]
Nope! But I can't even remember the use case for why I wanted to do this anymore... 😜

**Comment by euxx** [comment]
It seems `current_user` can be accessed like this:
```rb
Ahoy.exclude_method = lambda do |controller, request|
  controller.current_user
  controller.send(:current_user) # If current_user is a private method
end
```
