### ISSUE TITLE
External Link Clicks

### ISSUE THREAD

**Issue by wmlockhart** [ankane/ahoy#206]
Thank you so much for sharing the ahoy.js script. I am currently experimenting with this script and hopefully plan to use it in an upcoming project. One thing I have noticed with tracking external link clicks is that the event doesn't get posted to my data collection endpoint. What changes do I need to make to ahoy.js to achieve tracking of external link clicks? Thanks.

**Comment by ankane** [comment]
Hey @wmlockhart, there's not a great way to do this right now unfortunately. One approach would be for Ahoy to use `navigator.sendBeacon` when possible, and fall back to delaying the navigation on unsupported browsers for links that were detected / marked as external.

**Comment by wmlockhart** [comment]
Hi Andrew. Thanks for responding so quickly. I had an idea that it wasn't going to be straightforward. Thanks again for your script - I've learnt a lot. Have you any plans to develop the script further? Regards. Walter.

Get Outlook for iOS




On Thu, Aug 18, 2016 at 6:36 AM +0100, "Andrew Kane" <notifications@github.com> wrote:












Hey @wmlockhart, there's not a great way to do this right now unfortunately. One approach would be for Ahoy to use navigator.sendBeacon when possible, and fall back to delaying the navigation on unsupported browsers for links that were detected / marked as external.

**Comment by ankane** [comment]
Yeah, definitely. I don't have an immediate need for this, but happy to accept a PR if someone else wants to add it.

**Comment by wmlockhart** [comment]
I'll try to get some time to take a look at navigator.sendbeacon and get back to you. Thanks again.


Get Outlook for iOS




On Thu, Aug 18, 2016 at 7:36 AM +0100, "Andrew Kane" <notifications@github.com> wrote:












Yeah, definitely. I don't have an immediate need for this, but happy to accept a PR if someone else wants to add it.

**Comment by ankane** [comment]
Cleaning up issues - Ahoy.js has had this for a while now.
