### ISSUE TITLE
Ahoy with caching

### ISSUE THREAD

**Issue by thomassnielsen** [ankane/ahoy#207]
We're having trouble finding a good way to use Ahoy while still caching certain pages with Varnish. the issue is that Ahoy sets a cookie, which makes Varnish not cache the content (understandably). I see there [is an older issue](https://github.com/ankane/ahoy/issues/49) about this, but it was closed without any further info. Any suggestions welcome.

**Comment by ankane** [comment]
You should be able to do all the tracking client side (including setting cookies) by skipping certain filters. Try adding to your controller:

```ruby
skip_before_action :set_ahoy_cookies
skip_before_action :track_ahoy_visit
```

**Comment by thomassnielsen** [comment]
I started looking at this again recently. Although the above actions does what it says, this won't help as long as the client sends cookies with each request. I understand that this is part of how Ahoy works, so I'm not quite sure to go from here. Any suggestions appreciated. I'm currently investigating if we can turn of regular tracking and just track events, as we can except `/ahoy/` URLs from Varnish caching.

**Comment by ankane** [comment]
You should be able to configure Varnish to ignore certain cookies from what I recall.

**Comment by thomassnielsen** [comment]
Yes, that's my plan for testing tracking only events. I'll report back if I find a good solution.

**Comment by thomassnielsen** [comment]
Found a working solution by using the `skip_before_action`s described above.

Excerpt from my new varnish config, that tracks events but still caches pages:
```vcl
sub vcl_recv {
  if (req.url ~ "^/ahoy") {
    return (pass);
  } else if (req.method == "GET") {
    # Remove Ahoy cookies
    set req.http.Cookie = regsuball(req.http.Cookie, "(^|;\s*)(ahoy_[_a-z0-9-]+)=[^;]*", "");
    return (hash);
  } # else go to default
}
```

**Comment by ankane** [comment]
Awesome, thanks for updating. Hopefully someone will find this useful in the future.
