### ISSUE TITLE
Will ahoy track all incoming requests(including API requests) ?

### ISSUE THREAD

**Issue by letronje** [ankane/ahoy#212]

**Comment by ankane** [comment]
Hey @letronje, please explain more.

**Comment by letronje** [comment]
@ankane Since the documentation talks abt adding the ahoy javascript file, I was wondering if ahoy can track API requests send by native mobile apps to the rails app? Rails apps are often used as API endpoints in additional to serving web requests.

**Comment by ankane** [comment]
Yes, native apps are mentioned throughout the readme, and even have their [own section](https://github.com/ankane/ahoy#native-apps-1). Please read this before creating issues in the future.
