### ISSUE TITLE
Rails 5 belongs_to association behavior overridden

### ISSUE THREAD

**Issue by jeromedalbert** [ankane/ahoy#213]
In Rails 5 `belongs_to` associations are required by default. This is enforced by this line in `config/initializers/new_framework_defaults.rb`:
```ruby
# Require `belongs_to` associations by default. Previous versions had false.
Rails.application.config.active_record.belongs_to_required_by_default = true
```

Unfortunately, it means that gems that have an initializer that is lexicographically before the string "new_framework_defaults" (I think) and monkey patch too soon in the Rails autoloading process will break this Rails behavior. `ahoy` is one of those.

See issue https://github.com/rails/rails/issues/23589 for more information about the issue (the problem persists even for Rails 5 final). And [here is a commit](https://github.com/plataformatec/devise/commit/c2c74b0) that fixed the issue on the devise gem. It looks like using `ActiveSupport.on_load` instead of `ActiveRecord::Base.extend` could fix the problem.

**Comment by ankane** [comment]
Give master a shot.

**Comment by jeromedalbert** [comment]
It works! Thanks. :shipit:
