### ISSUE TITLE
Upgrading to ActiveRecordTokenStore

### ISSUE THREAD

**Issue by kevinjbayer** [ankane/ahoy#214]
So, upgrading to JSONB was no problem, but I'm a bit confused on upgrading to ActiveRecordTokenStore. 

I can't run `rails g ahoy:stores:active_record` since that tells me there's already another migration conflicting.

If I try to create a new migration with new columns for id and visitor_id as integers, I can't transfer the old UUID's over. Even just adding a new column called visit_token then violates the not-null on ID, but I can't just remove the ID. Help. I'm so confused. I'm just gonna stick with ActiveRecordStore that worked fine until I've got a clearer vision on moving forward. BTW, I love Ahoy. I'd love to help improve documentation with you.

**Comment by ankane** [comment]
Hey @kevinjbayer, there's not a strong reason to move from `ActiveRecordStore` to `ActiveRecordTokenStore`. It'll likely be a lot of work with little benefit, and `ActiveRecordStore` will continue to be supported.

**Comment by kevinjbayer** [comment]
Ah, ok. That makes me feel better. All of the examples in the README point to the Token store now so I figured it was going that route. It's certainly all still working great without using tokens. Out of curiosity, why the switch if there's little benefit? Why switch to integers instead of UUID's?

Feel free to close this issue. Maybe a note in the README that either can be used might be helpful to folks in the future.

**Comment by ankane** [comment]
The main reason for the switch is it's easier to work with integer ids than UUIDs. Developers are more familiar with integer ids, `Visit.last` returns the most recent visit in development, and numerous people have reported issues about errors storing UUIDs (which I haven't been able to reproduce).

The downside is you have to create the `Visit` (to get an id) before you create events associated with it, whereas with a UUID, you can create the `Visit` afterwards.

I'll add a short note in the readme about continuing support.
