### ISSUE TITLE
Encoding::UndefinedConversionError when tracking actions

### ISSUE THREAD

**Issue by darrenboyd** [ankane/ahoy#219]
We're starting to see quite a few errors being reported to AppSignal (our error reporting integration). They all look like...

`Encoding::UndefinedConversionError [safely] "\x9C" from ASCII-8BIT to UTF-8`

Since this is happening in an `after_action`, it's been hard to track down the cause. However, we finally tripped over this error in development, and got the error to repeat.  Here's the Rails error page...

![image](https://cloud.githubusercontent.com/assets/6103/18398026/a3d060de-767f-11e6-821e-8f1a5ddc6575.png)

My guess is that the uploaded file is trying to be coerced into a String. But, that's just a guess.

This hasn't been very reproducible, but if you like, we will take the time to try and build and app where it can be repeatably reproduced.

We can also fix the issue too, but wouldn't mind some guidance from anyone who knows the codebase better.

Thoughts?

**Comment by ankane** [comment]
It seems like Ahoy is having trouble storing the `ActionDispatch::Http::UploadedFile` due to its encoding - are you using one of the ActiveRecord stores?

My suggestion would be to filter out `ActionDispatch::Http::UploadedFile` types before passing it to Ahoy (stick with simple types). I'm happy to update the readme example to reflect that.

**Comment by darrenboyd** [comment]
I was originally thinking that this could be solved within ahoy. Now I realize that it can't (at least not without a lot of jumping through hoops).

This is literally what I've added to our `ApplicationController`. This will layer on additional filtering for ahoy to what the stock rails filtering which we also want (things like passwords, SSN, etc.).

```ruby
ADDITIONAL_AHOY_FILTERS = [ :blank_file, :signature, :wet_signature, :file, :image, :logo ]
AHOY_PARAM_FILTER       = ActionDispatch::Http::ParameterFilter.new(ADDITIONAL_AHOY_FILTERS)

def track_action
  ahoy_params = AHOY_PARAM_FILTER.filter(request.filtered_parameters)
  ahoy.track "Processed #{controller_name}##{action_name}", ahoy_params
end
```

I'd rather just filter out by type of `value`, but the `ActionDispatch::Http::ParameterFilter` isn't quite that sophisticated.

Feel free to generalize that example, and add it to the readme, if you think it would help others.

Thanks!

**Comment by mikewagz** [comment]
Thank you @darrenboyd - this error was constantly turning up in our error reporting too.  Your solution is perfect!
