### ISSUE TITLE
Visitable model getting a nil visit_id

### ISSUE THREAD

**Issue by jamesvanklink** [ankane/ahoy#220]
We have a few visitable models (Page view, ad view) in our website and sometimes the records are being created with a nil visit_id.

We are using the ActiveRecordTokenStore.

track_visits_immediately is set to true, since we log page views on pages that could be a user's landing page.

I haven't been able to track down a reason for this and was wondering if you have any general guidance on how to diagnose?

**Comment by tlawal** [comment]
I'm having this issue as well.

**Comment by davidguthu** [comment]
I'm seeing this also.

**Comment by BrahimDahmani** [comment]
+1, any news here?

**Comment by ankane** [comment]
If `Ahoy.track_visits_immediately = true`, one way I can see this happening is if the visit is being excluded. Ahoy excludes bots (or what it thinks are bots) by default. You can change this with:

```ruby
class Ahoy::Store
  def exclude?
    false
  end
end
```
