### ISSUE TITLE
Avoid tracking events without visit or from specific IP addresses

### ISSUE THREAD

**Issue by vitobotta** [ankane/ahoy#224]
Hi! I am using this gem in an app and love it! Thanks.

I am having a little problem with visits from UptimeRobot monitoring. Strange enough Ahoy logs events for these but without an associated visit. Why is this happening?

Also, in my ApplicationController I have:

``` ruby
  def track_action
    unless MONITORING_IPS.include? request.ip
      ahoy.authenticate(current_user) if current_user
      ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
    end
  end
```

This excludes visits from the monitoring service's IPs, but events are still created (without the visit_id) and I am not sure of how to prevent this... any suggestion?

Thanks!

**Comment by vitobotta** [comment]
I forgot to mention that I am using both the Ruby and JavaScript tracking because without the JavaScript tracking, for some reason, it doesn't associate the current user to the visit after sign in even though I have ahoy.authenticate(user) in my authentication action (using custom authentication, not Devise).

**Comment by ankane** [comment]
Hey @vitobotta, check out this section of the readme: https://github.com/ankane/ahoy#exclude-bots-and-more
