### ISSUE TITLE
undefined method `where_properties' for #<Ahoy::Event::ActiveRecord_Relation>

### ISSUE THREAD

**Issue by mreigen** [ankane/ahoy#230]
I have this code:

```
class User < ActiveRecord::Base
  include Ahoy::Properties
  def get_events
    Ahoy::Event.where(name: "Processed cars#search")
      .where_properties(viewer_id: self.id)
  end
end
```

but when I ran the method ```get_event``` it would give this error:

`undefined method 'where_properties' for #<Ahoy::Event::ActiveRecord_Relation>`

The app is using ahoy_matey 1.5.2

I was following the documentation. Am I doing it wrong?

**Comment by ankane** [comment]
`include Ahoy::Properties` should be added to `Ahoy::Event` instead of `User`.

**Comment by mreigen** [comment]
Nice, thank you. It works. I have created a PR to update the readme file:

https://github.com/ankane/ahoy/pull/231

**Comment by ankane** [comment]
Great, thanks for taking the time to contribute!
