### ISSUE TITLE
Install in padrino

### ISSUE THREAD

**Issue by faustoct** [ankane/ahoy#232]
Trying to install in padrino but get this

padrino g ahoy:stores:mongoid
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/ahoy_matey-1.3.1/lib/ahoy.rb:1:in `require': cannot load such file -- rails (LoadError)
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/ahoy_matey-1.3.1/lib/ahoy.rb:1:in `<top (required)>'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/ahoy_matey-1.3.1/lib/ahoy_matey.rb:1:in `require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/ahoy_matey-1.3.1/lib/ahoy_matey.rb:1:in `<top (required)>'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `each'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `each'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/bundler-1.8.5/lib/bundler.rb:134:in `require'
	from /Users/fausto/Projects/coding/4linked/config/boot.rb:9:in `<top (required)>'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3/lib/padrino-gen/generators/cli.rb:26:in `require'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3/lib/padrino-gen/generators/cli.rb:26:in `load_boot'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3/bin/padrino-gen:16:in `<main>'

**Comment by ankane** [comment]
Hey @faustoct, as the error message indicates, Ahoy requires Rails.

**Comment by faustoct** [comment]
Cannot use higher level of abstract ?
