### ISSUE TITLE
NoMethodError: undefined method `fields' for nil:NilClass

### ISSUE THREAD

**Issue by jadeKing** [ankane/ahoy#234]
Rails: 4.1.14.2,  with prepared statements disabled
Ruby: 2.1.8
pgbouncer to manage DB connections

We have this error occurring in large numbers but it doesn’t stop the page from loading and only affects ahoy.
It happens when ahoy tracks a visit. The visit is saved with the valid parameters but throws the error

NoMethodError: undefined method `fields' for nil:NilClass

We use pgbouncer to manage DB connections and wonder if this might be part of the problem.

Has anyone else had this problem?

**Comment by ankane** [comment]
Hey @jadeKing, think this is a Rails thing rather than Ahoy: https://github.com/rails/rails/issues/18027
