### ISSUE TITLE
Bug with API Use?

### ISSUE THREAD

**Issue by dts** [ankane/ahoy#236]
I'm trying to track down an irritating behavior that prevents "visits" from being set correctly in my use case.  Initially, I thought it was related to a race condition in the startup of my mobile app, but I'm pretty convinced now that this is not the case.  The source of the problem is a difference in the visit_token between what my app is POSTing and what the event is registering with later.  This could come from a few different things, the most obvious two are that `:api` is set incorrectly, or that `existing_visit_token` is called twice, and the first time the wrong thing happens.  I've done all I can do trying to figure it out without installing it locally and peppering the code with debug statements, but before I do that I wanted to check in and see if @ankane had any ideas about what this might be.  

For now, I have fixed it with this patch:

```
    # in super do |event| in my "store" definition
      # shim to re-set the visit if it got mismatched between cookies
      # and params:
      unless event.visit
        event.visit = Visit.find_by_visit_token(controller.try(:request).params['visit_token'])
        event.save
      end
```

**Comment by ankane** [comment]
Some request stores (like `ActiveRecordStore`) ensure the visit token is a valid UUID, and coerce it into one if it's not. If you set things up locally, it should be fairly easy to debug.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if there's more to add.
