### ISSUE TITLE
Encoding::UndefinedConversionError "\xFF" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by dikey94** [ankane/ahoy#237]
Hi guys,
just can't upload any photo using active_admin and paperclip.
![0d304e8e03a1472f7eb1fa62de72da60](https://cloud.githubusercontent.com/assets/14232224/20504100/109b9062-b046-11e6-8726-0283ab3af4f3.png)

 Encoding::UndefinedConversionError in Admin::UsersController#update 
"\xFF" from ASCII-8BIT to UTF-8

**Comment by ankane** [comment]
You'll need to manually filter out any image parameters before passing them to Ahoy.

**Comment by dikey94** [comment]
How can I do it? 
Filtered parameters:
`=> {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"hsQWowdrFh4YiMZ/baKkVxx1F2AlMdfcesTNx5vplHM+PD7ob0zroAZeos/BiX1dHPMl/ZU9czNA/Bl9IxJkPg==", "user"=>{"first_name"=>"John", "last_name"=>"Lennon", "email"=>"admin@admin.com", "unconfirmed_email"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "picture"=>#<ActionDispatch::Http::UploadedFile:0x007ffdfbe92018 @tempfile=#<Tempfile:/var/folders/m1/_gr7yy255pzc7n6_9nycy3f80000gn/T/RackMultipart20161122-20099-198un06.png>, @original_filename="0d304e8e03a1472f7eb1fa62de72da60.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[picture]\"; filename=\"0d304e8e03a1472f7eb1fa62de72da60.png\"\r\nContent-Type: image/png\r\n">, "role_ids"=>["", "1", "2"]}, "commit"=>"Aktualizuj Użytkownik", "controller"=>"admin/users", "action"=>"update", "id"=>"1"}`

**Comment by ACPK** [comment]
@dikey94 - I'm also getting this same error.

**Comment by ankane** [comment]
I updated the example in the readme.

@dikey94 see https://github.com/ankane/ahoy/issues/219#issuecomment-246413275 for a solution.
