### ISSUE TITLE
UUID Error on Migration

### ISSUE THREAD

**Issue by ryanchin** [ankane/ahoy#241]
I'm receiving an error when doing the migration `undefined method `uuid` for #<ActiveRecord::ConnectionAdapters::TableDefinition>`.

I think that it may be because I'm running Rails 4.  If this is the case, is there a version that I can use for Rails 4?   Thank you!

**Comment by olimart** [comment]
Did you activate the extension in PostgreSQL?
http://blog.arkency.com/2014/10/how-to-start-using-uuid-in-activerecord-with-postgresql/

**Comment by ryanchin** [comment]
I'm using mySQL.  Is there something that needs to be done in mySQL to enable UUID?  I tried searching, but couldn't find anything.

**Comment by olimart** [comment]
I don't know but found this http://geekhmer.github.io/blog/2014/12/06/using-uuid-as-primary-key-in-ruby-on-rails-with-mysql-guide/ and this http://stackoverflow.com/questions/40987630/rails-5-how-to-add-uuid-column
