### ISSUE TITLE
Recording page title in Visit model

### ISSUE THREAD

**Issue by activestylus** [ankane/ahoy#242]
I'm currently doing this in a callback and it works but is often very slow (10-30 seconds)

`update_column :page_title, Nokogiri::HTML(open(landing_page)).title`

Is there a straightforward way I can pull the `<title>` text into the visit model, rather than forcing another http request?

**Comment by ankane** [comment]
Hey @activestylus, there's not an easy way right now. You could use JavaScript events and pass the title as a property.
