### ISSUE TITLE
ahoy.trackView() POSTs twice to server, creating two $view Events for a single visit

### ISSUE THREAD

**Issue by georgecheng** [ankane/ahoy#243]
- I created a fresh, empty Rails app (5.0.0.1) adding only the 'ahoy_matey' gem. 
- I required ahoy.js in application.js. 
- I then created a single controller with a single action and set the root route to point to it. 
- Inside the view file I added script tags with ahoy.trackAll(). 
- I visit the root page and check the database. 
- I see two Ahoy::Events (two $view events) created for that single visit.
- Rails console shows two POSTs
- I refresh page and check database and see another two Ahoy::Events created for that visit. 
- Four Ahoy::Events ($view) were created for two visits.

I don't think this is the intended behavior. I have been unable to figure out why it's creating two view events in the database for each visit.

**Comment by ankane** [comment]
Any way you're accidentally calling `ahoy.trackAll()` twice?

**Comment by georgecheng** [comment]
Another thing I noticed is that the double POST is happening only after an initial visit. After doing an `ahoy.reset()` and refresh, I get one Visit created and one Event created. If I then refresh the page again, I get two Events created.

**Comment by georgecheng** [comment]
Is anyone else seeing this double POST issue?

**Comment by NathanExpl0sion** [comment]
I'm getting this as well. Anyone know a fix yet?

**Comment by jhuangtw-dev** [comment]
could be TurboLinks?
depending on how you're including ahoy.js on your site, `ahoy.track*()` may be accidentally included/called more than once.

I ended up working around TurboLink quirks with something like (coffee script):
```
$(document).on('page:change', =>
  # These methods call document.on('event') and should not be called
  # more than once per lifecycle of document.
  unless window.ahoyDocumentEventTrackersInitialized
    ahoy.trackClicks()
    ahoy.trackSubmits()
    window.ahoyDocumentEventTrackersInitialized = true

  # Should be called once per page load.
  ahoy.trackView()
)
```

**Comment by georgecheng** [comment]
@jhuangtw-dev I had considered that, but I had initially experienced this issue on a non-rails javascript frontend that used rails as an api backend. I thought perhaps it was a problem with the JS app, so I tested it on a clean Rails install and experienced the same issue. Digging through the source code for ahoy.js and the gem, I haven't been able to find where the issue is coming from yet.

**Comment by ankane** [comment]
Found the issue. Thanks all for reporting and helping debug.
