### ISSUE TITLE
Don't overwrite browser session after tracking

### ISSUE THREAD

**Issue by glennfu** [ankane/ahoy#245]
I have some code that dynamically changes session cookie parameters in an `after_action` in my `ApplicationController`. This wasn't being triggered in the Ahoy controllers. I had to add this to an initializer:
```
module Ahoy
  class BaseController < ApplicationController
    before_action :ignore_session
    
    def ignore_session
      request.session_options = request.session_options.dup
      request.session_options[:skip] = true
      request.session_options.freeze
    end
    
  end
end
```

Now no matter what else is going on, I know that the response from an event track won't change my session cookie. Is there any reason this wouldn't be default behavior? I couldn't think of a reason why it would ever be appropriate for Ahoy to change the session cookie.

**Comment by ankane** [comment]
Hey @glennfu, how was Ahoy modifying the session cookie?

**Comment by glennfu** [comment]
I misunderstood the problem. It was that Ahoy skips all before/after actions in the controller so I had to rewire to get mine called. I'm doing some custom cookie code on every request, and without the filters, this was being lost. Here's what I had to do to get that method called in the Ahoy controllers:

```
module Ahoy
  module CPController
    def self.included(base)
      base.after_action :change_session
    end
  end
end

ActiveSupport.on_load(:action_controller) do
  Ahoy::BaseController.send :include, Ahoy::CPController
end
```
