### ISSUE TITLE
can't modify frozen Array

### ISSUE THREAD

**Issue by tomtt** [ankane/ahoy#246]
I get an error when the line
`app.middleware.use Ahoy::Throttle`
is executed (lib/ahoy/engine.rb:6).

Error message:
`
can't modify frozen Array
/myapp/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/stack.rb:112:in 'push'
/myapp/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/stack.rb:112:in 'use'
/myapp/shared/bundle/ruby/2.3.0/gems/ahoy_matey-1.5.3/lib/ahoy/engine.rb:6:in 'block in <class:Engine>'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in 'instance_exec'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in 'run'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in 'block in run_initializers'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in 'run_initializers'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:352:in 'initialize!'
/myapp/releases/20170110180324/config/environment.rb:5:in '<top (required)>'
/myapp/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in 'require'
/myapp/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in 'block in require'
/myapp/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in 'load_dependency'
/myapp/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in 'require'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:328:in 'require_environment!'
/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:457:in 'block in run_tasks_blocks'
/myapp/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/task.rb:62:in 'block (2 levels) in define'
/myapp/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in '<top (required)>'
/home/deploy/.rbenv/versions/2.3.1/bin/bundle:23:in 'load'
/home/deploy/.rbenv/versions/2.3.1/bin/bundle:23:in '<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
`

**Comment by ankane** [comment]
It looks like something (possibly another gem) is locking in the middleware stack before Ahoy can add to it. To skip the middleware, you can use:

```ruby
Ahoy.throttle = false
```
