### ISSUE TITLE
Drop jquery requirement?

### ISSUE THREAD

**Issue by dts** [ankane/ahoy#251]
I'd love to simplify Ahoy.js and make it less dependent - the things that you use jQuery for are straightforward to just implement.  I'd be surprised if more than 100 additional lines of code would be required, based on a cursory read of the code.  Any objections?

**Comment by ankane** [comment]
Hey @dts, @richardvenneman has done a good amount of work on it here: https://github.com/ankane/ahoy.js/pull/10

It'd be great to get your feedback.
