### ISSUE TITLE
ActiveRecordTokenStore tries to assign user even if columns don't exist

### ISSUE THREAD

**Issue by njakobsen** [ankane/ahoy#255]
Unlike `ActiveRecordStore`, `ActiveRecordTokenStore` always tries to assign a user when tracking an event, even if the `user_id` column doesn't exist.

**Comment by ankane** [comment]
Hey @njakobsen, thanks for reporting. All fixed!

**Comment by njakobsen** [comment]
Nice turnaround! I can now get rid of my `user=` method stub :)
