### ISSUE TITLE
handling ShortUrls and referrals.

### ISSUE THREAD

**Issue by holden** [ankane/ahoy#256]
Hi,

We use an internal URL shortener in our application and I'm wondering how we can handle these.  The shortener does a 301 redirect thru a controller (before loading ahoy.js) and the first page that does loads ahoy.js then lists the referral url as being the shortened url (which isn't really useful).  We'd like to know if they came from twitter or facebook which is where most of these get used.

I tried searching the issues but didn't come across anything similar, would be grateful for a general nod in the right the direction.  We are using `Ahoy.cookie_domain = :all` so the cookie shouldn't be an issue.

Thanks,

**Comment by ankane** [comment]
Hey @holden, I'd recommend:

1. In the shortener, either set a cookie with the referrer or pass it through to the redirect as a query parameter.
2. On the landing page, pass the referrer to Ahoy (by reading the cookie or the query parameter first). You'll need to update Ahoy.js to add a `referrer` option to the `configure` method, which I'll happily accept a PR for.
