### ISSUE TITLE
Does not track visits, Rails 5

### ISSUE THREAD

**Issue by twist900** [ankane/ahoy#260]
Does not track visits and events after installation. Only if I call explicitly `ahoy.track_visit` in a controller action it will add a record to the visits table. Is this the intended behaviour for rails or it should track all page visits by default?

**Comment by twist900** [comment]
And it doesn't save a new Visit record when I change user. I use Devise.

**Comment by ankane** [comment]
Hey @twist900, Ahoy has been tested with Rails 5, so I'd double check you followed all the installation instructions if you're not seeing visits. There's no automatic event tracking out of the box. See https://github.com/ankane/ahoy#how-it-works for ways to set that up.

**Comment by apetrov88** [comment]
I'm experiencing the same issue.. I need to explicitly call ahoy.track_visit in a controller to get the visit in the database. Rails 5.0.2, Ahoy 1.5.5
