### ISSUE TITLE
RuntimeError Adapter not supported Sqlite

### ISSUE THREAD

**Issue by newterminator** [ankane/ahoy#261]
I put the following two lines in my Posts controller:
`ahoy.track "Viewed post", post_id: @post.id`
`@count = Ahoy::Event.where(name: "Viewed post").where_properties(post_id: @post.id).count`

And I get the **RuntimeError** error for the second line: **Adapter not supported: sqlite**
_Rails Version: 5.0.2_
_Ahoy Version: 1.5.4_

Any help with this issue will be appreciated.

**Comment by ankane** [comment]
Hey @newterminator, the `where_properties` feature doesn't work with SQLite.

**Comment by newterminator** [comment]
Hey @ankane , thank you for replying. 
So I will go with either PostgreSQL or MySQL. Could you please inform if it will work with either of those two.

**Comment by ankane** [comment]
Yep, works with both of those.

**Comment by newterminator** [comment]
Perfect. Thanks again!

**Comment by brandnamewater** [comment]
not sure if this alerts you guys on a comment but if so, what is the alternative for sqlite? How can i have the same feature (finding by property) but in sqlite?

**Comment by ankane** [comment]
Hey @brandnamewater, you'd need to dig into the code and write it yourself.
