### ISSUE TITLE
stores:custom & stores:log gives conflict warning

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#263]
When I run `rails generate ahoy:stores:custom` or `rails generate ahoy:stores:log` I get this line:

```
Running via Spring preloader in process 1496
    conflict  config/initializers/ahoy.rb
Overwrite /Users/David/Desktop/project/config/initializers/ahoy.rb? (enter "h" for help) [Ynaqdh] n
```

Why is that and what can I do?

**Comment by ankane** [comment]
Hey @Rubioli, this happens when you have an existing `config/initializers/ahoy.rb`. If you don't need the existing one, say `Y` to overwrite it.
