### ISSUE TITLE
How can I add ahoy_events & Visits only to one action

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#264]
Currently I can see that `ahoy` track all my views and controllers. How can I make Ahoy to only track one given controller only?

Thanks in advanced!

**Comment by ankane** [comment]
Hey @Rubioli, what have you tried?

**Comment by Rubioli** [comment]
@ankane What I have tried unitl now was to add `ahoy.track "Viewed book", title: "Hot, Flat, and Crowded"` in only one action, but I still get the whole site, like homepage etc.

Hope you can help me out

**Comment by ankane** [comment]
Hey @Rubioli, not sure I follow. Ahoy doesn't track any events by default, so you likely added code that's doing it.

**Comment by Rubioli** [comment]
Hello again, @ankane Sorry for late reply. I was going to do some tests to be sure I haven't added some extra things.

You mentioned 

> Ahoy doesn't track any events by default, so you likely added code that's doing it

I started a whole new rails installation & did the following:
*1)* Added `gem "ahoy_matey"` to my *Gem File* and ran `Bundle install`
*2)* Added `//= require ahoy` & `//= require jquery` to my `application.js`
*3)* Ran `rails generate ahoy:stores:active_record` and added new tables to my database by running `rake db:migrate`.

At this point, I didn't do anything else and reloaded one of pages *(Dashboard page)* and see that it was added to `visits` table.

So as I can see it `ahoy gem` tracks all events/visits in my application. I only want to track events on only one action in my whole application.

Hope you can help me out :)

**Comment by ankane** [comment]
Hey @Rubioli, if you only include the `ahoy.js` JavaScript on `posts#show`, that's the only page it will track visits on.

**Comment by Rubioli** [comment]
Hey @ankane Thanks for your reply.

I removed `//= require ahoy` from `application.js` & downloaded `ahoy.js` and only included it to the view I want to track visits, but I still see other pages on my platform still being tracked and create visit.

Basically what I'm trying to do is to only create visits on one action/view in my whole platform.

Thanks for your helo :)

**Comment by dan3lson** [comment]
Skip the visit-creation in your ApplicationController and then enable it in the lone controller action you want to track.
