### ISSUE TITLE
New Visit is not created after an user logout and login as a different user from the same browser session

### ISSUE THREAD

**Issue by MyExperiments** [ankane/ahoy#265]
Ahoy is a great gem for tracking user actions. Thanks for the team for the wonderful gem.

I had noticed an issue that when a user logout and login again as a different user, a new visit is not created. It uses the visit of the previous user. 

Any help will be appreciated.

Thanks,
Sufinsha

**Comment by ankane** [comment]
Hey @MyExperiments, you can delete the `ahoy_visit` cookie on login or logout if you want to force a new visit.

**Comment by MyExperiments** [comment]
@ankane I had tried setting the ahoy_visit cookie to nil. But It will not create a new visit right from the next request. Instead, a new visit is created after 3rd request.

**Comment by MyExperiments** [comment]
Is there any alternative for ahoy.reset() in ruby?

**Comment by ankane** [comment]
`ahoy.reset()` simply deletes cookie, so you can do the same thing in Ruby.

https://github.com/ankane/ahoy/blob/83e1126a257b3f33b1fd27fecb93765822ec1c42/vendor/assets/javascripts/ahoy.js#L277
