### ISSUE TITLE
Duplicate record event on same page.

### ISSUE THREAD

**Issue by RathanakSreang** [ankane/ahoy#266]
I use ahoy to track when users visit my page.
However, there is a problem when visitor visit then reload page ahoy also record this event.
What I want to do is record event when first view page, or in some amount of time like `30.minutes`.
How can I do that?

**Comment by ankane** [comment]
Hey @RathanakSreang, what have you tried?

**Comment by RathanakSreang** [comment]
@ankane 
I do follow this https://github.com/ankane/ahoy#ruby
And I put it in after_action like this:

```ruby
class PostsController < ActionController::Base
  after_action :track_action

  protected

  def track_action
    ahoy.track "Viewed #{controller_name}##{action_name}"
  end
end
```

**Comment by ankane** [comment]
It looks like you've set up `ahoy.track` to be called for each action. How have you tried to limit it to one event every 30 minutes?

**Comment by ankane** [comment]
Cleaning up stale issues
