### ISSUE TITLE
Mongoid write issues

### ISSUE THREAD

**Issue by lgelfan** [ankane/ahoy#271]
Hoping someone can help - I have limited experience with Rails, trying to set up Ahoy as a stand-alone web service and having trouble getting it to work with Mongo. It works fine with Postgres/Active Record. The mongoid models get created, I just don't see any writes to the db.

Not sure if there is something I'm missing when switching to Mongoid - I'm using the visit and events endpoints via the js library. The routes work (data is being sent and the visits response looks correct: `{"visit_id":"22434478-e198-4fb1-a4cf-728580e02521","visitor_id":"bfe0fbca-a714-4b92-b9c9-23bdcf67460b"}` ). The events endpoint looks like it does query the mongo db, but I don't see any write requests. This is the console output:

```
Started POST "/ahoy/visits" for 172.30.0.1 at 2017-04-26 22:33:37 +0000
Completed 200 OK in 179ms (Views: 1.2ms)

Started POST "/ahoy/events" for 172.30.0.1 at 2017-04-26 22:33:38 +0000
D, [2017-04-26T22:33:38.934234 #1] DEBUG -- : MONGODB | db:27017 | ahoy.find | STARTED | {"find"=>"visits", "filter"=>{"_id"=><BSON::Binary:0x69844188100600 type=uuid data=0x3232343334343738...>}, "limit"=>-1, "sort"=>{"_id"=>1}}
D, [2017-04-26T22:33:38.935651 #1] DEBUG -- : MONGODB | db:27017 | ahoy.find | SUCCEEDED | 0.001054142s
Completed 200 OK in 9ms (Views: 0.4ms)
```

Any suggestions would be appreciated.

**Comment by Startouf** [comment]
Hey did you try to update the gem version ? I remember having a similar problem and after reading the changelog I noticed one version fixed a bug of events not being tracked.

**Comment by ankane** [comment]
Cleaning up stale issues. Thanks for the assist @Startouf 👍
