### ISSUE TITLE
What is difference between Ahoy_events & Visits?

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#273]
What is the main differences between `ahoy_events` & `visits` and what is purpose of each of them?

When a `ahoy_events` is added and when `visits` are added? Because I see some `ahoy_events`, without `visit_id`, so what are those?

When using Chart to grab and show data to user, which one we need to use `ahoy_events` or `visits`?

**Comment by ankane** [comment]
Hey @Rubioli, see the "How It Works" section of the readme, or try it out yourself.
