### ISSUE TITLE
Validation failed: Visit must exist

### ISSUE THREAD

**Issue by jfrankov** [ankane/ahoy#276]
I just installed ahoy on a rails 5 project, added this line to the create action of my controller:

    ahoy.track "Created an action", title: "Call"

and I get "Validation failed: Visit must exist". My visit.rb model already has this line in it:

    belongs_to :user, optional: true

...so that might not matter.

Any ideas?

**Comment by ankane** [comment]
Hey @jfrankov, you can add `optional: true` to `belongs_to :visit` to fix the error. However, it's not ideal having events that don't have a visit. One option is to have Ahoy create a visit if there isn't already one.

**Comment by jfrankov** [comment]
Thanks for the reply. I'll play with it some more.

**Comment by skunkworker** [comment]
I just had this issue and modifying `event.rb` to have:

```ruby
    belongs_to :visit, optional: true
    belongs_to :user, optional: true
```

fixed it for me. Ruby 2.4.1, Rails 5.1.1 & ahoy_matey 1.6.0

**Comment by mitki** [comment]
@ankane I think it's caused because there's no visit at the time when `after_action :track_action` (from the README example) is called for the first time.

**Comment by edusantana** [comment]
Same thing happened with me.

**Comment by joshuajansen** [comment]
Same here, couldn't figure out what was causing this.. Eventually I went for calling the following method `before_action`:

```ruby
def ensure_visit
  return if ahoy.visit
  ahoy.track_visit
end
```

**Comment by wangthony** [comment]
Are you using visitable? You should be able to call `visitable optional: true` in your model.

However, there is a bug in Ahoy::Model#visitable that causes this for me:

```
def visitable(name = nil, options = {})
  if name.is_a?(Hash)
    name = nil
    options = name     # <---- will always be nil - this line should be switched with the previous line
  end
```

The workaround is to call `visitable :visit, optional: true` or `visitable nil, optional: true`

**Comment by mikgry** [comment]
I have the same issue. IMO `visitable :visit, optional: true` is not good solution. Why is there missing visit?

**Comment by mikgry** [comment]
#240

**Comment by ankane** [comment]
Ahoy 2.0 (just released) attempts to create a visit if one doesn't exist before creating an event, which should fix this. You can do this in Ahoy 1 with:

```ruby
class Ahoy::Store
  def track_event(name, properties, options)
    ahoy.track_visit unless visit
    super
  end
end
```
