### ISSUE TITLE
Set additional fields to visits (have the answer, just wonder if way I did it, is right way to do)

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#277]
My application only adds visits from `posts#show`. When a visit is tracked I want to have my posts id in my visit *row*.

I have added `post_id` to `visits`:
`add_reference :visits, :post, index: true, foreign_key: true`

*This is how my `Visit` model looks like:*
```
class Visit < ActiveRecord::Base
  has_one :ahoy_events, class_name: 'Ahoy::Event'
  belongs_to :user
  belongs_to :post, :counter_cache => true

  before_save :set_additional_fields
  def set_additional_fields
    uri = self.landing_page
    a = URI(uri).path.split('/').last
    self.post = Post.find_by_slug(a)
  end
```

*& my `Post` model:*
```
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_random_characters, use: [:slugged, :finders]
  def slug_random_characters
    o = [('a'..'z'), ('0'..'9')].map(&:to_a).flatten
    (0...8).map { o[rand(o.length)] }.join
  end

  has_many :visits

end
```

*My `PostsController`:*
```
def track_action
    ahoy.track "Viewed post", id: @post.id
end
```

I'v tried to get the `post_id` by searching through `slug` and changed how `landing _page` would be *(not sure its a good practice)*

```
before_save :set_additional_fields
def set_additional_fields
  uri = self.landing_page
  a = URI(uri).path.split('/').last
  self.post = Post.find_by_slug(a)
end
```

This got the `post_id` and added it to `visits`. So my question is if the way I did it, is good way or there is a better way to do this?

Thanks in advanced!

**Comment by chalmagean** [comment]
You could do something like this:

_app/models/ahoy/visit_properties_extension.rb_
```
Ahoy::VisitProperties.class_eval do
  RESOURCE_KEYS = [:page_id]

  KEYS = self::KEYS + RESOURCE_KEYS

  delegate(*RESOURCE_KEYS, to: :resource_deckhand)

  def keys
    if Ahoy.geocode == true
      KEYS
    else
      KEYS - LOCATION_KEYS
    end
  end

  protected

    def resource_deckhand
      @resource_deckhand ||= ::Ahoy::Deckhands::ResourceDeckhand.new(request_deckhand.landing_page)
    end
end
```

_app/models/ahoy/deckhands/resource_deckhand.rb_
```
module Ahoy
  module Deckhands
    class ResourceDeckhand
      def initialize(url)
        @page_url = url
      end

      def page_id
        url = Addressable::URI.parse(@page_url) rescue nil
        Alchemy::Page.find_by(urlname: url.path.slice(1..-1)).try(:id) if url
      end
    end
  end
end
```

Which will produce something like this:
```
select id, landing_page, page_id from visits;
 id |        landing_page         | page_id
----+-----------------------------+---------
  7 | http://localhost:3000/foo   |       3
```

**Comment by Rubioli** [comment]
Thanks a for your answe @chalmagean 

I added your code to my application and created `app/models/ahoy/visit_properties_extension.rb` & `app/models/ahoy/deckhands/resource_deckhand.rb` & removed  my code from `visit.rb`, but `post_id` is empty.

Maybe I've done some parts wrong. Do I need to add anything in my `Visit.rb`?

Appreciate any help :)

**Comment by chalmagean** [comment]
Well... there are two things here:

1. If you really need to add a `post_id` to a visit, then you probably need to fetch that `post_id` differently than I'm fetching `page_id`, since my example shows how you would do that using AlchemyCMS.

2. If you want to record each page visit (as in the same user clicking multiple pages), I think `Visit` is not the object you want. You should probably store it in `Ahoy::Event` as part of it's properties field.

**Comment by Rubioli** [comment]
Thanks @chalmagean 

In my application Im not using Ahoy events that much (or at all). I've built the functions based on ahoy visits. My application is a application where you put your link there and other users view your link and based on what country they are from and other details, I need to add balance and credit to each user.

Thats why I use ahoy visit and track almost everything based on each visit. That being said reason I need to fetch `post_id` is to show which link user been visiting.

They way I do currently, is it a bad practice? and would it be slower?

**Comment by chalmagean** [comment]
I see. Well, `Visit` fires only once for each user. So if the user visits the same url two times (in 30min, by default) you will only get one visit.

It depends on your application, but I don't see why it would be a bad practice. Nor do I think it to be slower.

**Comment by Rubioli** [comment]
Yeah the 30 min wait is exactly what I need.

Okei. I thank you so much for your answers.

Appreciate your help! :)
