### ISSUE TITLE
Mongoid Tracking crashes with embedded documents - suggestion to move from Hash field to "PropertySet" embedded_document 

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy#279]
I have the following tracker code in my controller

```
ahoy.track('Company registration',
      name: @company.name,
      subscription: @company.subscription,
)
```

My subscription is actually an embedded document embedded in the company model

The tracking code calls mongoid #upsert and in turn #as_document which converts to a document like this

```
{
           "_id" => <BSON::Binary:0x70113746711320 type=uuid data=0x6238653663333938...>,
      "visit_id" => <BSON::Binary:0x70113746710900 type=uuid data=0x3061366236633763...>,
       "user_id" => BSON::ObjectId('xxx'),
          "name" => "xxx",
    "properties" => {
                "name" => "xxx",
        "subscription" => #<Payment::Subscription:0x007f893d7d2080> {
                   :_id => BSON::ObjectId('xxx'),
             ...
        },
```

I do not know if I am expected to call #as_document myself or if this should be handled by default

EDIT : I also opened an issue in the Mongoid JIRA tracker in case 

Link : https://jira.mongodb.org/browse/MONGOID-4437

**Comment by Startouf** [comment]
A suggestion from the MongoDB team would be to use a nested document for the properties hash

This would bring the following changes to the template

```
class Ahoy::Event
  include Mongoid::Document

  # associations
  belongs_to :visit
  belongs_to :user

  # fields
  field :name, type: String
  field :properties, type: PropertySet
  field :time, type: Time
end
```

And we'd need to add an extra Property class that could hold anything like a Hash, but would serialize better

```
class Ahoy::Mongoid::PropertySet # (class name to define)
  include Mongoid::Attributes::Dynamic
end
```

@ankane was there a particular reason you used a Hash instead of a nested document ? 

Such a change is likely to require a small Mongoid "migration" since old Event document properties would have been persisted without an "ID" and I'm not sure how Mongoid would understand that, but otherwise it shouldn't break any existing application.

**Comment by ankane** [comment]
Hey @Startouf, thanks for the suggestion 👍  I'd recommend serializing objects before passing them to Ahoy. It's not really designed for embedded objects.
