### ISSUE TITLE
Ahoy matey slower rails app

### ISSUE THREAD

**Issue by adamlglover** [ankane/ahoy#280]
This isn't necessarily an issue but is there a way to make my rails app faster when tracking all events with Ahoy?

**Comment by ankane** [comment]
Hey @adamlglover, not sure I follow the question. Tracking events will always be a bit slower than not tracking events. Are there specific bottlenecks you're seeing?

**Comment by adamlglover** [comment]
Yes, I knew that it would be a bit slower to track all events and visits but sometimes it seems exponentially slower and sometimes pages wouldn't even load.

Maybe it is important to add that I am using cloud9 in development mode chartkick to visualize the results (great gem btw).

I was drawn to ahoy because I wanted a built-in event tracker for a rails app (not google analytics) but I'm worried that it's going to be too slow to use. Any advice?

**Comment by ankane** [comment]
I'd try to figure out the exact bottleneck. Ahoy shouldn't cause timeouts.

**Comment by adamlglover** [comment]
Wow, put the Ahoy javascript after the body instead of before. Seems to have done the job.
