### ISSUE TITLE
Kinesis to Redshift

### ISSUE THREAD

**Issue by cmalpeli** [ankane/ahoy#282]
Curious if anyone here has used this to push to Kinesis and then Redshift?  I see Kinesis is a supported destination - but wonder if anyone has put together a tutorial on the full process? Thanks!

**Comment by cmalpeli** [comment]
Specifically, when you send data from Kinesis to Redshift,  you need to specify a table in Redshift.  What should the scheme of that table look like?

![image](https://cloud.githubusercontent.com/assets/900950/26315488/4ddbc94c-3edf-11e7-8671-0779f6ec2967.png)

**Comment by cmalpeli** [comment]
Nevermind, sorted this out.

**Comment by ankane** [comment]
Hey @cmalpeli, glad you figured it out. Maybe you could create a tutorial for others :)

**Comment by cmalpeli** [comment]
Will do!
