### ISSUE TITLE
Multiple user types with Devise?

### ISSUE THREAD

**Issue by cmalpeli** [ankane/ahoy#283]
I see this integrates directly with Devise which is create.  Our app is a little unique in that we have two User Models:

`current_profile`
`current_employer`

Can we configure Devise to pick up on either of these?

Also - does Devise not work with the Kinesis store?  Since there is no actual Model for Kinesis, and it's simply passing the JSON to Kinesis, is there a way to customize what you are passing to Kineses (i.e. custom fields on visit/events).

**Comment by ankane** [comment]
Hey @cmalpeli, see the section labeled "Customize User" in the readme.

Re Kinesis: Devise works with Kinesis the same way it does with other stores. If you want to customize what gets shipped to Kinesis, try creating a custom store based off the Kinesis store in the source code.

**Comment by cmalpeli** [comment]
thanks @ankane!  I would up doing this in case anyone finds it useful:

```
def track_visit(options)
    super do |data|
      data[:profile_id] = controller.current_profile.id if controller.current_profile
      data[:employer_id] = controller.current_employer.id if controller.current_employer
      data[:started_at] = DateTime.now.strftime("%Y-%m-%d %H:%M:%S")
  end
end
```

**Comment by ankane** [comment]
Thanks for sharing how you solved it for others @cmalpeli 👍
