### ISSUE TITLE
Todo question: Dashboard?

### ISSUE THREAD

**Issue by kyleschmolze** [ankane/ahoy#286]
I'd be happy to take up building a basic Ahoy dashboard, but my use cases are more towards something like Mixpanel's dashboard:

- Ability to view graphs of events over time, filter by date, uniques/total count, and event properties. 
- Ability to view funnels of multiple events, tracking conversion rates. 
- Ability to create dashboards and add graphs / funnels to them.

If I only have the know-how to build this for Postgres, would it be considered for merging? Or should I just create my own gem? Is this what you're looking for, or were you thinking more of a real-time stream @ankane?

Thanks for the great libraries!

**Comment by ankane** [comment]
Hey @kyleschmolze, a Mixpanel-style dashboard would be great. I typically use [Blazer](https://github.com/ankane/blazer) for charts and dashboards, but it currently requires manual set up and isn't geared specifically towards user analytics. It's probably best to create a separate gem.

**Comment by djsegal** [comment]
You guys should do this. That would be awesome

Maybe you can build it on administrate or another CMS gem?

**Comment by kyleschmolze** [comment]
I'm planning for it to be a standalone gem to reduce dependencies. Have started, but haven't had much time in recent weeks. 

The only thing I'm struggling with is finding a good way to gather all keys in the json column. I feel like the dashboard wouldn't be very useful unless you could filter by the extra data in the `properties` json column, which means having an interface for browsing keys/values of the json, and there doesn't seem to be great support for browsing that info within postgres.

**Comment by omricohen** [comment]
Awesome @kyleschmolze!  Have you started working on this? I'd love to use this or help build if I can...

**Comment by kyleschmolze** [comment]
Hey @omricohen sorry for the delay there - I just got back to work on this project yesterday. I've got a super-preliminary prototype that works in a basic setup for some basic graphing functions: https://github.com/kyleschmolze/ahoy_dashboard

Let's chat over there if you want to help out!

**Comment by ankane** [comment]
Going to close this issue. Looking forward to seeing how it turns out.
