### ISSUE TITLE
Background Geocoding broken with Mongoid

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy#287]
When enabling background tracking with Mongoid, the dat gets badly serialized as a BSON::Binary object without its ID data attribute.

Here is what a Visit id currently looks like (I still don't get why IDs are `BSON::Binary` instead of `BSON::ObjectID`, any light on this @ankane ?)

    <BSON::Binary:0x45977960 type=uuid data=0x6434656664386137...>

The important part is the `bson_binary.data` attribute that is the object ID.

When setting geocoding to async `Ahoy.geocode = :async`, the following job gets serialized without the data attribute
```
{ 
  "job_class":"Ahoy::GeocodeJob",
  "job_id":"ebeb3ea8-5d43-43e9-8c8f -fb0b51f50b67",
  "queue_name":"MyJobGlasses_production_tracker",
  "priority":null,
  "arguments":[
    {"_aj_globalid":"gid://my-app/Visit/%23%3CBSON%3A%3ABinary%3A0x007efc4a9c0098%3E"}],"locale":"fr"}
```
which results in the following crash 

> Document(s) not found for class Visit with id(s) #<BSON::Binary:0x007f8437ae3090>.

as the data attribute is not restored

**Comment by Startouf** [comment]
When digging, there is this line of code in https://github.com/ankane/ahoy/blob/master/lib/ahoy/stores/mongoid_store.rb#L7

```ruby
v.id = binary(ahoy.visit_id)
```

And the code for the binary generation

```
def binary(token)
        token = token.delete("-")
        if defined?(::BSON)
          ::BSON::Binary.new(token, :uuid)
        elsif defined?(::Moped::BSON)
          ::Moped::BSON::Binary.new(:uuid, token)
        else
          token
        end
      end
```
@ankane is there a particular reason for using a binary ID instead of using MongoDB's native ID generation (or a custom ID) ? This causes the serialization bug mentioned above. My whole background geocoding tracking is on hold because of this, is a monkeypatch to avoid setting the ID this way going to work or is it going to mess some other part of ahoy ?

**Comment by Startouf** [comment]
@ankane I'd really like if you could tell me about this. I just need to know if there was a particular reason or if I can switch to using a normal MongoID, thanks

> Is there a particular reason for using a binary ID instead of using MongoDB's native ID generation ? This causes the serialization bug mentioned above. Mongoid background geocoding is broken because of this. Is it possible to patch it to use a normal MongoID or is it going to mess some other part of ahoy ?

**Comment by ankane** [comment]
Hey @Startouf, Ahoy is data store agnostic, so UUIDs are generated outside any data store. Feel free to fork and update as you wish.
