### ISSUE TITLE
Where to view rails generated tracking?

### ISSUE THREAD

**Issue by djsegal** [ankane/ahoy#290]
For example,

I have this js:

```
ahoy.trackAll();
```

and this rails:

```
class ApplicationController < ActionController::Base
  after_action :track_action

  protected

    def track_action
      ahoy.track "Viewed #{controller_name}##{action_name}"
    end
end
```

-----------

so questions for the `track_action` function in the rails controller:

+ where does the data from `ahoy.track` go? 
+ where is the code for the `ahoy` object that calls `track`?

**Comment by djsegal** [comment]
also, how do you test that the rails is up and running (when the javascript is also active)?

**Comment by ankane** [comment]
Hey @djsegal, you should be able to see what Ahoy is doing in `track_action` from the logs. Also, the interesting code is in the `lib` folder.
