### ISSUE TITLE
[Postgres] how to use uuid column for visitor_token and visit_token type if I already use pg_crypto ? 

### ISSUE THREAD

**Issue by kofronpi** [ankane/ahoy#292]
Hello,

I'm considering using Ahoy. Great work from what I can read in the source;

For various reasons ([https://stackoverflow.com/questions/32189129/performance-difference-between-uuid-char-and-varchar-in-postgresql-table](url)) I don't want to store uuid in string columns, and I already use the `pg_crypto` extension with postgres. What code do I need to override or configure if I want to use native uuid columns with `gen_random_uuid()` as a default ?

Thank you !

Edit : I can successfully use uuid as columns, that's already good enough. However I was also wondering if I can drop the dependency on the uuid gem when postgres is good enough for managing uuids. Maybe I'm just being very picky here !

**Comment by ankane** [comment]
Hey @kofronpi, glad it's working 👍  We'll still need the uuidtools dependency since Ahoy supports more than just Postgres.

**Comment by kofronpi** [comment]
Hey @ankane, yeah I figured that out a little while later. Thanks for your answer 👍
