### ISSUE TITLE
`visitable` will not accept options, unless the name is given

### ISSUE THREAD

**Issue by fruwe** [ankane/ahoy#293]
If you just call visitable with options like this:

`visitable :visit, inverse_of: :orders, optional: true`

name and options with be set to nil as you can see in the following snippet.

```
module Ahoy
  module Model
    def visitable(name = nil, options = {})
      if name.is_a?(Hash)
        name = nil
        options = name
      end
```

It should be:

```
      if name.is_a?(Hash)
        options = name
        name = nil
      end
```

**Comment by ankane** [comment]
Coding fail, nice catch @fruwe 👍
