### ISSUE TITLE
Ahoy & Sidekiq

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#295]
I want to add only visits to `sidekiq`. Is there any doc so I can look over and whats the best way to do this?

Any help is appreciated!

**Comment by ankane** [comment]
Hey @Rubioli, can you explain more? Not sure I understand what you're asking.

**Comment by Rubioli** [comment]
Thanks for reply @ankane.

I'm setting up redis & sidekiq to my application and adding some parts of my application as workers.

For instance I managed to add `ahoy_events` as worker by doing:

```
class EventWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'Events'

  def perform(post_id)
    post = Post.find(post_id)
    ahoy.track "with sidekiq", id: post.id
  end
end
```
In my `PostsController`
```
def show
    EventWorker.perform_async(@post.id)
end
```

This works fine and I can see `ahoy_events` is my queue in `Sidekiq` WebUI.

`ahoy_events` was easy to add as `Worker` since I could use `ahoy.track` in my `EventWorker`, but I can't see anything for `visits`. 

What Im wondering is how to create a `Worker` for visits too and add visits to my queue in `Sidekiq` as well.

Appreciate your help.

**Comment by wittawasw** [comment]
@Rubioli Unfortunately, right now there's no simple way to just delegate ```ahoy.track_visit``` to Sidekiq since it used the immediate ```controller``` object to calculate most of the attributes. 

If you really need it, you might try sending some parameters from ```request``` or  ```controller``` such as ```remote_ip```, ```referer``` and use ```Ahoy::VisitProperties``` to generate some attributes in the worker.

This feature could be a big improvement if done right.

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by KevinColemanInc** [comment]
I am using GraphQL for my API and that only uses 1 controller action for basically everything, so a lot of the benefits of `ahoy` as mentioned above, are lost.

I also want to have tracking of events to background workers.  There definitely is no interface or stub I could use for an event tracking?
