### ISSUE TITLE
Rails 3 Compatibility?

### ISSUE THREAD

**Issue by proteantech** [ankane/ahoy#296]
I am trying to use ahoy with a Rail 3.2.22 project. Is ahoy compatible? I didn't see anywhere in the documentation where it says what versions of Ahoy support which of Rails, nor in the gemspec. 

I tried it and it seems to be working on the front-end, but the POSTs are not materializing into DB records. I checked the route doing a, Rails.application.routes.recognize_path 'ahoy/events and it is not finding a valid route, so I am guessing the POSTs are just being dropped and never making it to the Ahoy controller that saves them in the DB (using MySQL btw).

Also, it looks like bundler pulled ahoy 1.5.4.

**Comment by ankane** [comment]
Hey @proteantech, I'm currently only supporting Rails 4.2+ right now.

**Comment by proteantech** [comment]
What is the last version to support rails 3?

**Comment by proteantech** [comment]
Just as an FYI. I was able to get 1.5.4 with Rails 3. The only thing I needed to do that wasn't in the documentation was mount the engine in the routes file. I think this is needed for any version of Rails and would probably be helpful to put in the README on the main git page.

**Comment by patakijv** [comment]
@proteantech - curious if you are indicating that the current version (1.6.0 at this writing) does not work with Rails 3.2 but the older version 1.5.4 does? Or if there is something that can be done to get the current version working from your experience on 1.5.4? I am about to start trying to implement this on a Rails 3.2 project.

**Comment by proteantech** [comment]
I didn't try 1.6. it would probably work though.

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by darrenterhune** [comment]
IF you are using Postgres, I was able to get this working with a Rails 3.2 project by doing this:

```ruby
# Gemfile (this allows migrations to work using :jsonb column type per the default migration file generated by ahoy)
gem 'activerecord-postgres-json',   '~> 0.2.1'

# ahoy/event.rb
serialize :properties, ActiveRecord::Coders::JSON
```
I'd assume it would be easy to write your own `active_record` extensions to work with mysql by using `activerecord-postgres-json` as an example.
