### ISSUE TITLE
Multiple stores 

### ISSUE THREAD

**Issue by Fodoj** [ankane/ahoy#297]
Is it possible to send every event to two different stores? I want to send them both to PostgreSQL and Intercom :-)

**Comment by ankane** [comment]
@Fodoj yes, you can use a custom store, or override methods of the Postgres store.

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore
  def track_visit(options)
    super # sends to Postgres

    # add code to send to intercom here
  end

  def track_event(name, properties, options)
    super # sends to Postgres

    # add code to send to intercom here
  end
end
```

**Comment by Fodoj** [comment]
Hmm, okay, this is a bit hacky in my taste. Do you think supporting multiple stores 2+) at once is something that could be implemented in future? I could help with that .

**Comment by ankane** [comment]
I'd be curious to hear how you'd do it. Happy to consider it for Ahoy 2.

**Comment by Startouf** [comment]
I suppose to dispatch events you'd rather use something like segment if you have more than one target destination (that includes third parties)

You can also use ActiveSupport::Instrumentation if you need to register several observers for one action/event

If you need flexibility, best remains to have some PORO. In my current app, I have some tracker classes responsible for event tracking, and in each tracking method I can decide to send the event to ahoy, intercom, slack. etc. with custom code

There's also rack_tracker which was designed to inject trackers inside the html

**Comment by ankane** [comment]
Cleaning up issues
