### ISSUE TITLE
Handle custom fields to Ahoy::Event model

### ISSUE THREAD

**Issue by gualopezb** [ankane/ahoy#298]
I am using MongoDB as data storage, furthermore I executed `rails generate ahoy:stores:mongoid`. It correctly generated the Ahoy::Event model with it's fields (`name`, `properties`, `time`) and it's associations (`visit` and `user`). I need to add an extra field to the model. My doubt is: Should I customize the `Ahoy::EventsController#create` to add this field to the event record? Or is there an alternative to do that?
**Note**: I can't add this field within the `properties` field, because this value comes from the cookies.

**Comment by ankane** [comment]
Hey @gualopezb, this is what Ahoy::Store is built for (use the track_event method in this case).

**Comment by gualopezb** [comment]
@ankane thank you for your clarification.
