### ISSUE TITLE
No Geo data showing in Visits

### ISSUE THREAD

**Issue by fatfrog** [ankane/ahoy#301]
Rails: 5.1.2 / Ruby 2.3.3

All data is showing in my visits table except for geolocation data which are all null.  Are there any troubleshooting tips you can suggest?  I tried v.set_location and got:

`NoMethodError: undefined method `set_location' for #<Visit:0x007fd94bbbb990>`

But that suggestion was from 2014 so I'm not sure if its still relevant?

Thanks!

**Comment by fatfrog** [comment]
This turned out to be an issue with Geocoder, I followed these instructions and everything works now:
https://github.com/alexreisner/geocoder/issues/1174#issuecomment-301799340

**Comment by ankane** [comment]
Hey @fatfrog, glad you figured it out.
