### ISSUE TITLE
Question: how background works?

### ISSUE THREAD

**Issue by Fodoj** [ankane/ahoy#302]
I know geocoding can be sent to background. What abount creation of events itself? Thing is I send events to multiple stores at once now, one stores is third party API. Does tracking happen inline? I am afraid that if this third party API is down then my whole app will be down :)

**Comment by ankane** [comment]
Hey @Fodoj, you can customize your `Ahoy::Store` to kick off background jobs as needed.

**Comment by Fodoj** [comment]
So I would have to do something like:


```ruby
def track_event(...)
  perform_in_background(super)
end
```

right?

**Comment by ankane** [comment]
@Fodoj You'd need to create a background job in your app and call that.

**Comment by Fodoj** [comment]
Would it make sense to wrap event saving into background job automatically (if this option is enabled)? So that when we call ‘track’ it will create background job instead of creating a new event

**Comment by ankane** [comment]
Hey @Fodoj, sorry for the delay. Which option are you referring to?

**Comment by Fodoj** [comment]
Ok, so let's say I have custom store that wraps API. Every time Ahoy is invoked it will pause to do API request - not good. Currently I will have to implement a new ActiveJob  to wrap these API calls and trigger a job in `track` method. What I am proposing is to make this invisible to end user - ahoy would wrap events tracking into ActiveJob automatically, given an option like "process_in_backgorund" is enabled. Does it make sense?

**Comment by ankane** [comment]
It sounds like you're proposing a new option? When customizing a store, creating a job should only be a few lines of code, so think we can leave that to developers.

**Comment by chrisedington** [comment]
@Fodoj did you ever manage to do this?
