### ISSUE TITLE
Session duration

### ISSUE THREAD

**Issue by Alagaesia93** [ankane/ahoy#303]
Hi guys! 

thank you for this awesome gem! 💯 

Two questions (maybe useful in README)

I need to track how long a users remains on my website: visit.started_at is the beginning, but the end? I could use its last ahoy_event.time, other ideas? 

If today I visit my website, I don't sign up. Few days later I visit again and I sign up. Does ahoy recognize it's the same visitor? 

Thank you very much!

**Comment by ankane** [comment]
Hey @Alagaesia93, to answer your questions:

1. The last event ahoy_event.time should be fine. Another approach would be to store a field on visit for this that you continuously update.
2. Yes, the visitor_id/visitor_token will be the same.
