### ISSUE TITLE
Why the Visit model is in the root app folder and the Event model is scoped under the ahoy module?

### ISSUE THREAD

**Issue by pazaricha** [ankane/ahoy#304]
Hey,

First off, awesome gem :) A true life & time saver.

I was wondering why does the visit model (`Visit`) is a stand-alone "root model" and the event model (`Ahoy::Event`) is scoped under the ahoy module? I would expect the visit model to be scoped under ahoy as well.

Just looked wired to me when first installing the plugin? is there any reason behind it and if not will be happy to create a pull request for it. 👍

**Comment by ankane** [comment]
Hey @pazaricha, I agree it makes sense to be consistent. Since this is a breaking change, it's probably best to hold off until Ahoy 2.0. I've added it to the plan: https://github.com/ankane/ahoy/issues/164

**Comment by ankane** [comment]
Thanks!
