### ISSUE TITLE
Ahoy.track_visits_immediately causes server-only side visit creation with not all attributes tracked (automatically).

### ISSUE THREAD

**Issue by patakijv** [ankane/ahoy#307]
I've been experimenting with using Ahoy on a system where I have both a web browser based app interface and a mobile app that uses an API endpoint. In order to get the API endpoint working as expected and modify the visit details from http parameters on the server side, I had to set `Ahoy. track_visits_immediately` to true. The name of this parameter and the documentation suggests that this is the correct path. 

However, what I have found that is not documented is that when `Ahoy.track_visits_immediately` is true, the browser side of the equation doesn't just _defer_ its tracking of a complete visit record, rather it stops sending requests to the ahoy mount point (i.e. `/ahoy`) to complete the visit record all together (automatically) therefore several of the visit attributes that are normally sent by the callback are now missing for visits from the browser side visits.  If I restart the server app with `Ahoy. track_visits_immediately` set to false, I now start getting visits with more attributes saved to the DB and I notice this is because posts are coming through `/ahoy/visits`.

Is this a correct understanding of this property `track_visits_immediately`? It seems either there is a missing follow up callback to `/ahoy/visits` beyond 'immediately' or this property's name and the documentation is a little misleading. Or am I missing something in my testing that I either haven't yet seen or I still need to do to get the `ahoy.js` to send a callback at some point even when `track_visits_immediately`is set to true?

What is the expected path here when using `track_visits_immediately` set to true to get the full visit details for the browser interface? Is there supposed to be a separate (from the automatic behavior of the gem) forced call to `ahoy.track()` added to each page's js code to make this happen at some other point in the page flow? If so, perhaps the documentation for `track_visits_immediately` should mention this because it is not clear. And if so, what is the recommended point at which to call `ahoy.track()` when  `track_visits_immediately` is true? If it is expected to add a call to `ahoy.track()` I would like to follow a good practice for doing so.

**Update:**

I also notice that `ahoy.track()` doesn't actually send the visit data that is missing, rather it is just for sending events and that `createVisit()` is the only place in the js code that sends the extra data (and only if `track` is true which is true only if `track_visits_immediately` is false) for the visit and that this function is not exposed through the `ahoy` object and that the only exposed function that ever calls `createVisit()` is `ahoy.start()` yet this function is turned into a empty function after the first time it is called! - DOH! It seems there has been a lot of effort targeted at making it so the only way to get the visit data attributes sent for a visit is if you set `Ahoy.track_visits_immediately` to false. Bummer. Seems like either `createVisit()` should be exposed so it is callable on demand or there should be a `trackVisit()` or even a `updateVisit()` function exposed that can be called to send the same data (or more) for the visit that is sent in `createVisit()` when `Ahoy.track_visits_immediately` to false.  There does exist several functions exposed for tracking more 'things' like views, events, clicks, submits, but not visit (rather, no update current visit) that is available outside for calling. 

Still trying to understand if after determining the above, is there some other approach I am missing that allows the use `Ahoy.track_visits_immediately` set to true on the server while also getting all of the visit data that comes along with when that property is false (whether immediately or deferred).

**Comment by ankane** [comment]
Hey @patakijv, your analysis is correct. If `Ahoy.track_visits_immediately` is true, any client-side only attributes are not tracked.

**Comment by ankane** [comment]
Cleaning up stale issues
