### ISSUE TITLE
Add ref to Visit

### ISSUE THREAD

**Issue by mbuckbee** [ankane/ahoy#310]
Something I'm seeing more and more is that sites will reference other sites with the `ref` URL parameter instead of the `utm` variants. 

ProductHunt is a prominent example, but lots of other smaller sites and services are doing it as well. 

This goes way beyond Ahoy, but I think the big thing driving adoption of it as an adhoc standard is how useless the http_referrer has become.

Consider something like Twitter: You post a tweet with a link to your site in it and it's consumed on: a desktop Twitter client like Tweetdeck, Hootsuite web service, Twitter mobile web, Desktop Web, 3rd Party Twitter app like TweetBot, Twitter Mobile but links open in Safari, Twitter mobile but links open in built-in app browser, etc, etc. 

There's also a variety of security and confidentiality concerns that come with http referrer that may end up getting it killed or at least heavily restricted in future browser versions (already Chrome won't pass referrer from https to http sites, and there are a variety of extensions which strip it entirely). 

Adding 'ref' to the Visit model helps ease this situation a bit. It makes it much easier to run a report that answers "All Twitter promo links we put out in the last month, how many visits did we drive?"

It was super easy to put it into my own fork (thanks for all the hard work on Ahoy!), this is just a suggestion that maybe it's something to be added for the next version. 

Again, thanks so much for your open source work!

**Comment by ankane** [comment]
Hey @mbuckbee, thanks for the suggestion 👍  I'm not sure the pattern is popular enough at the moment to warrant building this in, but you should be able to customize your Ahoy store to do this pretty easily.

**Comment by joemasilotti** [comment]
3 years later, is it popular enough to consider adding now?

If not, how can one add it to their own Ahoy store and backfill existing visits?
