### ISSUE TITLE
Precision of visit location coordinates?

### ISSUE THREAD

**Issue by patakijv** [ankane/ahoy#311]
I notice after initial testing that the longitude and latitude values for visits are integers only, no decimal values. Is this a configuration option somewhere to capture a higher precision value for location coordinates?

**Comment by patakijv** [comment]
I've tried adding precision and scale options to the migration to insure the database is able to accept the decimals yet I just get zeros filled up in the decimal places instead of a more precise value.

I've tried calling Geocoder.search(an_ip_address_found_in_visits) directly from the console and I get 4 decimal places for longitude and latitude.

Somewhere between Geocoder and when Ahoy writes to the database, the values are truncated to just the integer value for location coordinates. I've not yet found where this happening.

**Comment by ankane** [comment]
Hey @patakijv, I haven't seen this before. I'd try forking the gem to debug where the problem is happening.

**Comment by ankane** [comment]
Cleaning up stale issues
