### ISSUE TITLE
Capturing incorrect IP address when behind a CDN

### ISSUE THREAD

**Issue by ckorhonen** [ankane/ahoy#312]
We are behind CloudFlare and noticed that the IP's being captured in the visits table actually belong to the CloudFlare edge servers. 

I suspect this is also affecting other users whose site is behind a CDN since `request.ip` does not correspond to the visitors IP address.

Cloudflare passes the real IP address in the HTTP headers -  `request.env['HTTP_CF_CONNECTING_IP']`. In our case I modified `RequestDeckhand#ip`, but wondering what a better solution may be.

```
def ip
   request.env['HTTP_CF_CONNECTING_IP'] || request.remote_ip
end
```

How do you feel about being able to specify a HTTP header in the config and then using that (if present) in place of `request.remote_ip`?

**Comment by ankane** [comment]
Hey @ckorhonen, thanks for the detailed explanation. You should be able to customize your Ahoy store in your app code (see relevant section of readme) to accomplish this without patching the gem itself.

**Comment by achasveachas** [comment]
@ankane I ran into this issue as well.

So to clarify, I would modify my `Ahoy::Store` class as follows?

```class Ahoy::Store < Ahoy::DatabaseStore
  def track_visit(data)
    data[:ip] = request.env['HTTP_CF_CONNECTING_IP'] || request.remote_ip
    super(data)
  end
end```

**Comment by ankane** [comment]
Try it out :)

**Comment by achasveachas** [comment]
@randomm the `HTTP` part of the headers is added by Rails (to distinguish from other headers?) 

`data[:ip] = request.env['HTTP_CF_CONNECTING_IP'] || request.remote_ip` seems to be wroking fine for me.
