### ISSUE TITLE
Event duration

### ISSUE THREAD

**Issue by sintro** [ankane/ahoy#313]
There is duration time for visits, which prevents visits creating by just page refreshing (this is nice).
But it looks like there are no same mechanism for events. Meanwhile this can be usefull also: if we do not want to track event when client refreshes page multiple times (for example if we count page views by using Ahoy Event). Such behaviour of client can be considered as cheating, and we should disable tracking for some time for this event type. If some time passed, for example, 30 minutes, we can enable tracking again.
Of course, we need some scopes to check if it is the same event type as 1 minute ago (and do not prevent tracking of viewing of another page).
For now I can see the implementation of such feature with some global settings for Event model, like
```
class Ahoy::Event 
    duration 10.minutes, scope: [:page_id]
end
```
and the possibility of overriding the default settings in ahoy.track method:
```
ahoy.track 'Page viewed', page_id: @page.id, locale: I18n.locale, duration: 5.minutes, scope: [:page_id, :locale]
```
So the timeout will be counted for same :page_id, but if the user changed his language, event will be tracked.
The problem with last implementation for `ahoy.track` is that we have to reserve `duration` and `scope` keys for the library.
Also I do not cosidering scoping of event title, as I can not imagine where we should prevent of tracking of different event types.
This feature is not the same as Throttling by rack-attack, as it does not consider event parameters and type.

**Comment by ankane** [comment]
Hey @sintro, thanks for the suggestion 👍  There's no built-in way to do this, but you can customize your Ahoy store to accomplish this.

**Comment by sintro** [comment]
Is someone need this. The example shows both adding additional parameter for tracking (before this you need to add integer column 'page_id' to database) and checking for same event in last 3 minutes.
Assuming you use default ActiveRecordTokenStore as store adapter:
#_config\initializers\ahoy.rb_
```
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore
  def track_event(name, properties, options)
    if name == Ahoy::Event::EVENT_PAGE_VIEWED # 'Page viewed' 
      super do |event|
        page_id = event.properties['page_id'] # is there better way to pass page_id to event from track method?
        if page_id.present?

          # Do not record if duplicate event in last 3 minutes
          user_id = event.user_id.present? ?  {user_id: event.user_id} : {visit_id: event.visit_id}
          break if event.class.where({name: Ahoy::Event::EVENT_PAGE_VIEWED, page_id: page_id}.merge(user_id)).
              where('time > ?', 3.minutes.ago).exists?

          event.page_id= page_id
        end
      end
    end

  end
end
```
