### ISSUE TITLE
user_method in ActiveRecordStore and ActiveRecordTokenStore

### ISSUE THREAD

**Issue by thec0keman** [ankane/ahoy#314]
Thanks for such a great gem!

`Ahoy.user_method` seems like a nice way to set up a custom user method on controllers.  (In our use case, we wanted to add polymorphism to Ahoy visits and events).

I noticed that `ActiveRecordTokenStore` properly checks `Ahoy.user_method`, but anything else inheriting from `BaseStore` (in our case: `ActiveRecordStore`) does not.  Would it make sense to move the custom logic in `ActiveRecordTokenStore` to `BaseStore`, or is this meant to be used for something different?

**Comment by ankane** [comment]
Hey @thec0keman, Ahoy.user_method is a legacy option and shouldn't be used.

**Comment by thec0keman** [comment]
:+1: 
I noticed after writing this the readme talks about overriding the store directly.  Is that the preferred method?

Thanks!
