### ISSUE TITLE
Assigning of user to Events after authentication

### ISSUE THREAD

**Issue by sintro** [ankane/ahoy#315]
`ahoy.authenticate(user)` causes unassigned `visit` to be assigned to logged in user. 
The task is to make same thing for all event, previously assigned to current visit. 
How do you thing if this feature is worth adding to Ahoy 2.0 milestone?
It can be implemented by a bit of modifications in `authenticate` method, with possibility to enable or disable this behaviour in config or by delegating the question to `current_user`.

**Comment by ankane** [comment]
Hey @sintro, thanks for another suggestion 👍  You should be able to write custom code to accomplish this pretty easily, so I don't think it's worth adding to the project.

**Comment by sintro** [comment]
Ok, here is how to achieve this:
```
class Visit < ActiveRecord::Base
  **has_many :unassigned_ahoy_events, -> {where(user_id: nil)}, class_name: "Ahoy::Event"**
  belongs_to :user, optional: true, inverse_of: :visits
end

```
```
module Ahoy
  module Stores
    class BaseStore
      prepend (Module.new do
        def authenticate(user)
          super
          visit.unassigned_ahoy_events.update_all(user_id: user.id)
        end
      end)
    end
  end
end
```

**Comment by ankane** [comment]
Hey @sintro, thanks for sharing. A way to accomplish this with less code would be:

```ruby
class Ahoy::Store
  def authenticate(user)
    super
    visit.ahoy_events.where(user_id: nil).update_all(user_id: user.id)
  end
end
```

**Comment by sintro** [comment]
I will check it, but I think that was first thing which I tried, and now, looking at final code, probably, that was not working solution.

**Comment by sintro** [comment]
Modified the code a bit - added ` if visit` to it, so there will be no errors at first access.

**Comment by ankane** [comment]
Cool, edit example above for future readers.
