### ISSUE TITLE
Could not find generator 'ahoy:stores:active_record'

### ISSUE THREAD

**Issue by AmirolAhmad** [ankane/ahoy#316]
Added **gem 'ahoy_matey'** to the gem file and run the bundle install. When run the `rails generate ahoy:stores:active_record` it give me an error:

```
Could not find generator 'ahoy:stores:active_record'
```

My machine:
Rails 5.1.4
Ruby 2.4.2

**Comment by ankane** [comment]
Hey @AmirolAhmad, try restarting Spring.

**Comment by efojs** [comment]
Came here with `Could not find generator 'ahoy:install'` for Rails 6.1 — restarting spring helped

**Comment by pedromschmitt** [comment]
> Came here with `Could not find generator 'ahoy:install'` for Rails 6.1 — restarting spring helped

Me too! 

To prevent anyone from after getting here need to make a new search of how to restart spring, I will quote the StackOverflow:

"To stop spring you can use
` bin/spring stop`. 
It should start automatically when you run rails commands."
