### ISSUE TITLE
Question: how would you delay the installation of the cookie after the user has agreed

### ISSUE THREAD

**Issue by such** [ankane/ahoy#317]
Hello,
Thanks a lot for your awesome library.
As you might be aware, the european legislation forces all sites that use cookies to ask his agreement to the user. Is there a way to make ahoy compatible with this kind of behaviour? Can we delay the initialization of the library?
Thanks!

**Comment by such** [comment]
I tried:
```
ahoy.configure({
    startOnReady: false
});
```
but the cookie was installed anyway

**Comment by ankane** [comment]
Hey @such, you'll also need to add `skip_before_action :set_ahoy_cookies` to your `ApplicationController`.

**Comment by ankane** [comment]
Cleaning up stale issues (no response)
