### ISSUE TITLE
ahoy events 404 error

### ISSUE THREAD

**Issue by emredurukn** [ankane/ahoy#319]
1) Added gem "ahoy_matey" to my Gem File and ran Bundle install & restarted my server
2) Added //= require jquery & //= require ahoy to my application.js
3) Ran rails generate ahoy:stores:active_record and added new tables to my database by running 
rake db:migrate

`ahoy.track(name, properties);`

I use this function especially for my project. So i customize name and properties variables.

In local there is no problem but in the live version when the tracking method runs i received 404 error. This line creates A POST request to /ahoy/events and there is no path my-project-url/ahoy/events in the live version.

this is how looks like on chrome dev console
![ahoy](https://user-images.githubusercontent.com/8115903/32660839-8113e0e6-c635-11e7-8669-fe3f4e442b58.png)

**Comment by emredurukn** [comment]
Hi everyone i try a lot and finally i found solution. Meanwhile #29 issue helped me a lot.

I modify two files in my project.

# ahoy.rb
```
  mattr_accessor :auto_mount
  self.auto_mount = false
```

# routes.rb
`mount Ahoy::Engine => "/ahoy", as: :my_ahoy`

**Comment by archonic** [comment]
The equivalent of
```
mattr_accessor :auto_mount
self.auto_mount = false
```
in v 2.0+ is `Ahoy.api = false`. This is also the default.

**Comment by leoplct** [comment]
Adding this worked for me. I'd recommend adding it in the getting started tutorial.

mount Ahoy::Engine => "/ahoy", as: :my_ahoy
