### ISSUE TITLE
current_visit not present for request

### ISSUE THREAD

**Issue by jonhue** [ankane/ahoy#320]
I am trying to call this:

```ruby
location = current_visit.location
```

in my `application_controller.rb`. But I get the error:

> NoMethodError at /
undefined method `location' for nil:NilClass

So, the `current_visit` helper is not accessible, even though it should be.

**Comment by ankane** [comment]
Hey @jonhue, from the error, it looks like `current_visit` is returning nil (rather than the helper not being accessible). I'd add a `if current_visit` check before any code that uses `current_visit`, as it can be nil.

**Comment by jonhue** [comment]
@ankane 

In my understanding `current_visit` should always return the visit object, which itself must not be `nil` (because I am visiting the site right now). Please correct me if I am wrong.

**Comment by ankane** [comment]
It's very possible for `current_visit` to be `nil` (for instance, visit cookie can expire). I'd write your code with this in mind.

**Comment by jonhue** [comment]
@ankane 
Alright, thanks for your help!
