### ISSUE TITLE
Track Visit

### ISSUE THREAD

**Issue by joseglego** [ankane/ahoy#321]
Is there a way to track visits? 

I wanna track visits, just visits, without track events, without lose `visit.user_id` . Can I do this?

I'm doing it right now. But I can't change the `visit.user_id`. I already modified the `track_visit` function on `myapp/confit/initializers/ahoy.rb`. But the application never uses it. 

Also, I'm using devise, and my application has a `current_user` and it's saved in the Event, but not in the Visit. I'm using devise and activeadmin, is this related?

**Comment by ankane** [comment]
Hey @joseglego, Ahoy should automatically attach the user when you sign in with Devise. You can try overriding the `authenticate` method to debug what's going on.

**Comment by ankane** [comment]
Cleaning up stale issues
