### ISSUE TITLE
Serialization error for async geocoding using mongoid

### ISSUE THREAD

**Issue by benrs44** [ankane/ahoy#323]
Firstly, thanks for maintaining this gem, I love using it!

Unfortunately, I'm getting the following error when I enable async, using mongodb as the ahoy database:

`ActiveJob::SerializationError (Unsupported argument type: Visit):`

The app is using delayed_job, for background processing.

I there a workaround for this issue, or is this caused by incompatibility between mongoid and delayed_job?

Note: also posted on StackOverflow [here](https://stackoverflow.com/questions/47351798/rails-serialization-error-for-async-geocoding-with-ahoy-gem-using-mongoid)

**Comment by ankane** [comment]
Hey @benrs44, answered on StackOverflow
