### ISSUE TITLE
Don't create new visit if IP already exists?

### ISSUE THREAD

**Issue by Rubioli** [ankane/ahoy#324]
Great gem!

When creating `visits` is it possible to don't create a new visit/record if a visit/record with same **IP** already has been added?

Can I use?
```
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore
  def exclude?
    bot? || request.ip.present?
  end
end
```

*Problem with `request.ip.present?` is that now no `visits` are added!*

**Comment by ankane** [comment]
Hey @Rubioli, it is possible, and I think you should be able to figure it out if you break the problem down. I’d start with how to determine if a visit has been created from a specific IP already (hint: this info exists in the DB)

**Comment by Rubioli** [comment]
Thanks man. I guess I was tired after so many hours of work lol Got it work
