### ISSUE TITLE
IP stored in visit is, 127.0.0.1. Where can I override with request.remote_ip?

### ISSUE THREAD

**Issue by culov** [ankane/ahoy#330]
For some reason, most of my visits are being assigned a local IP. I want to override the method where the IP is assigned to ensure the remote_ip is stored, but am not sure where to do this.

I tried this in my Ahoy::Store, but it isn't working:

`def track_visit(options)
     super do |visit|
       visit.ip = request.remote_ip
    end
  end
`

**Comment by ankane** [comment]
Hey @culov, that pattern will work, but request.remote_ip is returning 127.0.0.1.

**Comment by pedrocarmona** [comment]
could be this:
https://stackoverflow.com/questions/10710486/wrong-ip-address-with-nginx-unicorn-rails

**Comment by ankane** [comment]
Cleaning up issues. Thanks for trying to help @pedrocarmona 👍
