### ISSUE TITLE
[Idea] Using amp-pixel when request.format == 'amp'

### ISSUE THREAD

**Issue by Bahanix** [ankane/ahoy#335]
Hello, first of all thank you for this gem, it is really great :)

It would be great to be able to use Ahoy with AMP pages, perhaps using [amp-pixel](https://www.ampproject.org/docs/reference/components/amp-pixel). It would not be perfect and would probably lose some data (eg. geocoding I guess), but it would be better than nothing :)

Whereas disabled JavaScript is quite rare, AMP users may approach 100 % of mobile visitors.

**Comment by ankane** [comment]
Hey @Bahanix, interesting idea. I haven't worked with AMP before, but happy to consider this. Can you explain more about how you're thinking it would work?

**Comment by Bahanix** [comment]
It is not possible to freely execute JavaScript with AMP: one can only use an official JS file hosted on a specific CDN delivering specific features (by the way, that's why most of news websites look all the same, since everyone have to use the same AMP-compliant-carousel, for example).

One of the features available is the amp-pixel, which loog like this: 

```html
<amp-pixel src="https://my-host.com/my-ahoy-tracker?screen_width=SCREEN_WIDTH" layout="nodisplay"></amp-pixel>
```

The `SCREEN_WIDTH` is one of the usable var subtitution. They are listed here: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#page-and-content

So, for Ahoy, it would consist of a `GET` route with some defined params that would create/update a Visit (using session id to avoid duplicate I guess), allowing a JS-free tracking system.

**Comment by Bahanix** [comment]
I digged a bit in Ahoy code and I landed here (breaklines for visibility): 

```html
<amp-pixel src="https://my-host.com/my-ahoy-tracker?
visit_token=<%= @visit_token %>&amp;
visitor_token=<%= @visitor_token %>&amp;
screen_width=SCREEN_WIDTH&amp;
screen_height=SCREEN_HEIGHT&amp;
platform=Web&amp;
landing_page=AMPDOC_URL&amp;
referrer=DOCUMENT_REFERRER" layout="nodisplay"></amp-pixel>
```

I do not know how to set `@visit_token` and `@visitor_token`: is there a way to compute theses values from the Rails side? I think it's the last bit of code I miss to start writing a PR.

**Comment by ankane** [comment]
Yeah, `ahoy.visit_token` and `ahoy.visitor_token` can be used in the controller. Looking forward to a PR. Let me know if you have any other questions.
