### ISSUE TITLE
Duplicate visit_token - ahoy_matey (1.0.2)

### ISSUE THREAD

**Issue by pctj101** [ankane/ahoy#34]
FYI, still getting this type of error after moving to v1.0.2

Mysql2::Error: Duplicate entry 'ecf37acb-ef0d-4f5f-b536-093c3a899868' for key 'index_visits_on_visit_token': INSERT INTO `visits` (`browser`, `cf_connecting_ip`, `country`, `created_at`, `device_type`, `ip`, `landing_page`, `os`, `platform`, `user_agent`, `utm_campaign`, `utm_medium`, `utm_source`, `visit_token`, `visitor_token`) VALUES ('IE', '1.2.3.4', 'US', '2014-07-31 06:26:27', 'Desktop', '1.2.3.4', 'https://example.com/';, 'Windows 7', 'Web', 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko', 'xx', 'yy-under', 'zz', 'ecf37acb-ef0d-4f5f-b536-093c3a899868', 'd57022c6-7748-490d-825f-0cbda451b845')

**Comment by Aerlinger** [comment]
Having this problem as well. Has anyone found a reasonable solution?

**Comment by bilby91** [comment]
Same issue here with pg 9.3.5 and rails 4.1.8

**Comment by honeybadaguas** [comment]
Having this same issue. Is there any way we can solve it?

**Comment by juno** [comment]
Same issue here with ahoy_matey 1.2.0, rails 4.2.3, pg 9.4.2.

@ankane 
Thank you for great gem. Our service heavily relies on ahoy. :sparkles: 

I dug into the source code and noticed that `generateId()` JavaScript function is a little naive implementation.
https://github.com/ankane/ahoy/blob/master/vendor/assets/javascripts/ahoy.js#L85-L91

You borrowed the `generateId()` logic from StackOverflow post.
The original author updated the comment at 2015-06-02 and he saids:

> Update, 2015-06-02: Be aware that UUID uniqueness relies heavily on the underlying random number generator (RNG). The solution above uses Math.random() for brevity, however Math.random() is not guaranteed to be a high-quality RNG. See Adam Hyland's excellent writeup on Math.random() for details. For a more robust solution, consider something like node-uuid.js[Disclaimer: I'm the author], which uses higher quality RNG APIs where available.]

http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript/2117523#2117523

I suppose we need a more robust UUID generator in client-side. Or generate UUID on server-side.
What do you think?

**Comment by bengalamx** [comment]
Same issue here:

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "visits_pkey"
DETAIL:  Key (id)=(143b6187-7868-42ae-b34f-06814e7ed45b) already exists.
INSERT INTO "visits" ("browser", "city", "country", "device_type", "id", "ip", "landing_page", "os", "referrer", "referring_domain", "region", "screen_height", "screen_width", "started_at", "user_agent", "user_id", "visitor_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING "id"
```

Do anyone find any solution?

**Comment by mikeghen** [comment]
I am having a similar issue, any new development? What's the deal with PR #44?

**Comment by ethankang** [comment]
Same issue here, it happens when tracks visits across subdomains.

seems like in ahoy.js, `destroyCookie("ahoy_track")` does not destroy the cookie, that causes to re-post visit.

in https://github.com/ankane/ahoy/blob/master/vendor/assets/javascripts/ahoy.js#L146
```
if (visitId && visitorId && !track) {
    // TODO keep visit alive?
    log("Active visit");
    setReady();
  } else {
    if (track) {
      destroyCookie("ahoy_track");
    }
  
...

  $.post(visitsUrl, data, setReady, "json");
}
```

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen or create a new issue if someone is still seeing this on the latest version and interested in helping to debug.

**Comment by GlombSt** [comment]
Just ran into this issue for tracking_events. 
For a base of 10 million events we see about 50 duplicate UUIDs over 24 hours.

**Comment by ankane** [comment]
@GlombSt Can you create a gist with the full error and backtrace?
