### ISSUE TITLE
Geocoder version needs to be updated

### ISSUE THREAD

**Issue by sds-dubois** [ankane/ahoy#341]
I noticed that the ip lookup with freegeoip started to fail. I fixed it by requiring version `1.4.5` of the Geocoder gem (see alexreisner/geocoder#1270).

It looks like there is no version set for the Geocoder gem dependency, so I guess you should require `>= 1.4.5` .

And thanks for this great gem!

**Comment by ankane** [comment]
Nice find, thanks @sds-dubois 👍
