### ISSUE TITLE
[Idea] Support for ActiveJob

### ISSUE THREAD

**Issue by danielfriis** [ankane/ahoy#344]
Hi,

First of all, thank you for the work on this awesome gem!

The only thing we're missing is support for ActiveJob. Non-crititical operations such as analytics should be possible to move into a background process.

**Comment by ankane** [comment]
Hey @danielfriis, can you explain your idea a bit more? Ahoy already uses ActiveJob for background tasks like geocoding.

**Comment by danielfriis** [comment]
Hi @ankane. 

I'm imagining something like `ahoy.track_later "My event"`.

I tried to do it manually, like this:
```
class Ahoy::Store < Ahoy::BaseStore
  def track_event(data)
    AhoyTrackEventJob.perform_later(@options, data)
  end
end
```

```
class AhoyTrackEventJob < ApplicationJob
  queue_as :default

  def perform(options, data)
    Ahoy::DatabaseStore.new(options).track_event(data)
  end
end
```

But `@options` throws an `ActiveJob::SerializationError: Unsupported argument type`

**Comment by ankane** [comment]
Thanks @danielfriis. I don't see a strong reason to support this pattern in the main gem, but since stores are customizable, someone could create a gem to add this functionality.
