### ISSUE TITLE
[help wanted] How to run tests?

### ISSUE THREAD

**Issue by gknedo** [ankane/ahoy#345]
Hi, i'm developing a way to allow the javascript on client side set the user_id ([issue on ahoy.js](https://github.com/ankane/ahoy.js/issues/27)).

But i'm having trouble running the test suite.
I just cloned the project, installed the gems with `bundle install` and i'm running `rake test`, but the default database config fails...
What database configs is expected?

**Comment by ankane** [comment]
Hey @gknedo, Ahoy only has tests for a very small part of functionality (which is why it's not documented), so don't worry running/adding tests.

**Comment by gknedo** [comment]
#348
