### ISSUE TITLE
[idea] - Allow Ahoy destroy after boot

### ISSUE THREAD

**Issue by peacepostman** [ankane/ahoy#349]
Hello,

With the incoming GDPR I think it could be nice to add a function to disable ahoy's tracking for the final user.

Best regards,

**Comment by ankane** [comment]
Hey @peacepostman, can you elaborate what you're thinking on how this would work?

**Comment by peacepostman** [comment]
Yes for sure. The basic idea is that users should be allowed to stop being tracked on a session. I have edited the JS part and the result is a kill and a restart function. 

The kill function remove all ahoy cookies and add a ahoy_disabled cookie set on true. I have also altered the ready() and track() function in order to check this cookie value before doing anything.

The restart function simply set ahoy_disabled to false.

I can submit a PR if you want when I have some free time. I didnt dig into the rails part because im working on the front part of our app but im pretty sure this behavioir can be easily mimic.

**Comment by ankane** [comment]
Sure, happy to review a PR. For anyone following along, here's a good summary: https://www.itgovernance.eu/blog/en/how-the-gdpr-affects-cookie-policies/

**Comment by peacepostman** [comment]
Yes I agree with the accept before condition. Our approach was to use this sentence on app onboarding "By continuing your visit to this site, you accept the use of Cookies to make visits statistics. To learn more and set cookies click here"

This approach allow us to track before and disable after but I rather like the accept before way :)

**Comment by ankane** [comment]
Cleaning up issues. For future readers, Ahoy took a different route that doesn't require cookies.
