### ISSUE TITLE
ahoy + Geocoder

### ISSUE THREAD

**Issue by Soukab** [ankane/ahoy#352]
Hi,

I've just added ahoy to my ruby on rails project and it's actualy storing some informations about the visits except for the city, region.
this is a capture of my database rows of ahoy_visits:
<img width="793" alt="ll" src="https://user-images.githubusercontent.com/16567004/38547162-642878d8-3ca6-11e8-990c-243458ea128c.PNG">

Did I miss something?

**Comment by ankane** [comment]
Hey @Soukab, this happens for local IP addresses (like `127.0.0.1`). If this is happening in production, you'll need to update your infra setup to pass Rails the correct IP. There should be docs online for how to do this.
