### ISSUE TITLE
Freegeoip Important Announcement

### ISSUE THREAD

**Issue by janephilipps** [ankane/ahoy#353]
Hi @ankane,

Our team at The Information just noticed that the freegeoip API will be discontinued on July 1st. [Here is the announcement](https://github.com/apilayer/freegeoip/#freegeoip---important-announcement) with the details.

We wanted to point this out in case any changes need to be made to ahoy before July 1st. We're happy to help out!

Thanks!

**Comment by ankane** [comment]
Hey @janephilipps, thanks for the heads up 👍  I'm curious to see what the `geocoder` gem will make the new default for IP geocoding. It looks like there are other free services that don't require an API key, but with lower request limits. https://github.com/alexreisner/geocoder#ip-address-services

**Comment by ankane** [comment]
To follow along: https://github.com/alexreisner/geocoder/issues/1279

**Comment by achasveachas** [comment]
I wonder if this is connected to this issue, but today I noticed that Ahoy stopped saving location data sometime this morning (Between `2018-07-02 10:49:35 UTC` and `2018-07-02 12:06:57 UTC`.

Nothing changed in my code, and I reverted to earlier versions of my code just in case and I still don't have location info for visits.

**Comment by ankane** [comment]
Cleaning up issues
