### ISSUE TITLE
User does not get linked to Visit

### ISSUE THREAD

**Issue by damienlethiec** [ankane/ahoy#355]
Hello,

I have just installed Ahoy and everything works great, except the visit does not get linked to a user. It gets linked correctly for the event.

More details:

Gems:
```
gem 'ahoy_matey', github: "ankane/ahoy"
gem 'devise', '~> 4.4'
```

I use Devise with a Client model, not user. So I made the following change in my Ahoy initializer:
`Ahoy.user_method = :current_client`

Here is my Event model (linked correctly to the client):
```
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :client, optional: true, foreign_key: 'user_id'
end
```

Here is my Visit model (not linked correctly to the client --> client_id is always nil):
```
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event", dependent: :destroy
  belongs_to :client, optional: true, foreign_key: 'user_id'
end
```

Do you have an idea of the reason?

Thanks a ton in advance :)

**Comment by ankane** [comment]
Hey @damienlethiec, please check out the Contributing Guide.

**Comment by damienlethiec** [comment]
Nevermind, found a solution.

You need to set an alias so the Visit model knows the user method

--> `alias_attribute :user, :client`

**Comment by artyrcheek** [comment]
@damienlethiec Legend, been looking for this!
