### ISSUE TITLE
Add or Extract data to properties in Events

### ISSUE THREAD

**Issue by kevinjbayer** [ankane/ahoy#36]
I'm using a slug for my URL, but would also like to capture the ID. I've narrowed it down to two routes I could take, but I'm not sure which is best.

1) Track an additional property and pull this out of the JSON? This seems far more difficult and can't figure out how to grab one of the properties like under Explore the Data or Funnels.

For instance, I added <%= ahoy.track "Viewed Model", title: "#{@model.id}" %> to my template and that works, but can I pull out the id easily for reports? That's where I'm stuck on this route.

2) Add an additional column under ahoy_events that references the ID. This seems far simpler? Is this correct route to take?

Still learning Ruby so sorry if this one is obvious.

& great work on all of your awesome plugins, @ankane! Loving this, chartkick and groupdate. Powerful stuff.

**Comment by ankane** [comment]
Cleaning up issues
