### ISSUE TITLE
`visit_token` and `visitor_token` are fetched from the request headers first even if Ahoy.api = false

### ISSUE THREAD

**Issue by monfresh** [ankane/ahoy#362]
Hello. Looking at the code in `tracker.rb`, I see that the token in `visit_token` and `visitor_token` is first read from the request headers "Ahoy-Visit" and "Ahoy-Visitor", respectively. However, I could not find anywhere those headers are being set. I noticed in the README that those headers apply to the API spec, but Ahoy.api is set to `false` by default.

Is there a reason the token is read from the headers even if Ahoy.api is set to false? Am I misunderstanding something?

The reason I ask is because we noticed some strange values for some of our `visit_token` and `visitor_token`, such as "cwindowswinini", "windowswininijpg", "windowswinini", and "unexistingwindowswinini". Looking through the Ahoy code, the only explanation for this is someone is sending a request to our app with the "Ahoy-Visit" and "Ahoy-Visitor" headers set to those values. I confirmed this locally by running `curl http://localhost:3000 -H Ahoy-Visit:'foo' -H User-Agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"`

Also note that we are not using `ensure_uuid` because if someone is setting those headers, they are not a normal user, and we don't want to treat their visit as a normal event. I know that we can exclude these events by defining an `exclude?` method in our Store that rejects any requests that contain "Ahoy-Visit" and/or "Ahoy-Visitor" headers, but I wanted to understand why Ahoy is behaving this way by default event when `Ahoy.api` is `false`, which means the app isn't using or expecting those request headers, right?

**Comment by ankane** [comment]
Hey @monfresh, the header allows the visitable method to work for mobile clients. Another explanation is someone is passing these values as in cookies (pentesters often do this).

**Comment by monfresh** [comment]
Ah, yes, good point about the cookies. Is there a particular reason you recommend using `ensure_uuid` in the Upgrade guide? Why not exclude any events that don't have a valid UUID?

**Comment by ankane** [comment]
It's just to keep the old behavior of Ahoy, which used `ensure_uuid`.
