### ISSUE TITLE
ahoy_visits.visitor_token = 'null'

### ISSUE THREAD

**Issue by jsharpe-mr** [ankane/ahoy#366]
Hi,

We've had ahoy up for a few months now, and today I came across an ahoy_visit record with visitor_token = 'null'. (That'd be the value 'null' not IS NULL). Further, it appears that we've possibly accumulated several distinct instances of events relating to this 'visitor' since we've had it up:

```
select 
  min(ahoy_visits.visitor_token),
  count(ahoy_events.id), 
  date(ahoy_events.time) 
from
  ahoy_events 
left join
  ahoy_visits on ahoy_events.visit_id = ahoy_visits.id 
where
  ahoy_visits.visitor_token = 'null'
group by
  date(ahoy_events.time);
 min  | count |    date
------+-------+------------
 null |     1 | 2018-05-03
 null |    34 | 2018-05-09
 null |     1 | 2018-05-17
 null |     2 | 2018-05-25
 null |    50 | 2018-06-04
 null |    25 | 2018-06-18
 null |    45 | 2018-06-20
 null |     2 | 2018-06-24
```
I supposed the issue could be in the client somehow generating 'null' as a token and passing that to the server, or, it could be the server somehow mucking up the token that is passed in.  Any guidance as to which is more likely would be appreciated.

Current version is 2.0.2, and I'm happy to update that to the latest, but as this is seemingly a sporadic issue, upgrading isn't going to immediately inform whether or not this issue is fixed.

Thanks!

**Comment by ankane** [comment]
Closing due to no response
