### ISSUE TITLE
Upgrading to 2.1, visit_token doesn't exist

### ISSUE THREAD

**Issue by kevinjbayer** [ankane/ahoy#367]
I'm finally trying to upgrade to 2.1 while I'm upgrading Rails to 5.2. I managed to work through the first couple issues I was running into. I can still successfully log my user in, but in my logs, I'm seeing this error:

```
PG::UndefinedColumn: ERROR:  column visits.visit_token does not exist
LINE 1: SELECT  "visits".* FROM "visits" WHERE "visits"."visit_token...
```

Which is true, I don't have a 'visit_token' column on visits. I assume this replaced 'id'? Should I just create a method to override visit_token to point to my id column, and where/how should I do that? I'm guessing that makes more sense that attempting some migrations that change column names around, right?

**Comment by ankane** [comment]
Hey @kevinjbayer, here are instructions for upgrading: https://github.com/ankane/ahoy/blob/master/docs/Ahoy-2-Upgrade.md
