### ISSUE TITLE
Tracking data missing since upgrading with GPDR settings

### ISSUE THREAD

**Issue by kofronpi** [ankane/ahoy#368]
Hello,

I'm using latest versions of ahoy and ahoy.js with recommended setup settings + GPDR settings (except  one thing : I don't overload `authenticate` to delink users & visits.

Since, on hundreds of visits 99.9% have missing fields:

-landing_page
-referrer
-referring_domain
-all utm parameters

all of which are equal to `nil`.

Those data were correctly collected before.

Any idea ? :) Could it be related to API mode being enable, or cookie tracking disabled ?

Thank you for your help.

**Comment by ankane** [comment]
Hey @kofronpi, this can happen when:

```ruby
Ahoy.cookies = false
Ahoy.server_side_visits = :when_needed
```

With cookies disabled, you should be able to set `Ahoy.server_side_visits = true`.

**Comment by kofronpi** [comment]
Thank you, I will try that out but I indeed had this config with `:when_needed`
