### ISSUE TITLE
How do I use ahoy in tests ?

### ISSUE THREAD

**Issue by emilsoman** [ankane/ahoy#37]
I'm currently hacking together a dashboard for my app to list all the ahoy events which are in the DB. I was thinking there would be some module I could easily include in my test so I could use "ahoy.track" inside my tests to setup some seed data for the test. I was hoping to find it in ahoy's test suite but I was surprised to find no tests :smile: (but it's still a kickass library and very useful, thank you) . So is there a module I can include to get hold of the controller helper methods ?

**Comment by ankane** [comment]
Cleaning up issues

**Comment by zyjisdog** [comment]
I have a same issue: following the README.md, I inserted the `ahoy.authenticate(user)` to the end of my own log_in method, then I ran the tests, but got an error:
```
NameError: undefined local variable or method `ahoy' for #<SessionsHelperTest:0x0000000823cca8>
            app/helpers/sessions_helper.rb:6:in `log_in'
            app/helpers/sessions_helper.rb:42:in `current_user'
            test/helpers/sessions_helper_test.rb:13:in `block in <class:SessionsHelperTest>'
```

sessions_helper.rb:
```
  def log_in(user)
    session[:user_id] = user.id
    ahoy.authenticate(user)
  end

  ......

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
```

sessions_helper_test.rb:
```
  test "current_user returns right user when session is nil" do
    assert_equal @user, current_user
    assert is_logged_in?
  end
```

**Comment by grozwalker** [comment]
@zyjisdog Did you find a solution?

**Comment by piotrturek** [comment]
Try to set this config in your initializer, then you will get `current_visit` as other methods available.
```
Ahoy.track_bots = Rails.env.test?
```

**Comment by jch** [comment]
Similar idea as ☝️ but I'm scoping it a single test file to avoid the extra writes across the test suite

```ruby
require "test_helper"

class AhoyTest < ActionDispatch::IntegrationTest
  setup do
    Ahoy.track_bots = true
  end

  teardown do
    Ahoy.track_bots = false
  end
end
```
