### ISSUE TITLE
Unable to create visit/event seed data

### ISSUE THREAD

**Issue by krsyoung** [ankane/ahoy#370]
Hi,

I'm trying to create sample visit and event data for Ahoy through the `seeds.rb` in my application. Unfortunately I can't seem to get past the error:

    Event excluded since visit not created: e80bea21-8e9f-4398-bdd4-d2768262d34f

I've used pretty much every variation of the following:

    # seeds.rb
    ahoy = Ahoy::Tracker.new
    current_user = User.first
    ahoy.authenticate(current_user)
    ahoy.track_visit()
    time = rand(1..100).hours.ago
    ahoy.track "search", {term: 'cool'}, {time: time}

Inspecting shows that the `ahoy.visit` is always nil:

    irb(main):007:0> ahoy.visit
    => nil

I believe this is the same as this [SO question](https://stackoverflow.com/questions/35531828/create-seed-data-for-analytics-ahoy-gem) (although not sure about any version differences from ~2 years ago)

I'm using Ahoy 2.1.0, Rails 5.2 and Ruby 2.5.0.

**Comment by ankane** [comment]
Hey @krsyoung, I don't know off the top of my head. I'd try forking the gem and adding some debugging to see why `track_visit` isn't creating an visit.

**Comment by ankane** [comment]
Closing due to no response

**Comment by krsyoung** [comment]
Sorry, just been busy, it is in my TODO list.  Hopefully will get to it this week.  I don't believe it has been fixed in the interim.

**Comment by krsyoung** [comment]
Ok, well that was way more fun than I had anticipated.

The net goal I wanted to achieve was to be able to create visits / events outside of the Rails server runtime.  This way I can generate seed data to test how the various UIs which display the analytics information (and it would be a lot more interesting than the current version of the dev db .. which is usually just today!).

The Ahoy library is incredibly tied into the `Request` class.  I could not find a good way to weed it out in the code (or avoid it) so I went ahead and mocked it thanks to the `request:` parameter in `Ahoy::Tracker.new`.

I've created a new class called `RequestFaker` which is intended to give just enough of a request object to let the library operate.

At the moment it isn't pretty but the usage would look like:

```
# seeds.rb
Ahoy.geocode = false
ahoy = Ahoy::Tracker.new(request: RequestFaker.new)
ahoy.track 'order_pizza'
ahoy.track 'order_pizza', {}, {time: 10.days.ago}
100.times.map{ Random.rand(100) }.each do |rando|
  ahoy.track 'order_pizza', {}, {time: rando.days.ago}
end
``` 

I still have one problem I'm trying to work through, basically I think there is an issue where the `visit` is somehow being serialized and giving an error like:

```
# Ahoy::Visit != Ahoy::Visit ???
ActiveRecord::AssociationTypeMismatch Exception: Ahoy::Visit(#70150552378200) expected, got #<Ahoy::Visit id: 6, ...> which is an instance of Ahoy::Visit(#70150537837220)
```
I thought it was due to Geocoding and DelayedJob but seems to not be the case.   I can avoid the problem with the following code:

```
diff --git a/lib/ahoy/database_store.rb b/lib/ahoy/database_store.rb
index 52c6a71..7ac29c7 100644
--- a/lib/ahoy/database_store.rb
+++ b/lib/ahoy/database_store.rb
@@ -1,3 +1,4 @@
+require 'byebug'
 module Ahoy
   class DatabaseStore < BaseStore
     def track_visit(data)
@@ -15,7 +16,13 @@ module Ahoy
       visit = visit_or_create(started_at: data[:time])
       if visit
         event = event_model.new(slice_data(event_model, data))
-        event.visit = visit
+        # WTF ... prevents
+        # ActiveRecord::AssociationTypeMismatch Exception: Ahoy::Visit(#70150552378200) expected, got #<Ahoy::Visit id: 6, ...> which is an instance of Ahoy::Visit(#70150537837220)
+        if visit.is_a? Ahoy::Visit
+          event.visit = visit
+        else
+          event.build_visit(visit.attributes)
+        end
         event.time = visit.started_at if event.time < visit.started_at
         begin
           event.save!
```

Here is my `RequestFaker` class:

```
# request_faker.rb
class RequestFaker
  attr_reader :params, :content_length, :body, :remote_ip, :original_url, :user_agent, :cookies, :referer, :headers

  def initialize(**options)

    @params = options[:params] || {}
    @headers = options[:headers] || {}
    @content_length = options[:content_length] || 10
    @body = options[:body] || StringIO.new('fake')
    @remote_ip = options[:remote_ip] || '127.0.0.1'
    @original_url = options[:original_url] || '/'
    @user_agent = options[:user_agent] || 'Agent/Fake'
    @cookies = options[:cookies] || {}
    @referer = options[:referer] || 'example.com'

    @options = options
  end

end
```

Not sure your thoughts @ankane?  Either on the error or on the general approach?

**Comment by krsyoung** [comment]
Well, inevitable the act of typing something makes it wrong :| 

The above doesn't work, however using the following class everything seems to work!

```
# request_faker.rb
class RequestFaker
  attr_reader :params, :content_length, :body, :remote_ip, :original_url, :user_agent, :cookies, :referer, :headers, :cookie_jar

  def initialize(**options)

    @params = options[:params] || {}
    @headers = options[:headers] || {}
    @content_length = options[:content_length] || 10
    @body = options[:body] || StringIO.new('fake')
    @remote_ip = options[:remote_ip] || '1.1.1.1'
    @original_url = options[:original_url] || '/'
    @user_agent = options[:user_agent] || 'Agent/Fake'
    @cookies = options[:cookies] || {}
    @cookie_jar = options[:cookie_jar] || {}
    @referer = options[:referer] || 'example.com'

    @options = options
  end
end
```

And to load a bunch of data:

```
# seeds.rb
Ahoy.geocode = false
ahoy = Ahoy::Tracker.new(request: RequestFaker.new)
ahoy.track 'order_pizza'
ahoy.track 'order_pizza', {}, {time: 10.days.ago}
100.times.map{ Random.rand(100) }.each do |rando|
  ahoy.track 'order_pizza', {}, {time: rando.days.ago}
end
```

Keeping the Geocoding disabled does seem to avoid the serializing / DelayedJob issue.  So as long as the seeding can live without Geocoding (which seems like a good idea in general, just fake it if needed), this should work.
