### ISSUE TITLE
uninitialized constant Ahoy::Visit

### ISSUE THREAD

**Issue by ChrisCPO** [ankane/ahoy#371]
```
Rails 5.2
ahoy_matey 2.1
```

Where seeing a good bit of these errors. stack trace:
![screen shot 2018-07-18 at 6 05 45 pm](https://user-images.githubusercontent.com/7773951/42910445-8ff962d0-8ab5-11e8-926a-e667d3c8fea0.png)

**Comment by yagudaev** [comment]
Having a similar issue now, migrating to Rails 5.0.7 and Ahoy 2.1.0. How did you resolve the issue @ChrisCPO?

**Comment by bascoe10** [comment]
@yagudaev I came across this issue. Make sure that you Visit Model is scoped correctly.
```ruby
class Ahoy::Visit < ApplicationRecord
  # code here
end
```

of you can re-define the `visit_model` in `config/intializers/ahoy.rb`
```ruby
class Ahoy::Store < Ahoy::DatabaseStore
  protected
  def visit_model
    ::Visit
  end
end
```
I found the latter to be a bit hacky
