### ISSUE TITLE
ahoy_events rolling back if manually added to controller

### ISSUE THREAD

**Issue by lettergram** [ankane/ahoy#372]
Hello, I have been having an issue with ahoy_events rolling back if I try to manually add them. 

It appears to be the same (or similar issue) to #153 

Essentially, I have javascript handling events, but if I try to manually add an event, such as the following in a controller (Rails side):

`ahoy.track("Search", term: "words",  source: "somewhere", domain: "example.com")`

I see it being executed, but it appears to do a rollback:

```
(0.2ms)  BEGIN
SQL (0.8ms)  
   INSERT INTO "ahoy_events" ("id", "visit_id", "name", "properties", "time") 
   VALUES ($1, $2, $3, $4, $5) RETURNING "id"  
   [["id", 0], ["visit_id", 4], ["name", "Search"], 
   ["properties", "{\"term\":\"words\",\"source\":\"somewhere\",\"domain\":\"example.com\"}"], 
   ["time", "2018-07-22 02:40:42.431005"]]
(0.1ms)  ROLLBACK
```

The `id` appears to be the issue there, also if I inspect the current_visit (`current_visit.inspect`) I can see my visit_id is 4, so that seems fine. The id should probably be iterating, so it appears to be manually getting set to zero:

```
   Column   |   Type  | Nullable |                 Default    
------------+---------+----------+-----------------------------------------
 id         | integer | not null | nextval('ahoy_events_id_seq'::regclass)
Indexes:
    "ahoy_events_pkey" PRIMARY KEY, btree (id)
```

I also found if I add `id` to the params, I can get different `id`'s to appear. Every time I managed to get a different `id` for the insert.

In six attempts I got: 0, 4, 0, 4959, 83563089, 0

The last attempt worked:

```
(0.2ms)  BEGIN
SQL (0.8ms)  
   INSERT INTO "ahoy_events" ("id", "visit_id", "name", "properties", "time") 
   VALUES ($1, $2, $3, $4, $5) RETURNING "id"  
   [["id", 83563089], ["visit_id", 4], ["name", "Search"], 
   ["properties", "{\"id\":3340, \"term\":\"words\",\"source\":\"somewhere\",\"domain\":\"example.com\"}"], 
   ["time", "2018-07-22 03:01:01.283000"]]
(0.1ms)  ROLLBACK
```

Which means, it is indeed an issue with `id` being set incorrectly - as the other `id`'s were already taken in the sequence. The next id in the secuence being (on my system) being: `33400`, dicovered through the following comment:

```
SELECT last_value FROM ahoy_events_id_seq;
```

I have edited `config/initializers/ahoy.rb` to match what was described in [ahoy 2 upgrade](https://github.com/ankane/ahoy/blob/master/docs/Ahoy-2-Upgrade.md)

```
  Ahoy.api = true
  Ahoy.server_side_visits = :when_needed

  def track_visit(data)
    data[:id] = ensure_uuid(data.delete(:visit_token))
    data[:visitor_id] = ensure_uuid(data.delete(:visitor_token))
    super(data)
  end

  def track_event(data)
    data[:id] = ensure_uuid(data.delete(:event_id))
    super(data)
  end
```

Any ideas? Perhaps this is even intended..?

**Comment by ankane** [comment]
Closing due to no response
