### ISSUE TITLE
Add a way to extend ahoy with extra associations

### ISSUE THREAD

**Issue by ndbroadbent** [ankane/ahoy#377]
Hello! My app has an Account model that has multiple users, and I'd like to use `ahoy` to track account-level events. I've added an `account_id` column to the `ahoy_*` tables, and have started extending all the Ahoy classes with some monkey patches. But I was thinking that it would be cool if there was an official API for doing this. I might take a quick stab at a PR, and would love to get your thoughts.

**Comment by ndbroadbent** [comment]
Actually I think this is easy enough to do in `config/initializers/ahoy.rb`. After reading through the source code, I figured out that I could just do:

```ruby
module Ahoy
  class Store < DatabaseStore
    def account
      @account ||= controller.current_account
    end

    def authenticate(_)
      if visit&.respond_to?(:account) && !visit.account
        visit.account = account
      end
      super
    end

    def track_visit(data)
      super(data.merge(account_id: account.id))
    end

    def track_event(data)
      super(data.merge(account_id: account.id))
    end
  end
end
```

**Comment by ankane** [comment]
For future readers, this is the recommended way to track additional data. I've tried to get this across in the readme in [this section](https://github.com/ankane/ahoy#track-additional-data), but maybe it could use some work.

**Comment by krsyoung** [comment]
This was very helpful @ndbroadbent! My only addition for future users would be to ensure that the `current_account` method is public wherever it is defined (likely ApplicationController) . 👍

**Comment by nekapoor** [comment]
Sorry for adding a question on this so late. The big question i have here is where is this account_id stored? @ndbroadbent did you just add this field to your Ahoy Visit table?
