### ISSUE TITLE
Tracking events from models and background jobs

### ISSUE THREAD

**Issue by ndbroadbent** [ankane/ahoy#382]
Hello! I couldn't find any documentation about this use-case, but this is actually the main reason I'm interested in using `ahoy`. It's awesome to be able to track visits and events on the client and in controller actions, but I'd also love to track account "lifecycle" events, like "created account", "suspended account", "new stripe invoice for $x".

Do you think it would be ok to use `belongs_to :visit, optional: true` in the `Ahoy::Event` model? I have an "events" table in my admin views, so I want this to be a stream of both client and server events in the same table.

But I guess I'm just wondering if you have any concerns about performance, or maybe `ahoy` isn't really written to support this case? Would love to hear your thoughts!

**Comment by ndbroadbent** [comment]
Got it all set up and it seems to be working really well!

**Comment by jsmestad** [comment]
@ndbroadbent care to share some code snippets on how you used Ahoy::Event from elsewhere in your Rails app?

**Comment by ndbroadbent** [comment]
Hi @jsmestad, I'm actually just using plain Rails methods to create the records, e.g.

```ruby
account.events.create(name: 'Account Event', properties: { foo: true })
```

I have an Account model with:

```ruby
has_many :events, class_name: 'Ahoy::Event', dependent: :destroy
```

Very simple, and haven't run into an issues yet.

**Comment by alainravet** [comment]
To be complete, you need to pass the `visit` and the `time` too
```
model User
  ..
  has_many :visits, class_name: 'Ahoy::Visit'
  has_many :events, class_name: 'Ahoy::Event'

  def record_action(name, properties = {})
    current_visit = visits.last
    events.create! name:       name,
                   visit:      current_visit,
                   time:       Time.now,
                   properties: properties
  rescue => e
    Raven.capture_exception e
  end
end
```
