### ISSUE TITLE
[Idea] Separate token generators for visitors and visits.

### ISSUE THREAD

**Issue by peterkeen** [ankane/ahoy#384]
I've been using Stripe for a number of years, and one of the very nice things they do with their API is typed IDs. Every ID that the API sends back to you is prefixed with a type so that you know exactly what you're looking at when you see one.

I've started to embrace this in my own projects and it would be handy to be able to set this up for Ahoy as well. I'm not sure about the design, though. The naive way would be to have two separate `generate_id` functions in the store, along with two different configuration options. We could also pass a type symbol through to `generate_id`.

**Comment by ankane** [comment]
Hey @peterkeen, I think having two options makes sense to me.

**Comment by ankane** [comment]
Cleaning up issues. I actually now think adding a parameter to the `generate_id` function is a better approach than multiple functions. If someone ones to do this, feel free to submit a PR.
