### ISSUE TITLE
[Question] Native app database columns?

### ISSUE THREAD

**Issue by chrismanderson** [ankane/ahoy#385]
(Posting this here as it seemed a better place than Stackoverflow)

Currently integrating Ahoy with a Rails app and an iOS app. I'm coding up the native api integration following the [api spec](https://github.com/ankane/ahoy#api-spec). But I noticed fields such as `os_version` and `app_version` are not created in the Ahoy migrations nor populated in any other field. 

I'm assuming the solution is as simple as adding those various fields into the create `ahoy_visits` migration, ala:

```
# mobile 
t.string :app_version
t.string :os_version
t.string :platform
```

but I wanted to make sure that is how to proceed with native visits and that I wasn't missing something. If it is what I should do, might be worth adding a bit into the readme's native section stating as such.

Thanks!

**Comment by ankane** [comment]
Hey @chrismanderson, that's exactly right. I'll update the docs when I have a chance.
