### ISSUE TITLE
Skipping track_ahoy_visit filter is nullifying devise's session 

### ISSUE THREAD

**Issue by naveed-ahmad** [ankane/ahoy#386]
We don't want to track visits for logged in users in our app. I followed the readme and skipped the `track_ahoy_visit` filter but that broke the login stuff. User's session are not persisting. 

here is steps to reproduce:
```
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :authenticate_user!
  skip_before_action :track_ahoy_visit, if: :user_signed_in?

end
```

I had to enable visit tracking again, will try to debug the issue and open PR. 

Gem versions:
ahoy_matey:  2.1.0
devise:   4.4.3

**Comment by ankane** [comment]
Hey @naveed-ahmad, thanks for reporting 👍 I don’t really see how skipping that method would affect the user session. What happens if you exclude the if condition?

**Comment by ankane** [comment]
Cleaning up issues (no response)
