### ISSUE TITLE
How to connect to elasticsearch as data store?

### ISSUE THREAD

**Issue by patakijv** [ankane/ahoy#387]
@ankane, this is a great gem for tracking visits and events! We are looking to move several areas of the data in our rails app to elasticsearch for better searching. Coincidentally we are using another great gem by you [searchkick](https://github.com/ankane/searchkick) for indexing (loading from mysql to elasticsearch) and searching data in elasticsearch.

Instead of having the data for events and visits go first to mysql through activerecord, then to elasticsearch, is there way to just have visits and events data go directly to elasticsearch as the data store and bypass mysql? 

Since you have both of these gems I am curious if you have used ahoy like this and if there exists a solution/sample for this implementation of ahoy directly with elasticsearch? Anything similar?

**Comment by ankane** [comment]
Hey @patakijv, you can write a custom data store for this. https://github.com/ankane/ahoy#data-stores

Check out the database store the in repo for a good example.

**Comment by ankane** [comment]
I haven't tried to do this, and Searchkick isn't designed to create records in Elasticsearch without another primary data store. You probably want something like this: https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence
