### ISSUE TITLE
[Idea] Separate out 'mount' and 'api' config

### ISSUE THREAD

**Issue by golmansax** [ankane/ahoy#388]
Hi, I use Ahoy with an API-only Rails setup and I'm mounting the Ahoy API at a path different from the default.

I currently need to set `api = false` or else I can't mount `Ahoy::Engine` at a custom path (`Invalid route name, already in use: 'ahoy_engine'`).  I'm assuming though that `api` should be set to true for my use case.

Could we bring back the `mount` option and have it default to `api`?  Happy to create this pull request if you think this is a good idea.

**Comment by ankane** [comment]
Hey @golmansax, `api` is the `mount` option.

**Comment by golmansax** [comment]
Thanks for the fast response.  I was trying to say that for the use case as described above, I want `api` to be turned on but I don't want to mount `Ahoy::Engine` at `/ahoy`, I want to mount it at a different path, say `/api/ahoy`.

Is this a valid scenario?  I believe that what I described is not possible given the current config options.

**Comment by ankane** [comment]
All the `api` option does is mount. Please look at the code if you have more questions.

**Comment by golmansax** [comment]
Ah, sorry I thought that the `api?` in the tracker was looking that the module params.  https://github.com/ankane/ahoy/blob/master/lib/ahoy/tracker.rb#L159.
