### ISSUE TITLE
Can't get geocoding to work because location.country is always blank (even though... it's not!)

### ISSUE THREAD

**Issue by darmenise** [ankane/ahoy#390]
Hi there, awesome gem!

My only problem is that I can't get the geocoding to work.

The problem seems to be related to this [line](https://github.com/ankane/ahoy/blob/master/app/jobs/ahoy/geocode_v2_job.rb#L14):

```ruby
module Ahoy
class GeocodeV2Job < ActiveJob::Base
[...]
if location && location.country.present? # <= but my location.country is never present...
```

This is really odd because, from my console, I get this:

```
> heroku run rails c

> visit = Ahoy::Visit.last

> location = Geocoder.search(visit.ip).first

=> #<Geocoder::Result::Geoip2:0x00000006e14910 @data=#<MaxMindDB::Result:0x00000006e150b8 @raw={"city"=>{"geoname_id"=>3170918, "names"=>{"de"=>"Piasco", "en"=>"Piasco", "fr"=>"Piasco", "pt-BR"=>"Piasco"}}, "continent"=>{"code"=>"EU", "geoname_id"=>6255148, "names"=>{"de"=>"Europa", "en"=>"Europe", "es"=>"Europa", "fr"=>"Europe", "ja"=>"ヨーロッパ", "pt-BR"=>"Europa", "ru"=>"Европа", "zh-CN"=>"欧洲"}}, "country"=>{"geoname_id"=>3175395, "is_in_european_union"=>true, "iso_code"=>"IT", "names"=>{"de"=>"Italien", "en"=>"Italy", "es"=>"Italia", "fr"=>"Italie", "ja"=>"イタリア共和国", "pt-BR"=>"Itália", "ru"=>"Италия", "zh-CN"=>"意大利"}}, "location"=>{"accuracy_radius"=>50, "latitude"=>44.5611, "longitude"=>7.4442, "time_zone"=>"Europe/Rome"}, "postal"=>{"code"=>"12026"}, "registered_country"=>{"geoname_id"=>3175395, "is_in_european_union"=>true, "iso_code"=>"IT", "names"=>{"de"=>"Italien", "en"=>"Italy", "es"=>"Italia", "fr"=>"Italie", "ja"=>"イタリア共和国", "pt-BR"=>"Itália", "ru"=>"Италия", "zh-CN"=>"意大利"}}, "subdivisions"=>[{"geoname_id"=>3170831, "iso_code"=>"21", "names"=>{"de"=>"Piemont", "en"=>"Piedmont", "es"=>"Piamonte", "fr"=>"Piémont", "ja"=>"ピエモンテ州", "ru"=>"Пьемонт", "zh-CN"=>"皮埃蒙特"}}, {"geoname_id"=>3177699, "iso_code"=>"CN", "names"=>{"en"=>"Provincia di Cuneo", "fr"=>"Coni"}}], "network"=>"85.159.180.0/23"}>, @cache_hit=nil>
```

So location is not nil!
But then:

```
> location.country
=> ""
```

**Even though**:  👀

```
irb(main):008:0> location.data['country']['names']['en']
=> "Italy"
```

I'm riding:

```
> Rails.version
=> "4.2.8"
> Ahoy::VERSION
=> "2.2.0"
```
Using **geocoder 1.5.0**.

And these are my initializers.

```ruby
module Ahoy
  class Store < Ahoy::DatabaseStore
    def track_visit(data)
      data[:ip] = request.headers['CF-Connecting-IP'] if request.headers['CF-Connecting-IP'].present? # because I'm using Cloudflare
      super(data)
    end

    def track_event(data)
      data[:properties][:subdomain] = request.subdomain
      data[:properties][:domain] = request.domain
      super(data)
    end
  end
end

Ahoy.api = true
Ahoy.geocode = true
```

```ruby
Geocoder.configure(
  lookup: :location_iq,
  api_key: ENV['LOCATION_IQ_ACCESS_TKN'],
  language: 'it',
  cache: Rails.cache,
  ip_lookup: :geoip2,
  geoip2: {
    file: Rails.root.join('lib', 'geocoder', 'GeoLite2-City.mmdb')
  }
)
```

Please help! 😅

**Comment by ankane** [comment]
Hey @darmenise, this seems like an issue with your Geocoder configuration. Please check out the Contributing Guide for where to get help.

**Comment by darmenise** [comment]
Thank you!
Anyway, I figured this out. The problem was that my default language is `it` but the GeoLite2-City.mmdb doesn't support Italian. So I just had to monkey patch `Geocoder::Result::Geoip2` to make it work :)

**Comment by darmenise** [comment]
This makes me think... how about relying on `location.latitude` presence instead of `location.country` presence [here](https://github.com/ankane/ahoy/blob/master/app/jobs/ahoy/geocode_v2_job.rb#L14)? 

Because in that case you still know wether location has been geocoded **but** latitude and longitude still get to be saved even if something with the other attributes didn't work out (case in point: an unsupported language was set). 

Would you like a PR?

**Comment by ankane** [comment]
I'm not sure latitude is always present. I doubt this situation is common enough to warrant a change.

**Comment by darmenise** [comment]
IMHO if I understood correctly the purpose of that line (that is, to verify wether `location` has been geocoded or not), `latitude` or `longitude` are more reliable than `country`, if not for other reasons, because they don't depend on the language.

You could also check the Geocoder API and verify that the coordinates (namely latitude and longitude) are the two main attributes that are set when geocoding is successful. See: https://github.com/alexreisner/geocoder#geocoding-objects 

Thank you in any case,
Duccio
