### ISSUE TITLE
Sanitize geo location data

### ISSUE THREAD

**Issue by TomK32** [ankane/ahoy#391]
First of all, I'm extremely happy with ahoy in my rails app. The data I need and nothing else :)

But, I notice that the geolocation data (I'm still using it via the API rather than a local db) is all over the place. E.g. for the german regions there is both "Baden-Wurttemberg" and "Baden-Württemberg Region", there's also "North Rhine-Westphalia" and "Nordrhein-Westfalen" which are both the same.

Does anybody have an advice for me to get those harmonized or will a local db do the trick? (if yes that should be noted in the README)

**Comment by ankane** [comment]
Hey @TomK32, I think your best option is to try another geocoding provider. However, I'm not sure how they'll compare.
