### ISSUE TITLE
Adding track once method, would that be valuable?

### ISSUE THREAD

**Issue by bo-oz** [ankane/ahoy#393]
For a site I'd like to track certain events only once in a users lifetime. Is there an easy way to achieve this, without keeping some kind of flag attribute on the user model? Would be great if Ahoy supported some kind of `ahoy.track_once` method, that creates an event only once per visitor. Is this something I can already do, or could this be interesting to add to the roadmap?

**Comment by ankane** [comment]
One option is to customize the data store to check the database for previous events (or do an upsert with on conflict do nothing). Typically, tracking all events is not an issue, and you can use SQL to fetch the first event if desired. What's the use case out of curiosity?

**Comment by bo-oz** [comment]
Eventually solved it by creating an extra method on my user model that queries the event model. I wanted to track when someone completes my 3 step registration, without having to worry about deduplication. So no longer an issue, although it could still be a nice feature.
