### ISSUE TITLE
[Idea] Grape support

### ISSUE THREAD

**Issue by leyb-opinya** [ankane/ahoy#395]
Hi,

I was very excited to use ahoy but it seems to demand that I'm in controller of some kind for it to work.
We work with the grape gem. I don't have ahoy there.
I also tried to use callbacks from devise, warden and rails (before/after commit/save) and no ahoy there =/

It'd be great to have a solution for this.

Thanks!

PS: for the record, it works great with active_admin gem =)

**Comment by ankane** [comment]
Hey @leyb-opinya, thanks for the suggestion. I don't use Grape, but happy to look at a PR if you can figure out how to make it work.
