### ISSUE TITLE
Rails Server IP showing in visits (skewing Geolocation)

### ISSUE THREAD

**Issue by chriscapetown** [ankane/ahoy#396]
Hi,

Just if anyone can point me in the right direction here. I'm getting alot of records created in 'ahoy_visits' with my server IP as the visiting IP, which skews Geo Location data when it comes to certain URL's I'm tracking.

Is there a way to prevent my server IP from used? I thought that only sending client-side visits (Ahoy.server_side_visits = false) would be the way, but it doesn't seem to help.

My configuration:

```
Ahoy.api = true
Ahoy.user_agent_parser = :device_detector
Ahoy.cookie_domain = :all
Ahoy.geocode = true
Ahoy.quiet = false
Ahoy.visit_duration = 4.hours
Ahoy.server_side_visits = false
```

Would appreciate any feedback! Thanks.

**Comment by ankane** [comment]
Hey @chriscapetown, this seems like a general question related to IP addresses in Rails.

**Comment by chriscapetown** [comment]
For those who come across this -- nginx proxy needed the following added:

outside server block:

```
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
```

inside "location /" block:

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Host $host;
```
