### ISSUE TITLE
Installing ahoy_matey breaks cancancan

### ISSUE THREAD

**Issue by ianrandmckenzie** [ankane/ahoy#397]
Hi there,

I'm working on a Rails application where I've decided to add `ahoy_matey` for download tracking. This application uses the `cancancan` gem (a user permissions gem that goes to 'Permission Denied' pages if the user doesn't have appropriate permissions), and I'm getting some bizarre behavior where any page within the application will, seemingly at random, give a Permission Denied error. This error goes away if I refresh the page. I know this isn't the cancancan repository, but these problems go away again if I remove the `ahoy_matey` gem.

I'm by no means blaming ahoy for this problem, but I was hoping I could get some help tracking down where exactly the problem is so I can attempt to fix it. I've scoured the internet for anyone who has had the same problem, and the only thing I've come across is this person's answer:
https://stackoverflow.com/a/39153224/2351224

They are claiming that the `cancancan` and `ahoy_matey` gems incorrectly monkey patch the Rails ActiveRecord functionality, and as far as I can find, this is my best lead. That being said, I haven't the slightest clue what to do with this information. If you have any insights or ideas, I'm a bit desperate to hear them, because I've reached a dead end with my searching and my coding ability.

Thank you for your time,

Ian

**Comment by ankane** [comment]
Hey @ianrandmckenzie, that specific issue was fixed in Ahoy in #213. Make sure you're on v1.5.2 or greater. If that doesn't solve it, I'm not sure what the issue could be.

**Comment by ianrandmckenzie** [comment]
I'm on 2.2.0, but no luck. I'm stumped. I've dug through the source and can't find anything that could possibly cause interference.

Anyway, thanks for the quick response.

**Comment by ianrandmckenzie** [comment]
I found a workaround that I thought I should mention here in case anyone runs into the same problem. What I ended up doing was forking this repo and editing `ahoy/lib/ahoy/controller.rb` to:

```
require "request_store"

module Ahoy
  module Controller
    def self.included(base)
      if base.respond_to?(:helper_method)
        base.helper_method :current_visit
        base.helper_method :ahoy
      end
      base.before_action :set_ahoy_cookies, unless: -> { Ahoy.api_only }
      # Disable tracking on all pages to circumvent cancancan issue
      # base.before_action :track_ahoy_visit, unless: -> { Ahoy.api_only }
      base.before_action :set_ahoy_request_store
...
```

Then, on the controller that I wanted actions tracked, I added:
```
class MyController < ApplicationController
  before_action :track_ahoy_visit, unless: -> { Ahoy.api_only }, only: [:show, :index]
...
```
