### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [ankane/ahoy#398]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by ankane** [comment]
Check out the repo.

**Comment by gustavosizilio** [comment]
Sorry, I gathered you project last year, on december 2018. Didnt checked that you have added travis. Added Travis - db2bd1c on Jan 4 -> **Is that the time you started using CI?**
