### ISSUE TITLE
[Idea] Reverse Proxy Support

### ISSUE THREAD

**Issue by jonmchan** [ankane/ahoy#402]
Many web applications are behind reverse proxies these days sending the real IP address of the request client in the headers. Logging just the `request.remote_ip` would always be only the IP of the reverse proxy server.

Could we add a feature to pull the IP address via a header option? The IP querying code seems very well isolated to a single function making this a pretty easy thing to add.

Something like:

https://github.com/ankane/ahoy/blob/aa93665b03544fe9cd17321431ba2d5d5afed507/lib/ahoy/visit_properties.rb#L94

```
    def ip
      if (@config.header_override_field) 
        ip = request.headers[@config.header_override_field]
      else
        ip = request.remote_ip
      end
      if ip && Ahoy.mask_ips
        Ahoy.mask_ip(ip)
      else
        ip
      end
    end
```

Though I would not be entirely sure how to pass the config options to the VisitProperties class.

There is only 2 more calls to `request.remote_ip` in https://github.com/ankane/ahoy/blob/aa93665b03544fe9cd17321431ba2d5d5afed507/lib/ahoy/tracker.rb#L245.  If all those 3 calls could be modified, you can have native proxy support. Hope you like the idea.

**Comment by ankane** [comment]
Hey @jonmchan, `request.remote_ip` handles proxies. You likely need to update the proxy configuration. Check out this discussion: https://stackoverflow.com/questions/10997005/whats-the-difference-between-request-remote-ip-and-request-ip-in-rails
