### ISSUE TITLE
Default properties

### ISSUE THREAD

**Issue by mklemme** [ankane/ahoy#403]
Hi! 

I wanted a way to handle default properties and thought I'd ask if that should be something included in the core library. Happy to open a PR if you point me in the right direction.

The basic idea is on load, I can initialize ahoy with some default properties that will be added to events generated.

Ex (maybe set on page load):
```js
ahoy.defaultProps({
  admin: false
})
```

Would create an event with:

```
name: '$view',
properties: {
  path: '/path',
  admin: false
}
```

**Comment by ankane** [comment]
Hey @mklemme, makes sense to me.

For JavaScript, was planning to add this to the Ahoy.js 1.0 release as a `setProperties` method, but never got around to it. Here's that repo: https://github.com/ankane/ahoy.js

**Comment by mklemme** [comment]
@ankane Perfect! I'll take this on and open the pr in [ankane/ahoy.js](https://github.com/ankane/ahoy.js) soon.

**Comment by mklemme** [comment]
View progress on this [here](https://github.com/ankane/ahoy.js/pull/38)
