### ISSUE TITLE
Cannot rollback generated migration

### ISSUE THREAD

**Issue by aok-solutions** [ankane/ahoy#404]
### Problem
After running `rails generate ahoy:install` this line is created in the migration file:
```
add_index :ahoy_events, "properties jsonb_path_ops", using: "gin"
```

If you run `rails db:migrate`, the index on the `ahoy_events` table looks like this (the name is wrong):
```
t.index ["properties"], name: "index_ahoy_events_on_properties_jsonb_path_ops", opclass: :jsonb_path_ops, using: :gin
```
so now if you try and  run `rails db:rollback` you will encounter the following error: 
```
StandardError: An error has occurred, this and all later migrations canceled:
No indexes found on ahoy_events with the options provided.
```

### Solution
In order for rollbacks to occur smoothly, the generated migration file should create the index like this:
```
add_index :ahoy_events, "properties", using: :gin, opclass: :jsonb_path_ops
```

**Comment by ankane** [comment]
Hey @aok-solutions, check out #365

**Comment by aok-solutions** [comment]
Ah, touché. Closing this then.
