### ISSUE TITLE
Segment-like ahoy add-on

### ISSUE THREAD

**Issue by mklemme** [ankane/ahoy#405]
This was just an idea but what do you think of core/add-on extension for ahoy to make it behave similar to services like segment.

```javascript
ahoy.track(event, props)
```

would create the local record but also send data upstream to external services like google analytics, mailchimp, etc.

**Comment by ankane** [comment]
Hey @mklemme, I have an unreleased library that does something like this. It basically allows you to define what happens when track is called. Another approach I’ve considered is adding an onTrack option to Ahoy.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by alexanderadam** [comment]
Does it mean you added the onTrack option to Ahoy?
