### ISSUE TITLE
track_visit + super

### ISSUE THREAD

**Issue by colinmccann** [ankane/ahoy#408]
I've added an additional field to the Visit model called 'visitor_email' (with a migration). I can manually create a Visit object with a visitor_email.

In config/initializers/ahoy.rb, I'm subscribing to the track_visit data store. Here, I want to add the user's email to the new Visit model. I can see that the attribute being add to the data hash before I call super. But I can also that it is never written to the visit model.

```
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore
  # customize here

  def track_visit(data)
    # new visit

    data[:visitor_email] = "example@email.com"
    super(data)
  end
end
```

I initially thought this might have something to do with the param not being permitted by the Visit controller. However, I cannot set any Visit field in track_visit (I've tried eg setting browser and utm_medium)

Am I misunderstanding something here? Or approaching this in the wrong way? I feel like this use case is ripped straight out of the README. I've also seen other examples that use different types of stores, and some that completely patch the track_visit method. Can I not use super?

**Comment by ankane** [comment]
Hey @colinmccann, it looks like you're on an earlier version of Ahoy - all the examples in the readme use `Ahoy::DatabaseStore`.
