### ISSUE TITLE
How to avoid being ignored as a bot in RSpec request specs

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy#412]
When upgrading from Ahoy v1 to v3 Version, many of my specs suddenly fail because the new Ahoy now considers my test controllers to be `bot?` requests

I know it's possible to keep the original bot implementation detector, but I'd like to upgrade if possible.

How do you suggest improve tests so that we can still test the persistence of Ahoy Events ?

Example of Rspec request spec that fail with v3 but would pass with v1 because of new bot detection

```ruby
def search_request
  get(api_v1_search_path, params: params, headers: headers)
end

it 'tracks the search results' do
  expect { search_request }.to change(Ahoy::Event, :count).by(1)
end
```

Based on the answer it would be nice to make a PR for documentation purposes

In the meantime I have to still use `Ahoy.bot_detection_version = 1`

**Comment by ankane** [comment]
You can use:

```ruby
Ahoy.track_bots = true
```

in your test/spec helper.

[Docs](https://github.com/ankane/ahoy#exclusions)
