### ISSUE TITLE
LoadError: No such file to load -- ahoy/base_controller

### ISSUE THREAD

**Issue by Vish-was** [ankane/ahoy#413]
On restarting delayed getting this error 

`LoadError: No such file to load -- ahoy/base_controller`

Gem is perfectly fine on rail 3.0 now upgrade to 4.2 
it throws error

**Comment by ankane** [comment]
Hey @Vish-was, I’m not familiar with that error, but the latest (and only supported) version of Ahoy requires Rails 5+
