### ISSUE TITLE
exclude_method not receiving request headers

### ISSUE THREAD

**Issue by larsthegeek** [ankane/ahoy#414]
It appears that the Ahoy.exclude_method does not receive the request object rather frequently and I am unable to create an effective guard clause.

I am using Ahoy v2.2.1

In my ahoy.rb initializer I have the following:

Ahoy.exclude_method = lambda do |controller, request|
  return if request.blank? || request.nil?

  request&.user_agent&.starts_with?('updown.io') || request&.user_agent&.starts_with?('python-requests') || request&.user_agent == 'WSWR' || request&.user_agent == 'MailChimp'
end

Initially, I didn't have the guard clause nor the ruby safe navigation but even with the guard clause this method doesn't seem to work at all as I continue to get loads of errors of the ilk:

**NoMethodError: [safely] undefined method `user_agent' for nil:NilClass (Most recent call first)**

As an added quirk, if I simply comment out the Ahoy.exclude_method I still get these errors.  I have to completely delete the exclude method to prevent it from being called.

I've looked through the code and cannot find the issue.  Any assistance would be delightful.

I am religiously restarting the server, etc., after making any config changes.  I can see the changes in the Rollbar error messages as well.

**Comment by ankane** [comment]
Hey @larsthegeek, there isn't much I can do to help without a reproducible example. Try upgrading to the latest version (v3.0.0) to see if you still have the issue.
