### ISSUE TITLE
Rails 6 rc2 deprecation warning for media_type (in Rails 6.1)

### ISSUE THREAD

**Issue by sqlninja** [ankane/ahoy#416]
Just noting that I am seeing the following deprecation warning, wouldn't say this is urgent yet since it's for 6.1...

`DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from set_ahoy_request_store at /Users/johnhenderson/.rvm/gems/ruby-2.6.3/gems/ahoy_matey-3.0.0/lib/ahoy/controller.rb:45)`

**Comment by ankane** [comment]
Hey @sqlninja, that line is a `yield` statement, so I think the deprecating warning is coming from somewhere in your app rather than Ahoy.

**Comment by sqlninja** [comment]
Thanks, noted...
