### ISSUE TITLE
track additional data

### ISSUE THREAD

**Issue by aksharj** [ankane/ahoy#417]
Hi @ankane,

many thanks for the great gem!

I am facing an issue in which I am trying to store screen resolution information with each visit. I have added this code to the sign up page `ahoy.configure({visitParams: {screen_resolution: '1920 x 1080'}});`  #the screen resolution is detected dynamically
 
and the visit table has a column named `screen_resolution`

Also, below is the code in the `initializers/ahoy.rb`

```
class Ahoy::Store < Ahoy::DatabaseStore
  def track_visit(data)
    data[:screen_resolution] = request.parameters["screen_resolution"]
    super(data)
  end
end
```

I don't see the parameter getting passed during visit creation and its not getting saved. Can you please let me know if I am doing something wrong & provide some guidance as to how I can achieve the same.

Thanks.

**Comment by ankane** [comment]
Hey @aksharj, the code looks right to me. Make sure you're on the latest version of Ahoy/Ahoy.js (earlier versions don't support `visitParams`). If that's not it, I'd try forking the library and adding debugging to see where the issue is.

**Comment by ankane** [comment]
Closing due to no response
