### ISSUE TITLE
Ahoy calling user_method in Rails::InfoController

### ISSUE THREAD

**Issue by ianrandmckenzie** [ankane/ahoy#419]
Hi there,

I am getting the following error when attempting to look up my routes in development:
```
NoMethodError in Rails::InfoController#routes
undefined method `helper_method' for ApplicationHelper:Module
```

It seems Ahoy is trying to get my user method (`current_website`) but because I am declaring it in my ApplicationController, the call creates an error because it is not scoped to the Rails::InfoController in any way.

This is obviously only an issue for the development environment, but the only way I can view routes at the moment is to either comment out my user_method or use the ugly printed output in the console.

**Comment by ankane** [comment]
Hey @ianrandmckenzie, not sure I follow. Can you paste the relevant Ahoy and ApplicationController code?

**Comment by ianrandmckenzie** [comment]
I think the problem is that the Rails::Info controller doesn't use any of the ApplicationController code, which is where `current_website` is defined. The error happens in this block:
```ruby
def user
      @user ||= begin
        if Ahoy.user_method.respond_to?(:call)
          Ahoy.user_method.call(controller)
        else
          controller.send(Ahoy.user_method)
        end
      end
    end
```

I don't know if I was just exhausted when I posted this, but when I replicate the bug now, I'm getting a different error:
`undefined method `current_website' for #<Rails::InfoController:0x00007f7f9e0b0d90> Did you mean? current_visit`

I'm starting to think maybe my problem is that my `current_website` helper method only being available from `ApplicationController` is the problem because Ahoy is trying to get `current_website` independently from any controller?

**Comment by ankane** [comment]
Yeah, that sounds like the issue. How are you calling Ahoy from the `Rails::InfoController`?

**Comment by ianrandmckenzie** [comment]
I don't even know how to edit the `Rails::InfoController` — I assume it's some component of Rails that is only available in `RAILS_ENV=development`.

If you go to `localhost:3000/rails/info/routes` you can see the controller in question in action.

**Comment by ankane** [comment]
Thanks for the additional info. Give master a shot.

**Comment by ianrandmckenzie** [comment]
Amazing! Thanks @ankane
