### ISSUE TITLE
Consecutive visits not tracked

### ISSUE THREAD

**Issue by martijndekuijper** [ankane/ahoy#420]
Hi y'all,

Somehow I can't get ahoy to track consecutive visits. The first visit is tracked, but after that it doesn't tracking anything anymore. When I remove the ahoy cookies, it does track one visit again. Any idea what I'm doing wrong?

I also want to "opt-in" to the tracking, so I thought I'd use the `api_only` option, but then there's no `visitor_token` and `visit_token`. How can I fix this?

Thanks, Martijn

**Comment by ankane** [comment]
Hey @martijndekuijper,

1. A visit is a session, which is why a new one isn't created on every request. It sounds like you want to use events instead.

2. For opt-in tracking, use a custom exclude method.

If you additional help, please check out the Contributing Guide.

**Comment by martijndekuijper** [comment]
Thanks Andrew,

Sorry, I didn't realize it worked that way. I thought all page visits would be tracked and that events are, well... events :) Thanks for clarifying! 🙏

Martijn
