### ISSUE TITLE
Tracking Outbound links

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy#421]
Does this gem or Ahoy.JS track outbound link stats?

**Comment by ankane** [comment]
Hey @ACPK, I'm not sure I understand the question. Can you elaborate?

**Comment by ankane** [comment]
Yes, click tracking in JavaScript works on outbound links.

**Comment by kevinhq** [comment]
> Yes, click tracking in JavaScript works on outbound links.

It doesn't save the data anywhere. Can you point me to working sample?
