### ISSUE TITLE
GDPR Compliance feature stopped working — add user_id to Visit and Event

### ISSUE THREAD

**Issue by efojs** [ankane/ahoy#423]
I have project on **Rails 5.2** with **Ahoy 2.1.0** — it does not track `user_id` both for Visits and Events, as intended by applying:
```
# config/initializers/ahoy.rb
def authenticate(data)
    # disables automatic linking of visits and users
end
Ahoy.mask_ips = true
Ahoy.cookies = false
Ahoy.api = false  # I don't use JS tracking.
```

Now, trying to implement the same behaviour for **Rails 6.1**, I installed **Ahoy 3.0.0**, added same instructions to `config/initializers/ahoy.rb` — it adds `user_id` to Visits and Events.

Pinned gem to `ankane/ahoy` — same.

**Ruby 2.5.5**
**Rails 6.1.0.alpha @ b1c27c0@b1c27c0**
**Devise 4.6.2 @ master@9aa17ee**

Am I missing something, or is it something you can see from my description, or should I create test app?

**Comment by ankane** [comment]
Hey @efojs, the `authenticate` method needs to go inside `Ahoy::Store` as shown in the documentation.

**Comment by efojs** [comment]
Sorry, I didn't show it (because class added by default), but it goes there:
```
class Ahoy::Store < Ahoy::DatabaseStore
  def authenticate(data)
    # disables automatic linking of visits and users
  end
end
```
And it's working in old version.

**Comment by efojs** [comment]
I've created test app — [efojs/ahoy-gdpr](https://github.com/efojs/ahoy-gdpr) — with GDPR feature in [config/initializers/ahoy.rb](https://github.com/efojs/ahoy-gdpr/blob/master/config/initializers/ahoy.rb)

Same problem — it tracks user_id:

![image](https://user-images.githubusercontent.com/4446937/63231921-26b09600-c22b-11e9-9926-14dd2ad42f1d.png)

**Comment by ankane** [comment]
Hey @efojs, thanks for putting that together, but unfortunately, Ahoy won't support Rails 6.1 until the final release (and possibly release candidates).

**Comment by efojs** [comment]
Ah, OK, I see, it makes sense) thank you for what you do!
