### ISSUE TITLE
Associate a model with many visits

### ISSUE THREAD

**Issue by willianveiga** [ankane/ahoy#424]
Right now, [it seems to be possible to associate a model with a single visit object](https://github.com/ankane/ahoy/blob/6409f3152afa882659a02f95644e3ac928f7dcb6/lib/ahoy/model.rb#L5).

To work around this limitation, I've implemented the following userland code:

Tracking visits:

```
# ...
def show
  ahoy.track("Post view", @post.id)
end
# ...
```

Getting visits associated with a single model:

```
# ...
Post.select(
  'posts.id, ' \
    'COUNT(DISTINCT ahoy_events.id) AS visits, ' \
    'COUNT(DISTINCT ahoy_events.visit_id) AS unique_visits'
).joins(
  'INNER JOIN ahoy_events ON posts.id::TEXT = ahoy_events.properties::TEXT ' \
    'AND ahoy_events.user_id IS NULL'
).group('posts.id')
# ...
```

It works fine, but it would be great to have an interface provided by the lib. Like [the interface provided for a single associated model](https://github.com/ankane/ahoy#associated-models) and [querying](https://github.com/ankane/ahoy#querying-events).

**Comment by ankane** [comment]
Hey @willianveiga, thanks for the suggestion. Since it's already possible to do this by either customizing the store and/or creating an additional table, I don't think another method is needed.
