### ISSUE TITLE
Same IP and location details always

### ISSUE THREAD

**Issue by aksharj** [ankane/ahoy#427]
Hi All,

I have integrated the ahoy gem in our rails 5 application and it works really well. I am however seeing a weird issue related to getting IP address and location details. I see that the location details are always same even when users are accessing the application from different locations. I have integrated the geocoder gem as specified in the documentation.

The country is always `United States`, the state is always `California` & city is always `Mountain View` and event the lattitude and longitude details are always the same.

Any help in fixing this would be really great, many thanks.

**Comment by ankane** [comment]
Hey @aksharj, the root of the problem is the incorrect IP address (as geocoding will return the same results for the same IP). This is likely due to an issue with how a proxy server is configured. Check out out #402 and #396 for more info.
