### ISSUE TITLE
Ahoy on Serverless

### ISSUE THREAD

**Issue by nabilfreeman** [ankane/ahoy#428]
Hey there,

We run a Node.js stack but love Ahoy so much that we are running a Rails app on the side just to use it for analytics!!

After successfully moving the rest of our tech to serverless on Lambda and seeing enormous cost & concurrency benefits I thought Ahoy could also benefit from it.

Anybody tried?

I found Ruby on Jets: https://blog.boltops.com/2018/12/21/jets-afterburner-serverless-rails-on-aws-lambda-in-5-minutes which promises an easy solution to getting Rails on Lambda but I'm wondering what cold starts etc are like.

I also looked at writing a JS server port of Ahoy specifically for Lambda but I don't think it's worth the effort considering how amazing this library already is.

**Comment by ankane** [comment]
Hey @nabilfreeman, I haven't tried running Ahoy on Lambda myself, but will leave this open for a bit in case others want to jump in (however, there's typically not a lot of chatter here).

**Comment by ankane** [comment]
Cleaning up issues
