### ISSUE TITLE
Changing the path to record events

### ISSUE THREAD

**Issue by abrambailey** [ankane/ahoy#431]
I would like to change the path from /ahoy/events to /foober/events

I tried doing mount `Ahoy::Engine => "/foober", as: :my_ahoy` in routes

and 
```ruby
class Ahoy::Store < Ahoy::DatabaseStore
  mattr_accessor :auto_mount
  self.auto_mount = false
end
```
but this didn't seem to change anything

**Comment by pelletencate** [comment]
@ankane Especially now that `/ahoy/events` and `ahoy/visits` [have made it to EasyPrivacy](https://easylist.to/easylist/easyprivacy.txt), it would be nice to be able to configure the path.

**Comment by abrambailey** [comment]
Yes, in my testing it seems that /ahoy/ is a commonly blocked path rendering this software almost useless in terms of basic traffic reporting.

**Comment by ankane** [comment]
You can manually mount the engine to any path with:

```ruby
mount Ahoy::Engine => "/ahoy2"
```

And configure the JavaScript library accordingly.

**Comment by abrambailey** [comment]
"And configure the JavaScript library accordingly."

What does that entail exactly? Is there a wiki somewhere for this?

**Comment by ankane** [comment]
https://github.com/ankane/ahoy.js#configuration

**Comment by abrambailey** [comment]
Great thanks !
