### ISSUE TITLE
declare module 'ahoy.js

### ISSUE THREAD

**Issue by Tioneb12** [ankane/ahoy#433]
I have the following message when I try to install Ahoy :

```
Could not find a declaration file for module 'ahoy.js'. 
'...... /node_modules/ahoy.js/dist/ahoy.js' implicitly has an 'any' type.
  Try `npm install @types/ahoy.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'ahoy.js';`
```

How can I fix it ?

ruby = 2.6.5
rails = 6.0.2.1

**Comment by ankane** [comment]
Hey @Tioneb12, Ahoy.js doesn't have TypeScript definitions, so you'll need to disable type-checking. Check out https://stackoverflow.com/questions/56688893/how-to-use-a-module-when-it-could-not-find-a-declaration-file
