### ISSUE TITLE
Event can't reference a polymorphic user

### ISSUE THREAD

**Issue by darmenise** [ankane/ahoy#434]
Hello, 
I'm not very familiar with this codebase but I'm trying to setup Ahoy to work with polymorphic users.

The `Ahoy::Visit` works well, all I needed to do was to add the `user_type` column and the `belongs_to :user, polymorphic: true` option to it.

So I figured that it will be easy with `Ahoy::Event` as well but, it wasn't. It keeped saving only the `user_id` and never the `user_type`. So I found this line:
https://github.com/ankane/ahoy/blob/13f029f457fb79f910e41d7a64accebe4012814d/lib/ahoy/tracker.rb#L26

It seems that it sets only the `user_id` before saving the event. 

Anyway, I got it working with a simple workaround. 
I'm using this `before_validation` callback in the `Ahoy::Event`:

```ruby
before_validation :set_user_from_visit
[...]

def set_user_from_visit
  return true unless visit&.user&.present?
  self.user   = visit.user
end
```

But is not ideal. So, is it possible to have the `Event` working with a polymorphic user, as `Visit` does, without needing this callback?

Thank you,
Duccio

**Comment by ankane** [comment]
Hey @darmenise, you can access the `user` object in your Ahoy store.

```ruby
class Ahoy::Store < Ahoy::DatabaseStore
  def track(data)
    data.delete(:user_id)
    data[:user] = user
    super(data)
  end
end
```

**Comment by darmenise** [comment]
Oh, ok, thank you @ankane!

Wouldn'it be better to change [ahoy/lib/ahoy/tracker.rb#L27](https://github.com/ankane/ahoy/blob/master/lib/ahoy/tracker.rb#L27) in:

```ruby
  user: user
```
So that `Event` could be polymorphic out-of-the-box like `Visit`?

**Comment by ankane** [comment]
Ah, you're right, it must be `user_type`. Thanks for following up!
