### ISSUE TITLE
Having trouble turning off cookies for specific endpoints

### ISSUE THREAD

**Issue by durkie** [ankane/ahoy#435]
Hello -- thanks for creating such a useful gem. I really appreciate your effort.

I'm using Ahoy 3.0.1 with Rails 6 and would like to turn off cookies for certain endpoints to let Cloudflare cache some results upstream (they apparently will not cache endpoints that set cookies). 

I've tried `skip_before_action :track_ahoy_visit` in top-level of my controller, but am not having much luck with it: I'm still seeing `ahoy_visit` and `ahoy_visitor` cookies being set. 

My `config/initializers/ahoy.rb` file is below, and modified somewhat to allow for multiple databases:
```
class Ahoy::Store < Ahoy::DatabaseStore
  def track_visit(data)
    ActiveRecord::Base.connected_to(role: :writing) do
      super(data)
    end
  end

  def track_event(data)
    ActiveRecord::Base.connected_to(role: :writing) do
      super(data)
    end
  end
end

# set to true for JavaScript tracking
Ahoy.api = false
Ahoy.geocode = false
```

is there anything I'm missing?

**Comment by ankane** [comment]
Hey @durkie, you'll also need to skip `set_ahoy_cookies`. Check out https://github.com/ankane/ahoy/blob/master/lib/ahoy/controller.rb.

**Comment by durkie** [comment]
That's what I'm missing -- thanks so much!
