### ISSUE TITLE
[Idea] Ability to set SameSite and Secure attributes on cookies

### ISSUE THREAD

**Issue by zminot** [ankane/ahoy#436]
Hi!

Chrome has been issuing warnings about setting the default `SameSite` attribute for cookies to be `Lax` instead of `None` for cookies without the SameSite attribute. From my understanding, in ahoy, there is no current way to configure ahoy's cookie's `SameSite` and `Secure` attributes.

Is this planned to allow the configuration of ahoy cookies `SameSite/Secure` attributes?

**Comment by ankane** [comment]
Hey @zminot, thanks for the suggestion. We could add `Ahoy.cookie_options` to set these and [other values](https://api.rubyonrails.org/classes/ActionDispatch/Cookies.html) users may want to change.

```ruby
Ahoy.cookie_options = {domain: ..., secure: true, httponly: true, ...}
```

A few notes:

- `Secure` is set automatically for all cookies with `force_ssl`, which is preferred
- Rails doesn't currently provide a way to set `SameSite`. It was backported to 6.0 but hasn't been released yet. See https://github.com/rails/rails/pull/28297

**Comment by zminot** [comment]
I think Rails 6.0 already supports it because at least in the [changelog](https://github.com/rails/rails/blob/master/actionpack/CHANGELOG.md) it says that

> NB: Technically already possible as Rack supports SameSite protection, this is to ensure it's applied to all cookies

but I may be wrong (also I am able to set SameSite locally running Rails ~> 6.0).

**Comment by ankane** [comment]
Added on master by @zminot in #438 🎉
