### ISSUE TITLE
Events are not retrofitted with the user_id from the visit after login

### ISSUE THREAD

**Issue by bo-oz** [ankane/ahoy#437]
In the documentation it is stated that after a login, we are still able to track all events that happened before the login event. While this is technically true, the implementation could be somewhat improved by retrofitting all the event records with the user_id after the login event took place.

Currently only events that happen after the login is set, are stamped with the user_id. This means that when calling `current_user.events` it will only show the events that happened after login. While accessing the AR collection from the visit does contain all the events.

Could it maybe be a solution to implement an after_save callback on the `Ahoy::Visit` class that updates all related events with the user_id? Or are there any strong arguments why this behavior would be unwanted?

Happy to write a PR for this, but would like to understand if there's any objection against this approach.

**Comment by bo-oz** [comment]
Also, I found that the `user_id` is not set consistently when using the suggested `after_action` callback. Any idea why for some requests it doesn't set the `user_id` even though the user is logged in?

`
  def track_action
    ahoy.track 'Ran action', request.path_parameters
  end
`

**Comment by ankane** [comment]
Hey @bo-oz, the `user_id` field on events indicates if the user was logged in when the event occurred. You can join with the visit and query on the visit `user_id` if needed (or have an app-specific callback to update events like you mention), but I'd prefer not to change the existing behavior.
