### ISSUE TITLE
[Question] Scope by resource associated with domain

### ISSUE THREAD

**Issue by vitobotta** [ankane/ahoy#439]
Hi! I'm thinking of using this gem in my app, but I'm not sure about one thing. I'm building a CMS for blogs where each blog has a subdomain of the app's main domain, as well as one or more custom domains. Therefore I would need to combine or group visits and page views by blog rather than the single domain. Is this possible with ahoy? Thanks a lot in advance!

**Comment by ankane** [comment]
Hey @vitobotta, Ahoy is pretty flexible, so you should be able to do this. Check out the Contributing Guide for where to get additional help if needed.
