### ISSUE TITLE
Visits with duplicate tokens

### ISSUE THREAD

**Issue by pelletencate** [ankane/ahoy#441]
I have a Visit table with about 15 million records, as such, I've got about 15 million visit tokens. All tokens seem to be UUID's generated by Ahoy. My visits are set to expire after 2 hours

I ran a query that shows that I have now 39 visits in my database that lasted longer than a year. It turns out that they all represent two (or more) different visits that just seem to have drawn the same UUID, but represent completely different users in different parts of the globe.

I refuse to believe that out of about 15 million UUID's, I've got 39 collisions, unless there is something seriously wrong with the generator that's being used. Is there another possible explanation for this?

Also, do you believe it would be useful to have ahoy_events validate the age of the visit, i.e. if ahoy's visit expiration time is 2 hours, should an ahoy event check for the last event posted on a visit, and do something (force a new visit, or even raise an exception) if it's out of time?

**Comment by ankane** [comment]
Hey @pelletencate, thanks for reporting. It's possible a bot (that spoofs its user agent) is reusing visit tokens at a later time, or a misbehaving browser is ignoring cookie expiration. Overall, 39 out of 15 million is an extremely low percentage, so I don't think it makes sense to make changes for it. You can add custom logic in `Ahoy::Store` to raise an exception or skip tracking for your specific application if desired.
