### ISSUE TITLE
visitable cannot accept a customized Visit class

### ISSUE THREAD

**Issue by kofronpi** [ankane/ahoy#442]
Hello, the code here:

https://github.com/ankane/ahoy/blob/6409f3152afa882659a02f95644e3ac928f7dcb6/lib/ahoy/model.rb#L5

cannot accept a customized `Visit` class.

To reproduce with a `Visit` model in `app/models` (without `Ahoy` module), write this in `config/initializers/ahoy.rb`:

```
class Ahoy::Store < Ahoy::DatabaseStore
  def visit_model
    Visit
  end
end
```
`visitable` now breaks on any model:

```
19:16:15 web.1       | Completed 500 Internal Server Error in 161ms (ActiveRecord: 36.1ms)
19:16:15 web.1       | 
19:16:15 web.1       | 
19:16:15 web.1       |   
19:16:15 web.1       | NameError (uninitialized constant MyModel::Ahoy::Visit):
19:16:15 web.1       |   
19:16:15 web.1       | (eval):3:in `set_ahoy_visit'
```

I use ahoy 3.0.1.

**Comment by ankane** [comment]
Hey @kofronpi, you can use `visitable class_name: "Visit"`.
