### ISSUE TITLE
[IDEA] Allow to track sessions on Rails API only projects

### ISSUE THREAD

**Issue by lauer** [ankane/ahoy#443]
Hi, 

I have a project with Rails 6 API only and React frontend, using Device and JWT as authentication. 
It would be great if I somehow could track manage a visit_token to be the same as long as the JWT bearer authentication token stays the same. 

Today, two different users get the same `visitor_token` if they come from the same mask IP and using the same browser user agent. That does not make sense. 

There must be a line between Anonymity Sets and not using cookies, but still track different user sessions. 

Currently, I have this setup:

```
Ahoy.api = false
Ahoy.api_only = true
Ahoy.cookies = false
Ahoy.mask_ips = true
Ahoy.geocode = false
```

**Comment by ankane** [comment]
Hey @lauer, thanks for the suggestion. I'm not sure this is common enough to add right now, but you should be able to fork and update the logic in `Ahoy::Tracker` to accomplish this.

**Comment by lauer** [comment]
I see that it might be a special case. 

Maybe the Authentication header, could be used to generate a visit token, which would be the same as long as the session says the same. 
But then, how could I define a visitor, if it isn't defined by the username.
My API is login only access, and the above suggestion wouldn't work for open APIs.

**Comment by ankane** [comment]
If you decide to fork, feel free to share what you come up with.

**Comment by ACPK** [comment]
@lauer - Did you come up a solution to your issues which was using a UUID?

**Comment by baaart** [comment]
@lauer - same here, did you manage to come up with some fix?
