### ISSUE TITLE
uninitialized constant Ahoy::GeocodeV2Job

### ISSUE THREAD

**Issue by microdevil** [ankane/ahoy#444]
Hi,

I have implemented ahoy to track our users. However, I got this error when I implement it in production.

uninitialized constant Ahoy::GeocodeV2Job

Can anyone help me solve this issue?

Thanks!

**Comment by ankane** [comment]
Hey @microdevil, can you paste the stack trace?

**Comment by microdevil** [comment]
> Hey @microdevil, can you paste the stack trace?

`A NameError occurred in background at 2020-05-29 13:02:55 UTC :

  uninitialized constant Ahoy::GeocodeV2Job
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:285:in 'const_get'

-------------------------------
Backtrace:
-------------------------------

  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:285:in 'const_get'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:285:in 'block in constantize'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in 'each'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in 'inject'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in 'constantize'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/core_ext/string/inflections.rb:68:in 'constantize'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/core.rb:41:in 'deserialize'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/execution.rb:23:in 'block in execute'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in 'block in run_callbacks'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/railtie.rb:28:in 'block (4 levels) in <class:Railtie>'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in 'wrap'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in 'block in wrap'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in 'wrap'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in 'wrap'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/railtie.rb:27:in 'block (3 levels) in <class:Railtie>'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in 'instance_exec'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in 'block in run_callbacks'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in 'run_callbacks'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/execution.rb:22:in 'execute'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/activejob-5.2.3/lib/active_job/queue_adapters/resque_adapter.rb:47:in 'perform'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/job.rb:168:in 'perform'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:308:in 'perform'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:897:in 'block in perform_with_fork'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:895:in 'fork'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:895:in 'perform_with_fork'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:264:in 'work_one_job'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:238:in 'block in work'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:235:in 'loop'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/worker.rb:235:in 'work'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/resque-2.0.0/lib/resque/tasks.rb:20:in 'block (2 levels) in <top (required)>'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:273:in 'block in execute'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:273:in 'each'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:273:in 'execute'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:214:in 'block in invoke_with_call_chain'
  /home/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in 'mon_synchronize'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:194:in 'invoke_with_call_chain'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/task.rb:183:in 'invoke'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:160:in 'invoke_task'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:116:in 'block (2 levels) in top_level'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:116:in 'each'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:116:in 'block in top_level'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:125:in 'run_with_threads'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:110:in 'top_level'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:83:in 'block in run'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:186:in 'standard_exception_handling'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/lib/rake/application.rb:80:in 'run'
  /home/user/.rvm/gems/ruby-2.6.3@app/gems/rake-12.3.3/exe/rake:27:in '<top (required)>'
  /home/user/.rvm/gems/ruby-2.6.3@app/bin/rake:23:in 'load'
  /home/user/.rvm/gems/ruby-2.6.3@app/bin/rake:23:in '<main>'
  /home/user/.rvm/gems/ruby-2.6.3@app/bin/ruby_executable_hooks:24:in 'eval'
  /home/user/.rvm/gems/ruby-2.6.3@app/bin/ruby_executable_hooks:24:in '<main>'
`

**Comment by ankane** [comment]
It looks like the code with Ahoy wasn't deployed to the worker server.

**Comment by microdevil** [comment]
> It looks like the code with Ahoy wasn't deployed to the worker server.

Do you have an idea to solve this issue ?

I think the main issue are coming from resque services that could not implement Ahoy.

**Comment by ankane** [comment]
You'll need to add Ahoy to the code that's running on workers or disable geocoding (instructions in readme). There's probably an unofficial way to change the queue adapter for the job to run it inline as well, but will leave that to you to figure out if that's the direction you decide to go. Check out the Contributing Guide for where to get additional help.
