### ISSUE TITLE
[Idea] Storing utm_id

### ISSUE THREAD

**Issue by gmanley** [ankane/ahoy#445]
Hello,

Currently utm_id is not tracked. It seems to be a standard utm tag [according to google](https://support.google.com/analytics/answer/6066741?hl=en ). 

I monkey patched it for my project, but that is not ideal.
Would you accept a PR adding it? If so, should I update the migration as well? I'd make it backward compatible.

I was also considering making [this array](https://github.com/ankane/ahoy/blob/master/lib/ahoy/visit_properties.rb#L33) a configurable option, with a default, instead.  Would that be preferred?

Any thoughts on better alternatives? I'm willing to do the work.

**Comment by ankane** [comment]
Hey @gmanley, thanks for the suggestion and offer to contribute! I'm not sure `utm_id` is as popular as the others, so I don't think it makes sense to include it by default. Users who need it should be able to add it cleanly by tracking additional data: https://github.com/ankane/ahoy#track-additional-data

**Comment by gmanley** [comment]
@ankane That is a lot cleaner than a monkey patch. I didn't realize it would work with a new column. Thank you!
