### ISSUE TITLE
User id blank for ahoy_visits

### ISSUE THREAD

**Issue by aksharj** [ankane/ahoy#448]
Hi All,

My apologies if this is something very simple and may be i might be missing something.

There are many cases I am seeing where there is no user_id associated with visits and i am not sure if its an issue or may be something in configuration I have done wrong.

I am on `Rails 5.2.3`

below is my ahoy/visit.rb
```
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end
```
Any help in how to fix this will be great.

Thanks.

**Comment by ankane** [comment]
Hey @aksharj, that column will be `nil` for non-logged in users.
