### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/ahoy#450]
Ideas

- [ ] (breaking) Use `:default` job queue instead of `:ahoy` by default

**Comment by andrisole92** [comment]
1. Probably not closing open issues.

**Comment by ringofhealth** [comment]
make ahoy.track async on the serverside, either with fork or job, as if you run ahoy.track in the ruby code, it blocks view from rendering to the client

**Comment by andresakata** [comment]
Hi :wave: Is it possible to establish a polymorphic association between the visit and the "user"? If not, is there any workaround for systems that have more than one authenticated model?

**Comment by ankane** [comment]
@ringofhealth Sorry for the delay. Check out #344.

@andresakata You should be able to add `user_type` columns and update `belongs_to` in the models.

**Comment by ankane** [comment]
Also, closing this out, as I'm moving ideas to a new issue.
