### ISSUE TITLE
track_visits_immediately causes undefined method

### ISSUE THREAD

**Issue by martino-dot** [ankane/ahoy#452]
When I try and add ```Ahoy.track_visits_immediately = true``` to ```ahoy.rb``` it tells me ```undefined method `track_visits_immediately=' for Ahoy:Module```. If I remove it from the file it works fine.

Steps to reproduce:
* Add ahoy to project (from master branch)
* Run all the migrations and first time installation
* Add ```Ahoy.track_visits_immediately = true``` to ahoy's initializer
* Run the server

**Comment by ankane** [comment]
Hey @martino-dot, `Ahoy.track_visits_immediately` was replaced by `Ahoy.server_side_visits` in Ahoy 2.0 and `true` became the default, so you can remove that line. See the changelog for more info on the changes between Ahoy 1 and the current version.
