### ISSUE TITLE
Mysql Older Version Do not support Json Data Type ahoy_events table

### ISSUE THREAD

**Issue by ak15** [ankane/ahoy#454]
For MySql(< 5.7) Database especially InnoDB which does not have support for native json datatype will have issues after migration of ahoy_events due to [this condition](https://github.com/ankane/ahoy/blob/master/lib/generators/ahoy/activerecord_generator.rb#L25).

I am not sure if someone else too came with this problem, I faced it for my Heroku Application manually changed it to text and  using ActiveRecord#serialize

**Comment by ankane** [comment]
Hey @ak15, thanks for sharing. That approach should work fine. Since MySQL 5.6 is older at this point, I don't think it makes sense to make any changes to the repo for it.

**Comment by ak15** [comment]
Thanks

**Comment by charlietag** [comment]
@ak15 
I found a way here, #463

**Comment by ak15** [comment]
> @ak15
> I found a way here, #463

I appreciate your suggestion but for us we had to change the datatype in migration for the older database to text and then
user Rails serializer
