### ISSUE TITLE
Is it normal to be this slow?

### ISSUE THREAD

**Issue by kevinhq** [ankane/ahoy#455]
```
 SELECT count(*) FROM ahoy_events
 WHERE name = 'event_name' AND (JSON_UNQUOTE(properties -> '$.id') = 123) 
 GROUP BY user_id, DATE(time) ;
```

and it returns

```
19 rows in set (0.66 sec)
```

Is it normal to be that slow? More than half seconds for such query?

**Comment by kevinhq** [comment]
So, we ended up adding index with virtual column to that json column. It's running instantly now. Will update details soon

**Comment by ankane** [comment]
Hey @kevinhq, queries can become slower as the table grows. You can use `EXPLAIN` with relational databases to better understand the performance of queries and indexes to improve performance (as you mentioned).
