### ISSUE TITLE
Client side doesn't work when server in production mode

### ISSUE THREAD

**Issue by XXChester** [ankane/ahoy#456]
When I run my rails env with RAILS_ENV=development my client side (javascript) track calls properly save to the database but when I use RAILS_ENV=production client side events stop logging to the database.

Looking at the network pane in dev tools I don't see an outgoing API call related to ahoy. How do we get this to work in production? It's so simple and lightweight, I love it and I'd hate to change.

**Comment by ankane** [comment]
Hey @XXChester, unfortunately, I'm not sure how to reproduce with the info provided. Many apps use Ahoy in production, so I think it's specific to your application. Check out the Contributing Guide for where to get help.
