### ISSUE TITLE
Getting undefined error with Webpacker in Rails 6

### ISSUE THREAD

**Issue by davidlesches** [ankane/ahoy#457]
First time using Rails 6 and Webpacker, I've run `yarn add ahoy.js`, and added `require("ahoy.js")` to packs/application.js, but trying to call ahoy in my javascript or console window triggers a "Uncaught ReferenceError: ahoy is not defined" error.

Am I doing something wrong?

**Comment by davidlesches** [comment]
Never mind, got it. Thanks!

**Comment by xaviablaza** [comment]
What did you do to resolve this? @davidlesches

**Comment by davidlesches** [comment]
@xaviablaza If you want to call ahoy from anywhere like the console window you'll need to do this 

```
import ahoy from "ahoy.js";
window.ahoy = ahoy;
```

Better to keep it in a class/file though, like in app/javascript/src make a file called tracking.js with something like 

```
import ahoy from "ahoy.js";

document.addEventListener("turbolinks:load", function() {
  ahoy.doWhatever();
});
```
