### ISSUE TITLE
Customizable mount path

### ISSUE THREAD

**Issue by jukkakoskinen** [ankane/ahoy#46]
First, thank you for such a great gem and its JS cousin!

Second, is there any way to customize the engine's mount path (e.g. /ahoy => /tracking)? Or rather, is there way to disable auto-mounting? This is only a very minor problem though. :smile:

**Comment by yega** [comment]
At this moment you can chage mount path:

before call ahoy.js
```javascript
var ahoy = {"eventsUrl": "/stats/events", "visitsUrl": "/stats/visits"};
```

in route.rb
```ruby
mount Ahoy::Engine => "/tracking"
```

**Comment by jukkakoskinen** [comment]
Thanks @yega, and sorry for the late response.
