### ISSUE TITLE
How to trigger ahoy.track from a model ?

### ISSUE THREAD

**Issue by leoplct** [ankane/ahoy#460]
Hi,

I have to trigger the event _ahoy.track 'User Sign up'_  in the User.after_create callback.
I want to avoid to call it in a controller (eg. thank you page). 

```
after_create do
  ahoy.track(user_id: self.id, name: 'User Sign up')
end 
```
Error: ahoy is not defined.

**Comment by ankane** [comment]
Hey @leoplct, Ahoy doesn't have an official method to access the `ahoy` object in a model. Unofficially (which could break at any time), you can use `Thread.current[:ahoy]`.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by ankane** [comment]
Just added an official method for this on master - `Ahoy.instance` . It'll only be set if the model is used in a controller context, so you'll need to make sure your code handles the case when it's `nil`.

```ruby
after_create do
  ahoy = Ahoy.instance
  ahoy.track(user_id: self.id, name: 'User Sign up') if ahoy
end 
```

**Comment by leoplct** [comment]
Thank you. 
I need to trigger an event when an ActiveJob is completed. Do you think this is the best approch?

**Comment by suupic** [comment]
I have meet the same issue, and fixed like this:

##### add a new method to module Ahoy, it create a fake visit and track events
```
# config/initializers/ahoy.rb
module Ahoy
  def self.non_visit_track(event_name, visit_properties: {}, event_properties: {})
    visitor = Ahoy::Visit.create(visit_properties)
    visitor.events.create(name: event_name, time: Time.now, properties: event_properties)
  end
end
```
and call it anywhere
```
Ahoy.non_visit_track(AppEvent::MembershipTransfer,
        visit_properties: { user_agent: 'Rails Console' },
        event_properties: { from_user_id: from_user.id, to_user_id: target_user.id })
```

> 



> Thank you. I need to trigger an event when an ActiveJob is completed. Do you think this is the best approch?
> 
> I have updated to last version and run it from console but I got nil.
> 
> ```
> Running via Spring preloader in process 6612
> Loading development environment (Rails 6.0.3.4)
> irb(main):001:0> Ahoy.instance
> => nil
> ```
