### ISSUE TITLE
Tracking additional fields for Visits

### ISSUE THREAD

**Issue by leoplct** [ankane/ahoy#461]
I have edited this method to track the "language"

config/initializers/ahoy.rb
```
class Ahoy::Store < Ahoy::DatabaseStore
    def track_visit(data)
        puts "TRACK VISIT"
        data[:accept_language] = request.headers["Accept-Language"]
        super(data)
    end
end

# set to true for JavaScript tracking
Ahoy.api        = false
Ahoy.geocode    = true
Ahoy.job_queue  = :low
Ahoy.track_bots = false
```

This method is called but how do I access the "accept_language" value?
`Ahoy::Visit.last.accept_language`
NoMethodError (undefined method `accept_language' for #<Ahoy::Visit:0x00007ffe7d985688>)

**Comment by iamajvillalobos** [comment]
I think you need to add a new field in the `ahoy_visits` table for `accept_language` since it's not supported by default

**Comment by leoplct** [comment]
Thank you solved.

```
class AddLanguageToAhoyVisits < ActiveRecord::Migration[6.0]
  def change
    add_column :ahoy_visits, :accept_language, :string
  end
end
```
