### ISSUE TITLE
[FIX] Since properties column type is json, but this line does not convert output to json content

### ISSUE THREAD

**Issue by charlietag** [ankane/ahoy#463]
https://github.com/ankane/ahoy/blob/331121821de8eaf4c0676919e828481618ad2aa2/lib/ahoy/tracker.rb#L29

```diff
- properties: properties,
+ properties: properties.to_json,
```

**Comment by ankane** [comment]
Hey @charlietag, Active Record should automatically serialize JSON columns.

**Comment by ankane** [comment]
Cleaning up issues
