### ISSUE TITLE
Manually setting user when creating an event

### ISSUE THREAD

**Issue by abinoda** [ankane/ahoy#475]
I have certain controllers/actions where `current_user` is not set. Is there any way to manually pass in `user` or `user_id` when creating an event?

Something like this:

```ruby
ahoy.track "My first event", {language: "Ruby"}, user_id: 5
```

**Comment by abinoda** [comment]
Not sure if this is officially supported but I came across https://github.com/ankane/ahoy/pull/411#discussion_r297085902

It looks like I could do:

```ruby
ahoy.user = User.find(5)
ahoy.track "My first event", {language: "Ruby"}
```

**Comment by ankane** [comment]
Hey @abinoda, can you explain the use case a bit more?

One way to do it right now would be:

```ruby
ahoy = Ahoy::Tracker.new(controller: self, user: user)
ahoy.track "My first event", language: "Ruby"
```

**Comment by abinoda** [comment]
@ankane I have certain controller actions that load users indirectly, ie. through a tokenized URL.

**Comment by ankane** [comment]
Makes sense.

The approach above should work for that. I've added a `user_id` option in the [`user_id_option`](https://github.com/ankane/ahoy/compare/user_id_option) branch, but not sure if it's worth the extra complexity.

**Comment by abinoda** [comment]
Cool. Yeah, I think the solution I have works. Would defer to you on whether offering the option makes sense. Thanks for your continued work on all these valuable open source projects! I previously built [Pull Panda](https://pullpanda.com) which heavily utilized groupdate and chartkick.

**Comment by ankane** [comment]
Thanks @abinoda

**Comment by jacobperia** [comment]
> Hi @ankane. Is this working? I could not get Ahoy to set the user with
> 
> ```
> user = User.find_by(token: "my_token")
> ahoy.track "User's calendar", {}, user_id: user.id
> ```

doesn't seem to work for me either.
