### ISSUE TITLE
Using this gem requires you to make your full code base open source (GPLv3 dependency)

### ISSUE THREAD

**Issue by sbrmnn** [ankane/ahoy#477]
I found that this gem uses device_detector as a dependency which is has a license of GPLv3. The license needs to be updated from MIT to GPLv3 in order to avoid license violations.

GPLv3 makes it not viable for most commercial projects because of the requirement of making your full code base open source.

**Comment by ankane** [comment]
Hey @sbrmnn, `device_detector` is LGPL, not GPL. Neither requires you to open source your code: https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic
