### ISSUE TITLE
Ability to change the namespace in routes

### ISSUE THREAD

**Issue by heaven** [ankane/ahoy#479]
The gem was automatically mounted to the `/` namespace while we need it to reside inside `/api`.

So far I've manually mounted the `Ahoy::Engine` to the desired namespaces and set `Ahoy.api = false`

```ruby
namespace :api do
  mount Ahoy::Engine => "/ahoy"
end
```

But I'm not sure which side-effect this may have.

**Comment by ankane** [comment]
Hey @heaven, that's the recommended approach for changing the path. See #431

**Comment by heaven** [comment]
Hi @ankane, sounds good but would be great to mention this in the docs. Because I felt pretty much like I'm doing it wrong, even though it worked :)
