### ISSUE TITLE
current_visit not always present?

### ISSUE THREAD

**Issue by rassom** [ankane/ahoy#480]
Hi,

I'm using ahoy in a method that I'm calling in ApplicationController like this:
`before_action :sponsor_redirect, if: -> { current_user }`

But ahoy's `current_visit` is "only" present for 99,x% of my users. For a few it's strangely not. 

In my `sponsor_redirect` method mentioned above, I log when `current_visit` is nil like this:

````
    if current_visit.nil?
      Rails.logger.info "No current_visit for UserID : #{current_user.id}"
      return
    end
````

Screenshot from my logs:
![image](https://user-images.githubusercontent.com/594378/113131600-b72fc480-921d-11eb-9800-319964d532c9.png)

Could it be a bug that `current_visit` is sometimes not present even though the user is succesfully authenticated? Any ideas to troubleshoot it further?

Thanks :-)

**Comment by ankane** [comment]
Hey @rassom, Ahoy excludes bots by default, so you can try setting `Ahoy.track_bots = true`. If you have a custom `exclude_method`, that could also be the cause.

**Comment by rassom** [comment]
Hey @ankane

Thanks for the suggestions. 

As you can see in the log screenshot I posted, current_visit is missing for actual, devise-authenticaed users (not bots), so I'm quite sure the tracking bots setting will not help. 

I don't have a custom exclude_method.

Any other ideas?

**Comment by ankane** [comment]
Bots are determined from the user agent (there could be false positives or bots could be logging in). I'd recommend forking and adding debugging to try and better understand what's going on.

**Comment by rassom** [comment]
I'm sure these users are not bots as they have many valid manual data entries. 

Also, I happens for so few users that forking that debugging is probably overkill, so I'll leave it for now. Just thought it could have be an issue other people had experienced before.

Thanks for answering and for the ideas :-)

Happy Easter,
Rasmus

**Comment by rassom** [comment]
PS. Is there a way that I can manually register a visit, i.e. something like `ahoy.track_visit(current_user)´ ? That way I could manually create a visit for users that for some reason don't have a current_visit.

**Comment by ankane** [comment]
Check out the source code for the unofficial `track_visit` method.

**Comment by chen1125he** [comment]
I met this problem too. 
In my case, I used `skip_before_action :track_ahoy_visit` in some pages. when user visit these pages, cookie(ahoy_visit) would be set. With this cookie exists, Ahoy::Visit would not be create when user visit other pages.
So, i set my skip like this `skip_before_action :set_ahoy_cookies, :track_ahoy_visit`

**Comment by rassom** [comment]
> Check out the source code for the unofficial `track_visit` method.

I can't seem to find it :( Would you point me to which file (incl path) I can find it in, please?
