### ISSUE TITLE
Hash format in event 

### ISSUE THREAD

**Issue by Olli** [ankane/ahoy#483]
Hi,
if I track an event like ahoy.track "myevent", property: 1 
than the property: 1 hash is stored as   properties: "{:property => 1}" into the database.
So if I search for that event with Ahoy::Event.where_event("myevent", property: 1) the event isn't will not been found. 
This is IMHO caused by a SQL query like

`
SELECT `ahoy_events`.* FROM `ahoy_events` WHERE `ahoy_events`.`name` = 'myevent' AND (properties REGEXP '[{,]\"property\":1[,}]') 
`

which obviously doesn't match the data stored into the database.
Do I have some kind of misunderstanding in using the tracking or is this a bug?

**Comment by ankane** [comment]
Hey @Olli, it looks like properties aren't being serialized correctly. What database are you using, and what column type does `properties` use?

**Comment by Olli** [comment]
I use 10.5.9-MariaDB-1 (Debian SID)
The format of this field is longtext (on my development machine and also on the server).

**Comment by ankane** [comment]
Try adding the following line to the `Ahoy::Event` model:

```ruby
serialize :properties, JSON
```

Will update the install generator to add it for MariaDB.

**Comment by Olli** [comment]
Thanks :)

**Comment by pupgray** [comment]
If anyone is coming to this after upgrading to Rails 7.2, `serialize` [now takes a keyword argument instead](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize):

```ruby
serialize :properties, coder: JSON
```
