### ISSUE TITLE
Ahoy Event Statement Returning More Data Than Requested

### ISSUE THREAD

**Issue by Tressa-Sanders** [ankane/ahoy#488]
Hello,

I have set things up so Ahoy tracks two custom events:

- Product Audio Play
- Product Audio Ended

They look like this in the Database:
Product Audio Play     {"product": "Blueberry Branch Tee"}
Product Audio Ended  {"product": "Blueberry Branch Tee"}

I am using the following code to see how many times the audio has been played for each product:

@product_audio_plays = Ahoy::Event.where_event("Product Audio Play").group_prop(:product).count

This is not working as expected. In dev, I have only a single entry for Play and a single entry for Ended but the code above is giving me a count of 2 which indicates that it's counting both Product Audio Play and Product Audio Ended even though I specified only "Product Audio Play". 

The SQL I get in dev:
SELECT COUNT(*) AS count_all, JSON_UNQUOTE(JSON_EXTRACT(properties, '$.product')) AS json_unquote_json_extract_properties_product FROM `ahoy_events` GROUP BY JSON_UNQUOTE(JSON_EXTRACT(properties, '$.product')) 

Also, this doesn't work at all in Prod. I get no counts at all even though there is data for it there.  The only difference between the two is that in Dev (running MySQL) the properties field is JSON and in Production (running MariaDB 10.2 the properties field is LONGTEXT which from my understanding is an alias of JSON.

But regardless, I would think in dev at least, it would only count the Product Audio Plays....

**Comment by Tressa-Sanders** [comment]
This fixed it:
@product_audio_plays = Ahoy::Event.where(name: "Product Audio Play").group_prop(:product).count

**Comment by Tressa-Sanders** [comment]
This still doesn't work in prod.  All I get in prod is a count of 18 (down from over 800) but no data. This is the SQL in dev and prod:

SELECT COUNT(*) AS count_all, JSON_UNQUOTE(JSON_EXTRACT(properties, '$.product')) AS json_unquote_json_extract_properties_product FROM `ahoy_events` WHERE `ahoy_events`.`name` = 'Product Audio Play' GROUP BY JSON_UNQUOTE(JSON_EXTRACT(properties, '$.product'))

**Comment by Tressa-Sanders** [comment]
Well group_prop doesn't work properly with MariaDB 10.2.  I changed the code to this and it works in prod. It's ugly but works. 

@product_audio_plays = Ahoy::Event.where(name: "Product Audio Play").group(:properties).count

**Comment by ankane** [comment]
Hey @Tressa-Sanders, thanks for reporting! This functionality was pretty broken (facepalm) and should be fixed in 4.0.1. Let me know if you run into any more issues with it.

**Comment by Tressa-Sanders** [comment]
@ankane Fantastic! I'll have to try it out when I get a chance. Thanks for fixing it.  👍
