### ISSUE TITLE
Warnings issued from device_detector dependency

### ISSUE THREAD

**Issue by ryenski** [ankane/ahoy#494]
The `device_detector` gem, which is required in the [`gemspec`](https://github.com/ankane/ahoy/blob/2be502d0f78af648e64498106915b13fd5178f4c/ahoy_matey.gemspec#L20), is raising multiple errors: 

```
~/.gem/ruby/3.0.2/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
~/.gem/ruby/3.0.2/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
~/.gem/ruby/3.0.2/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
~/.gem/ruby/3.0.2/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
~/.gem/ruby/3.0.2/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
```

This is a known issue with `device_detector` and is addressed here: 
https://github.com/podigee/device_detector/issues/20
https://github.com/podigee/device_detector/issues/89

Explicitly tracking the previous version of `device_detector` silences the warnings, but it's not clear if there is any disadvantage to downgrading: 

```
gem 'device_detector', '1.0.5' # 1.0.6 raises noisy warnings.
gem 'ahoy_matey'
```

**Comment by ankane** [comment]
Hey @SatoshiGardener, thanks for sharing. I'm not sure there's anything we should do with Ahoy (hopefully it's addressed upstream), but good to know users can downgrade to silence the warnings.

**Comment by SatoshiGardener** [comment]
Yeah, probably not worth binding the version; hopefully they will fix the issue in device_detector.

**Comment by BasJoosten** [comment]
Seems like they updated the gem yesterday with a fix included: https://github.com/podigee/device_detector/blob/develop/CHANGELOG.md

**Comment by ankane** [comment]
Great, thanks @BasJoosten!
