### ISSUE TITLE
delayed_job_active_record stops location information update

### ISSUE THREAD

**Issue by Martin-Fritsche** [ankane/ahoy#496]
I have a react on rails app, using delayed_job and ahoy.  In production, the location information does not update, when I have delayed_job running. 

I have tried setting the Ahoy.job_queue to :delayed_job, but that didn't help.  Not sure what I'm doing wrong.  All I know is if I remove delayed_job, the location information gets set.

Also, the referrer and referring_domain only get set sometimes.  Most of the time their value is nil.  How should they work?  I'm I doing something wrong?

**Comment by ankane** [comment]
Hey @Martin-Fritsche, if you're not seeing any errors in the logs, my guess is delayed_job isn't configured to process the queue.

For the referrer fields, Ahoy gets that information from the [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) header, so it won't always be set.

**Comment by Martin-Fritsche** [comment]
Thanks for replying so quickly. I was just discussing this issue with
someone else. They suggested the same thing.  Thanks again
