### ISSUE TITLE
Polymorphic User

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [ankane/ahoy#501]
Hello. Is this currently possible? I am trying the gem out and it's pretty fantastic. However, what if say I want to have 2 different user models integrated into Visit? For example, customers and merchants. I thought a polymorphic association would be neat, but I am stumbled how to properly assign `user_type` upon the creation of a visit.

**Comment by ankane** [comment]
Hey @cheeeeeeeeeen, you should be able to override the `track_visit` method to populate `user_type`, similar to this: https://github.com/ankane/ahoy/issues/434#issuecomment-575870504
