### ISSUE TITLE
Could not find generator 'ahoy:install'

### ISSUE THREAD

**Issue by ianrandmckenzie** [ankane/ahoy#509]
This issue is basically an SEO'd version of the issue a few people have run into where a solution was found in #316:

`Could not find generator 'ahoy:install'.`

This issue seems to be a Rails 6.1+ occurrence as it was with me (but may exist elsewhere).

As mentioned in #316, stop Spring (it will restart when you try to run the generator again):
`bin/spring stop`

I am making and closing this issue for anyone who is a fool like me and ignored 316 and spent too long trying to find an answer elsewhere before finally reading that issue as a last resort. Hah!

**Comment by martingjaldbaek** [comment]
And if that doesn't work, make absolutely sure you installed the "ahoy_matey" gem, not "ahoy" which is entirely unrelated.
