### ISSUE TITLE
Difference between visits.id and visits.visitor_id?

### ISSUE THREAD

**Issue by inkitt** [ankane/ahoy#51]
What is the difference between visits.id and visits.visitor_id? Thanks

**Comment by podopie** [comment]
I believe visits.id is a distinct visit (you can define the length of a visit  based on inactivity in the config), while visits.visitor_id defines a particular visitor, and defined by ip address, etc. visitor_id should tie back to your user_ids (a user can have multiple visitor_ids if they use multiple devices)

**Comment by ankane** [comment]
Thanks for taking this question @podopie
