### ISSUE TITLE
Performance degradation in api_ony and using no cookies

### ISSUE THREAD

**Issue by jfanals** [ankane/ahoy#511]
These were my original settings:
```ruby
Ahoy.api = true
Ahoy.api_only = true
```

When using Chrome, the `ahoy.js` library inside an iframe is not able to read/write cookies, as Chrome is blocking them. Therefore `ahoy.js` not able to write/pass the `visit_token` or `visitor_token` to the main ahoy api.

When migrating from an enabled cookies setup to disabled cookies one, I noticed quite a performance degradation: from an average of 5ms response time to a 20ms average response time for an event creation.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2676548/182814431-0b3d5491-df9c-4634-a072-b248c3162693.png">

These are the current settings:
```ruby
Ahoy.api = true
Ahoy.api_only = true
Ahoy.cookies = false
Ahoy.server_side_visits = :when_needed
```
And on the `ahoy.js` front:
```javascript
ahoy.configure({
  cookies: false,
})
```

My guess is that now that not deferring the visit tracking to `ahoy.js` moves the "work" to the main ahoy api. But I was surprised to see that the performance was degraded so much.

I thought that `Ahoy.server_side_visits = :when_needed` could improve the performance but it didn't.

As I am mainly interested in the events (and not the visits), I am considering overriding the `Ahoy::Store` `track_visit` method with something like this, but it looks too hacky:
```ruby
class Ahoy::Store < Ahoy::DatabaseStore
  def track_visit(data)
    data[:visit_token] = "fixed_visit_token"
    data[:visitor_token] = "fixed_visitor_token"
    super(data)
  end
end
```

Is there any way of keeping the "cookies" performance when tracking server side?

**Comment by jfanals** [comment]
After spending more time investigating, it looks like the performance issue was not due to the settings, but rather the amount of traffic that now has to be processed processed. Thanks to not discarding events with empty `visit_token` & `visitor_token` now the server has more valid requests and therefore more events to process.

All working as expected.

Thank you Andrew for such a great gem :)

**Comment by ankane** [comment]
Great, thanks for the follow up.
