### ISSUE TITLE
Visit tokens and anonymity sets

### ISSUE THREAD

**Issue by Obversity** [ankane/ahoy#516]
Hi there!

**Context:** we started using anonymity sets recently, and put `validates :visit_token, uniqueness: { allow_blank: true }` in our Ahoy::Visit model a while back and have been seeing `Validation failed: Visit token has already been taken` errors every few hours. 

**Question:** When using anonymity set settings, should it be possible for there to be multiple visit records with the same `visitor_token` — e.g. when their masked IP and user agent happens to be the same?

What should happen when two of these requests come through at exactly the same time, given that there's a unique constraint on `visitor_token` in the database?

**Comment by ankane** [comment]
Hey @Obversity, you'll want to remove the `uniqueness` validation. Ahoy already [has code](https://github.com/ankane/ahoy/blob/f05719b2a69c4a392381daa73ef746923f2d1d83/lib/ahoy/database_store.rb#L3-L11) to handle errors from unique constraints.
