### ISSUE TITLE
Limit on ahoy event api

### ISSUE THREAD

**Issue by rekhaagarwal09** [ankane/ahoy#517]
Hello

Is there any limit to events array list size in below api:

https://github.com/ankane/ahoy#events-1

{
  "visit_token": "<visit-token>",
  "visitor_token": "<visitor-token>",
  "**events**": [
    {
      "id": "<optional-random-id>",
      "name": "Viewed item",
      "properties": {
        "item_id": 123
      },
      "time": "2018-01-01T00:00:00-07:00"
    }
  ]
}

We observed that when event array size exceeding to 30, its giving 403 error.
Also its posting upto 10 events at once only.

**Comment by ankane** [comment]
Hey @rekhaagarwal09, there's a limit of 10 events and 8KB per request by default. You can change this with:

```ruby
Ahoy.max_content_length = 16.kilobytes
Ahoy.max_events_per_request = 20
```

It'll return 413 if `max_content_length` is exceeded.

**Comment by rekhaagarwal09** [comment]
hey @ankane Thanks a lot for reply.
We will try this.
