### ISSUE TITLE
skip automatic inclusion of Ahoy::Controller etc.

### ISSUE THREAD

**Issue by tomasc** [ankane/ahoy#522]
It should be possible to not auto-include `Ahoy` everywhere on require.

More specifically, to skip this whole part:
https://github.com/ankane/ahoy/blob/master/lib/ahoy.rb#L117-L131

This would give more control over what and where is being tracked.

If you have a suggestion how to implement this, I'd be happy to make a PR.

**Comment by ankane** [comment]
Hey @tomasc, thanks for the suggestion, but it's not something I'd like to support.

**Comment by tomasc** [comment]
@ankane why not? For example, I run an app that is using multiple controllers and only some should be tracking visits. It would be very helpful if I could be selective where and when to use this library.

I was thinking about this and it could be fairly straightforward. By default working as now, with an option for opting-out.
