### ISSUE TITLE
[Idea] Can support pushing events using WebSocket?

### ISSUE THREAD

**Issue by OuYangJinTing** [ankane/ahoy#532]
Thank you for open sourcing this project, it is amazing.

In my project, there are a large number of buried points. If I use HTTP to send these buried point events, I have to increase my server to receive these requests. However, my project also uses WebSocket, and most of these WebSocket connections are idle. I think it may be a better choice to use WebSocket to push these events instead?

_PS: English is not my native language; please excuse typing errors._

**Comment by ankane** [comment]
Hi @OuYangJinTing, thanks for the suggestion. It's an interesting idea, but don't think it's common enough to add to the gem. You can try creating an Action Cable channel for it in your application with similar logic as the [controllers](https://github.com/ankane/ahoy/tree/master/app/controllers/ahoy).

**Comment by OuYangJinTing** [comment]
> Hi @OuYangJinTing, thanks for the suggestion. It's an interesting idea, but don't think it's common enough to add to the gem. You can try creating an Action Cable channel for it in your application with similar logic as the [controllers](https://github.com/ankane/ahoy/tree/master/app/controllers/ahoy).

Thank you for your reply. I will start trying to implement it after the May Day holiday and hope that it can be used as an extension package for Ahoy later on.💪
