### ISSUE TITLE
exclude Turbo 8 instant-click requests

### ISSUE THREAD

**Issue by francescob** [ankane/ahoy#550]
I'm not sure this is doable at the moment because from a first look seems like new turbo 8 instant-click (aka prefetch) requests are indistinguishable from a normal request, but it would be very important to be able to exclude this request from the tracking

**Comment by francescob** [comment]
I've actually found a header value that can't be used to filter the request, it looks like this:

`"HTTP_X_SEC_PURPOSE"=>"prefetch"`

so it can easily be skipped by writing one line of code in application_controller

Don't know if it's worth to skip it by default though (probably yes)

**Comment by ankane** [comment]
Hi @francescob, you can use `exclude_method` or customize the data store for this (but would need to use client-side analytics to know if a page has been visited).
