### ISSUE TITLE
[Idea] Support Trilogy

### ISSUE THREAD

**Issue by pdsmcgavin** [ankane/ahoy#552]
https://github.blog/2022-08-25-introducing-trilogy-a-new-database-adapter-for-ruby-on-rails/

Trilogy looks to be the default mysql driver for rails in the future. Are there any plans to support it? If not I'm happy to open a PR

**Comment by ankane** [comment]
Hi @pdsmcgavin, thanks for the suggestion! Added in the commit above.

**Comment by pdsmcgavin** [comment]
Awesome, thank you for the quick response
