### ISSUE TITLE
Improve handling of unexpected data passed to EventsController.

### ISSUE THREAD

**Issue by somazx** [ankane/ahoy#553]
Hi,

Should there be some sort of sanity check that `events_json` decodes to an Array?

We noticed a number of errors reported in our exception logging related to [events_controller.rb:25](https://github.com/ankane/ahoy/blob/8e5df402f04bca84498aa7215b7301c9ee56583f/app/controllers/ahoy/events_controller.rb#L25) where the code expects an instance of array. Some values passed in as param `events_json` will result in the code reaching this point with a nil or integer value instead of an instance of array.

In our case, this was the byproduct of automated fuzzing/penetration testing by a bot (Detectify). 

> undefined method `first' for nil:NilClass

params:
```json
{
  "action": "create",
  "controller": "ahoy/events",
  "events_json": "nil"
}
```

>undefined method `first' for 41414141:Integer

params

```json
{
  "action": "create",
  "controller": "ahoy/events",
  "events_json": "41414141"
}
```

**Comment by ankane** [comment]
Hi @somazx, thanks for reporting! Updated in the commit above.
