### ISSUE TITLE
[Idea] Use device hints

### ISSUE THREAD

**Issue by pedrocarmona** [ankane/ahoy#557]
Dear @ankane,

Device detector has [instructions](https://github.com/podigee/device_detector?tab=readme-ov-file#using-client-hint) to improve accuracy of detection, by using `Sec-CH-UA` and `http-x-requested-with/x-requested-with`.

Would be nice to support it in ahoy.

**Comment by ankane** [comment]
Hey @pedrocarmona, thanks for sharing. Added support in the [user-agent-client-hints branch](https://github.com/ankane/ahoy/compare/user-agent-client-hints), but going to wait until Ahoy 6 to merge (not sure when that'll be yet).

**Comment by pedrocarmona** [comment]
Hi @ankane, super nice, thank you!
