### ISSUE TITLE
Additional property to `Visit`

### ISSUE THREAD

**Issue by db0sch** [ankane/ahoy#558]
I'm working on an app with a mobile PWA and would like to track PWA usage (some users do "install" the PWA on their phone, but also keep using the classic web version).
I can easily know if the app is used in "standalone" mode with a bit of JavaScript, and can send these pieces of information by adding them to headers (say before a turbo-load), and would very much like to add this to the Ahoy::Visit object.
I guess we would need to:
- Add the column to the `Ahoy::Visit` table like `standalone_mode`
- Update the visit when we get the information back to the server (which might not be on the first request, as first, we need to evaluate the JS, so probably on a second request).

Would that make sense?
Or should I just use the Ahoy::Event to track this? (even though, I feel like this piece of information should belong to the visit, but I might be wrong).

Thank you for this amazing gem, and your work for the Ruby community

**Comment by ankane** [comment]
Hi @db0sch, adding it to the visit makes sense to me.

```ruby
current_visit&.update!(standalone_mode: true)
```

**Comment by db0sch** [comment]
Thanks a lot for your quick reply @ankane
