### ISSUE TITLE
[Idea] Allow custom attributes server side

### ISSUE THREAD

**Issue by pedrocarmona** [ankane/ahoy#560]
Hi @ankane,

Would be nice if `Ahoy::EventsController` would allow to customize extra data.

Scenario: A controller that inherits from`Ahoy::EventsController`, could add extra data to the event based on subdomain, etc.

Proposal: Refactor the method `create` and split the method into smaller methods, so that it would be possible to inherit and call ahoy.track with extra params.

A workaround is possible by customizing the Ahoy::Store, and performing if statements to check subdomain.

**Comment by ankane** [comment]
Hi @pedrocarmona, thanks for the suggestion. You can achieve this by customizing `track_event` (similar to [this](https://github.com/ankane/ahoy?tab=readme-ov-file#track-additional-data)).
