### ISSUE TITLE
Can `Ahoy::Store` be put in `app/models` vs. `config/initializers`?

### ISSUE THREAD

**Issue by maurice-does-software** [ankane/ahoy#64]
It seems easier during development of an application to have the class defined in models, so that changes to the class are immediate, versus having to reload the rails environment. But I have not looked far enough into the implementation to see if moving that file would break something.

**Comment by chischaschos** [comment]
It worked for me

**Comment by ankane** [comment]
@maurice-does-software For Ahoy 2.0, I'd like to find a place to put the store that is autoloaded by default.
