### ISSUE TITLE
ID-specific filtering?

### ISSUE THREAD

**Issue by cjshort** [ankane/ahoy#65]
Hi,

I am looking to use Ahoy for analytics, it seems like a brilliant gem and I am certainly excited to use it!

I'm wondering if it would be at all possible for me to somehow pass in a custom parameter for each view/event which specifies which current blog category it is on. So that I can create an analytics platform for each individual category while having a master platform which shows global views/events without category-specific filtering?

Any help with this would be insanely appreciated!

**Comment by ankane** [comment]
@cjshort You should be able to add a `category` property to each event.
