### ISSUE TITLE
Ahoy::Visit name dissapears after first usage

### ISSUE THREAD

**Issue by ceigel** [ankane/ahoy#68]
I just installed ahoy and followed the instructions for postgres database. I wanted to look at the visits and after the first function call on Ahoy::Visit, the name disappeared:

[1] pry(main)> Ahoy::Visit.all.map{|v| v.landing_page}
  Visit Load (1.4ms)  SELECT "visits".* FROM "visits"
=> ["http://localhost:3000/en"]
[2] pry(main)> Ahoy::Visit.all.map{|v| v.landing_page}
NameError: uninitialized constant Ahoy::Visit
from (pry):3:in `__pry__'

**Comment by ankane** [comment]
Hey @ceigel, the default visit model won't have an `Ahoy` prefix - it's just `Visit` .
