### ISSUE TITLE
New visit on user log out

### ISSUE THREAD

**Issue by dingels35** [ankane/ahoy#69]
If a user logs out then logs in as a different user, the result is a single Visit record that has Event records with 2 different user_ids.  I'd like for a new Visit record to be created when a user logs out.  Is this possible?

I have a before_filter on my application controller to log all page views.  Is there a way to do something like ahoy.create_a_new_session?  If so I can check to see if ahoy.visit.user.id == current_user.id.

```ruby
before_filter :track_page_load
def track_page_load
  if ahoy.visit.user_id && (current_user.nil? || current_user.id != ahoy.visit.user_id)
    ahoy.create_a_new_session      
  end

  ahoy.track "page_load", url: request.url if request.format.to_s == 'text/html'
end
```

**Comment by ankane** [comment]
You can delete the `ahoy_visit` cookie in your sign out action and a new visit will be automatically created on the next request.

**Comment by joaomm** [comment]
Could you show a code snippet on that ankane?

**Comment by ankane** [comment]
@joaomm You should be able to call `cookies.delete("ahoy_visit")` in your sign out controller.
