### ISSUE TITLE
Add latitude and longitude support

### ISSUE THREAD

**Issue by PeterHatch** [ankane/ahoy#74]
I'd like to have geocoding support latitude and longitude, in addition to country, region, and state.

I think all this would take is adding them to Ahoy::VisitProperties::LOCATION_KEYS, and adding latitude and longitude methods to the LocationDeckhand.

(They still wouldn't be used unless the Visit model responded to latitude= and longitude=, so people like me would need to add those columns to the database; that seems reasonable.)

**Comment by ankane** [comment]
Love it, feel free to submit a pull request.

**Comment by kartikluke** [comment]
This could be pretty useful.

**Comment by ankane** [comment]
@kartikluke #76 has been merged, so you can use it today.

**Comment by kartikluke** [comment]
I'd have to make a migration for the latitude and longitude in visit right?

**Comment by andytime** [comment]
Yes.
