### ISSUE TITLE
Setting track_visits_immediately causing issues with persisting visit to db

### ISSUE THREAD

**Issue by oliverswitzer** [ankane/ahoy#78]
I'm setting track_visits_immediately to true and have been trying to figure out why visits weren't getting persisted... after looking in the `Ahoy::Controller` model I saw that the `set_ahoy_cookies` before_filter gets run before the `track_ahoy_visit`, which only tracks the visit if no cookie has been set (see `new_visit?` method in `Ahoy::Tracker`):

```ruby
   # lib/ahoy/controller

   before_filter :track_ahoy_visit
   
   ...

    def track_ahoy_visit
      if ahoy.new_visit?
        ahoy.track_visit(defer: !Ahoy.track_visits_immediately)
      end
    end
```
if the cookies are always set before the `track_ahoy_visit` filter is called, doesn't this mean that a visit will never be persisted to the db as `ahoy.track_visit` never gets called? 

Cheers,
O

**Comment by ankane** [comment]
@oliverswitzer The response header will be set, but not the request header, which is what `new_visit?` checks.  Did you restart your Rails server after the change?

**Comment by ankane** [comment]
Cleaning up issues (no response)
