### ISSUE TITLE
can't write unknown attribute `visit_id'

### ISSUE THREAD

**Issue by casertap** [ankane/ahoy#79]
I can not manage to have something written in the table visit.
I set a Blog model: visitable and when I save a new Blog object I get the following error message:
can't write unknown attribute `visit_id'

My config is simple:
````
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
  # customize here
    def exclude?
        false
    end
end
```

This call to track method is working
````
class BlogsController < SecureController
  def index
      ahoy.track "Ask blog page", title: "title"
     @section_name = 'Blog / Press'
     render :template => 'angular/blogs/index' , :layout => 'angular/welcome'
  end
...
````

````
class Blog < ActiveRecord::Base
  visitable
...
````

I also included the ahoy.js in my pages but I mainly want to track event from the backend point of view.
How do I configure ahoy to track visited pages?

**Comment by casertap** [comment]
ok so I could save some data in the visit table using this issue:
https://github.com/ankane/ahoy/issues/41
by setting:
````
Ahoy.quiet = false
````
But still I have the "can't write unknown attribute `visit_id'" error on mu visitable blog.rb

**Comment by ankane** [comment]
Be sure to add a `visit_id` column to your `Blog` model with a migration.

**Comment by casertap** [comment]
It is working thanks

**Comment by ankane** [comment]
Cleaning up issues
