### ISSUE TITLE
Using Mongo for Events and Mysql for Visits

### ISSUE THREAD

**Issue by casertap** [ankane/ahoy#82]
I will have a lot of events (every user action) so I want them to be very fast so I want to use mongoDB for that.

Now new visits will occur a lot less often and request query are done many times on the visit table to checks if the visit is already save so I think using a Mysql solution for that is a good idea.
More over I can perform complex joins query on my user and visit to perform cohort analysis so that's good.

I could not manage to setup the visit table with mysql and the ahoy_events with mongodb.
Each time it is either one or the other but I could not dissociate them.

Is that even possible with the ahoy gem?

**Comment by ankane** [comment]
Hey @casertap, you'll need to choose one of the stores as the base, and then override one of the methods.  One way would be to:

- use the ActiveRecord store
- override `track_events` to store events in MongoDB

Or you could start with the Mongoid store and override `track_visits`.

**Comment by ankane** [comment]
Cleaning up issues
