### ISSUE TITLE
Can't access event properties 

### ISSUE THREAD

**Issue by mklemme** [ankane/ahoy#86]
I'm having trouble accessing event properties. I've assigned the result to a varaible `e` and tried everything to get properties but it returns `TypeError: no implicit conversion of Hash into String`. Any ideas? 

Activerecord query
```bash
=> #<Ahoy::Event:0x000001037b3938
  id: "ff9ab428-01b7-4dc1-aefe-5af027d0a3c9",
  visit_id: "da53b65f-004e-4ac9-95b6-f88e2eb5a314",
  user_id: nil,
  name: "$view",#<Ahoy::Event:0x81bd9c9c>
```

I'm also using the example `track_visit` method provided:
```ruby
def track_event(name, properties, options, &block)
    event =
    event_model.new do |e|
      e.id = options[:id]
      e.visit_id = ahoy.visit_id
      e.user = user
      e.name = name
      e.properties = properties.to_json
      e.time = options[:time]
    end
    yield(event) if block_given?
    begin
      event.save!
    rescue *unique_exception_classes
      # do nothing
    end
  end
```

**Comment by ankane** [comment]
@mklemme if you replace `properties.to_json` with `properties`, the error should go away.  Rails handles the serialization, so it expects hash instead of a string. `to_json` generates a string.

**Comment by mklemme** [comment]
Awesome. It also looks like I had serialization in my model file from an example on here. Removed it and it worked.

**Comment by marckohlbrugge** [comment]
I'm running into the same problem, yet when I remove `.to_json` when tracking an event in my controller using `ahoy.track` I get the following error message: `no implicit conversion of Hash into String`

This suggests I _do_ need to use a string. My `schema.rb` lists the following column: `t.jsonb    "properties"`

Any suggestions?

**Comment by mklemme** [comment]
@marckohlbrugge What was the error?

**Comment by marckohlbrugge** [comment]
@marckohlbrugge Same error as you: `TypeError: no implicit conversion of Hash into String`. When running the ahoy generators the `-d` was ignored resulting in the serialize call in the Event model.

**Comment by mklemme** [comment]
@marckohlbrugge I copied the custom initializer when I installed it. Might be worth doing that then building anything custom from there? The Active record default init: https://github.com/ankane/ahoy/blob/master/lib/ahoy/stores/active_record_store.rb

**Comment by marckohlbrugge** [comment]
@mklemme Thanks! Don't have a need to customise any of this right now, but will keep it in mind.
