### ISSUE TITLE
current_visit is nil

### ISSUE THREAD

**Issue by jasonaibrahim** [ankane/ahoy#88]
I'm using the log store only. In my controller I call ahoy.track_visit. Interestingly, the visit gets logged in log/visits.log, but if I try to print out current_visit it says its nil. 

The same goes for overriding the track_visit method in the initializer. It will throw an error saying current_visit is undefined.

```ruby
module Api
  module V1
    class SessionsController < ApplicationController

      def index
        render json: current_user.as_json
        ahoy.track_visit
        p current_visit # nil
      end

      def destroy
        sign_out current_user
      end

    end
  end
end
```

**Comment by jasonaibrahim** [comment]
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
Rails 4.2.0

**Comment by ankane** [comment]
@jasonaibrahim `current_visit` will always be `nil` for the log store.  Ahoy doesn't try to lookup the visit from the logs (this would be problematic for a number of reasons).  I'd suggest trying a database store.

**Comment by jasonaibrahim** [comment]
I'm trying out the database store now, works just as I expect. Much more powerful than logging anyway. I was exploring logging the events and visits to s3, wanted to get a hold of the current_visit and essentially just log it manually to a bucket, but I'll stick with the database store.

**Comment by ankane** [comment]
At Instacart, we start with the database store and override the `track_event` method to log events, so visits are stored in the DB and events are logged.
