### ISSUE TITLE
Javascript ahoy.track does not track additional values

### ISSUE THREAD

**Issue by pdoggi** [ankane/ahoy#89]
@ankane, Thanks for the awesome gems. It has saved me a lot of time.

I'm trying to track additional values in events so I've added the following method to `/config/initializers/ahoy.rb`:

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore

  def track_event(name, properties, options)
    super do |event|
      #saves something
    end
  end
end
``` 
The above method gets triggered when I use `ahoy.track` in one of my app controllers, but in javascript, `ahoy.track` does not seem to trigger this method. I'm not sure why since the route `/ahoy/events` triggers the ruby version of `ahoy.track` in line 27 of `ahoy/app/controllers/ahoy/events_controller.rb`, I presume.

Maybe it has to do with where the `ahoy.track` is being called,
  1. from within my application and therefore the method in the initializer exists, 

     *__-versus-__*

  2. from outside my application in the gem's `events_controller.rb`

Any thoughts on why this behavior occurs and how can I fix it? Let me know if you need more information. 

Thank you!

**Comment by ankane** [comment]
@pdoggi your custom `track_event` method should be called in both cases

**Comment by pdoggi** [comment]
Ah, okay. I'll dig deeper to see why I'm experiencing something different. Thanks for your time, @ankane !

**Comment by tom-alcorn** [comment]
@pdoggi did you ever figure this out? I have the same issue.

**Comment by mltcx** [comment]
I had the same issue and you have to convert JSON keys to symbols in ruby. In my case, the additional values are passed through the properties. I uses the symbolize_keys! method in rails.

```ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordTokenStore

  def track_event(name, properties, options)
    properties.symbolize_keys!

    super do |event|
      # additional values
    end
  end

end
```

**Comment by ankane** [comment]
Thanks for sharing your solution @mltcx
