### ISSUE TITLE
ActiveRecord::AssociationTypeMismatch

### ISSUE THREAD

**Issue by acrogenesis** [ankane/ahoy#90]
I've just installed ahoy to my Rails 4.2.1 app, i'm running ruby-2.2.1 and use devise for authentication.

To install I used
`rails generate ahoy:stores:active_record -d postgresql`
I've added `//= require ahoy` and at the end of my application.js I added
``` ahoy.trackView();
ahoy.trackClicks();
```

When I visit any page I get this error at `/events` and a similar at `/visits`

ActiveRecord::AssociationTypeMismatch at /events
================================================

> User(#70335852040600) expected, got User(#70335852040600)

activerecord (4.2.1) lib/active_record/associations/association.rb, line 216
----------------------------------------------------------------------------

``` ruby
  211           # the kind of the class of the associated objects. Meant to be used as
  212           # a sanity check when you are about to assign an associated record.
  213           def raise_on_type_mismatch!(record)
  214             unless record.is_a?(reflection.klass) || record.is_a?(reflection.class_name.constantize)
  215               message = "#{reflection.class_name}(##{reflection.klass.object_id}) expected, got #{record.class}(##{record.class.object_id})"
> 216               raise ActiveRecord::AssociationTypeMismatch, message
  217             end
  218           end
  219   
  220           # Can be redefined by subclasses, notably polymorphic belongs_to
  221           # The record parameter is necessary to support polymorphic inverses as we must check for
```

App backtrace
-------------

Full backtrace
--------------

 - activerecord (4.2.1) lib/active_record/associations/association.rb:216:in `raise_on_type_mismatch!'
 - activerecord (4.2.1) lib/active_record/associations/belongs_to_association.rb:12:in `replace'
 - activerecord (4.2.1) lib/active_record/associations/singular_association.rb:17:in `writer'
 - activerecord (4.2.1) lib/active_record/associations/builder/association.rb:123:in `user='
 - ahoy_matey (1.1.1) lib/ahoy/stores/active_record_store.rb:31:in `block in track_event'
 - activerecord (4.2.1) lib/active_record/core.rb:283:in `initialize'
 - activerecord (4.2.1) lib/active_record/inheritance.rb:61:in `new'
 - ahoy_matey (1.1.1) lib/ahoy/stores/active_record_store.rb:28:in `track_event'
 - ahoy_matey (1.1.1) lib/ahoy/tracker.rb:19:in `track'
 - ahoy_matey (1.1.1) app/controllers/ahoy/events_controller.rb:28:in `block in create'
 - ahoy_matey (1.1.1) app/controllers/ahoy/events_controller.rb:18:in `create'
 - actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 - actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
 - actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
 - activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 - actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
 - actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
 - actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
 - actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
 - railties (4.2.1) lib/rails/engine.rb:518:in `call'
 - railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
 - actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/deflater.rb:35:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
 - warden (1.2.3) lib/warden/manager.rb:34:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/etag.rb:24:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/head.rb:13:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rollbar (1.4.5) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
 - rollbar (1.4.5) lib/rollbar.rb:754:in `scoped'
 - rollbar (1.4.5) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - rollbar (1.4.5) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
 - railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
 - ahoy_matey (1.1.1) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/runtime.rb:18:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/lock.rb:17:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - font_assets (0.1.11) lib/font_assets/middleware.rb:29:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - hirefire-resource (0.3.5) lib/hirefire/middleware.rb:29:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - railties (4.2.1) lib/rails/engine.rb:518:in `call'
 - railties (4.2.1) lib/rails/application.rb:164:in `call'
 - newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
 - rack (1.6.0) lib/rack/content_length.rb:15:in `call'
 - thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
 - thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
 - thin (1.6.3) lib/thin/connection.rb:53:in `process'
 - thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
 - eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
 - thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
 - thin (1.6.3) lib/thin/server.rb:162:in `start'
 - rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
 - rack (1.6.0) lib/rack/server.rb:286:in `start'
 - railties (4.2.1) lib/rails/commands/server.rb:80:in `start'
 - railties (4.2.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
 - railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `server'
 - railties (4.2.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
 - railties (4.2.1) lib/rails/commands.rb:17:in `<top (required)>'
 - bin/rails:4:in `<main>'

**Comment by ankane** [comment]
Hi Adrian, thanks for reporting this and submitting a pull request. For some reason in your setup, the Rails reloader and Ahoy are not playing nicely.  Try putting your `Ahoy::Store` class in `app/models/ahoy/store.rb` to see if the error goes away.

**Comment by ankane** [comment]
Cleaning up issues
