### ISSUE TITLE
Why meta data is in Visit only?

### ISSUE THREAD

**Issue by Fodoj** [ankane/ahoy#95]
Would be handy to have all meta data inside events table. But currently I need to make another query against visits to get it for every event. So I wonder what is the reasoning behind this decision :)

**Comment by ankane** [comment]
By default, Ahoy tries to keep things normalized.  You should be able to take advantage of `joins` and `includes` to reduce the number of queries you need.  If you'd like to denormalize (which can totally make sense), you should be able to override the `track_event` method.

**Comment by Fodoj** [comment]
Okay, thanks!
