### ISSUE TITLE
Visitable: mongoid support

### ISSUE THREAD

**Issue by forme** [ankane/ahoy#96]
I've looked into the code. It seems that visitable is only supported by ActiveRecord. How can I rewrite this method to add mongoid support?

Thanks for any advice!

**Comment by ankane** [comment]
Thanks for the interest in helping out!  It may be as easy as adding:

```ruby
ActiveModel::Callbacks.send(:include, Ahoy::Model)
```

to the end of `lib/ahoy.rb`.

**Comment by ankane** [comment]
Cleaning up issues. Future readers, feel free to submit a PR if you care about this.
