### ISSUE TITLE
Error when uploading an image and tracking event

### ISSUE THREAD

**Issue by nguyenchiencong** [ankane/ahoy#98]
ActiveRecord::StatementInvalid (PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8"

In development environment, if I create a record with an image uploaded, Ahoy will try to track the event thus creating an error due to trying to record a byte sequence in the properties column.

Any hint?

**Comment by ankane** [comment]
@nguyenchiencong When calling `ahoy.track(name, properties)`, you'll need to exclude the image from properties.

**Comment by nguyenchiencong** [comment]
Do you mean something like this?

``` ruby
request.filtered_parameters.delete("image")
ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
```

**Comment by ankane** [comment]
Since `delete` modifies `filtered_parameters`, a safer approach would be:

```ruby
ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters.except("image")
```

**Comment by nguyenchiencong** [comment]
Thanks @ankane !
